//! Custom message types generated by `horus.msggen`.
//!
//! This file is the committed empty stub. `horus.msggen.builder` rewrites it,
//! adding one `mod <name>;` per registered message and expanding
//! `register_custom_messages` to register each `#[pyclass]` on the module.
//!
//! It exists as a stub because `lib.rs` must declare `mod custom_messages;`
//! unconditionally — otherwise cargo never compiles what the generator writes,
//! and the generated types are absent from the extension with no error
//! anywhere. That was the state before: `builder.py` wrote
//! `horus_py/src/custom_messages/`, `lib.rs` did not mention it, and the files
//! were dead on arrival.

use pyo3::prelude::*;

/// Register generated message classes on the `horus._horus` module.
///
/// The stub registers nothing. Regenerated by `horus.msggen.build_messages()`.
pub fn register_custom_messages(_m: &Bound<'_, PyModule>) -> PyResult<()> {
    Ok(())
}
