FROM fedora:39

ENV CARGO_HOME=/root/.cargo
ENV PATH="/root/.cargo/bin:${PATH}"

RUN dnf install -y \
    curl gcc glibc-devel pkg-config openssl-devel systemd-devel alsa-lib-devel \
    clang-devel git \
    && dnf clean all

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable

WORKDIR /horus
COPY . .

RUN cargo build --no-default-features --release -p horus_core -p horus_library -p horus_sys -p horus_manager

CMD ["cargo", "test", "--no-default-features", "-p", "horus_sys", "--", "--test-threads=1"]
