FROM archlinux:latest

ENV CARGO_HOME=/root/.cargo
ENV PATH="/root/.cargo/bin:${PATH}"

RUN pacman -Sy --noconfirm \
    gcc pkg-config openssl systemd alsa-lib \
    clang git rust cargo

WORKDIR /horus
COPY . .

RUN cargo build --no-default-features -p horus_core -p horus_library -p horus_sys

CMD ["cargo", "test", "--no-default-features", "-p", "horus_sys", "--", "--test-threads=1"]
