//! The C ABI for generated message types.
//!
//! A generated type reaches Rust and reads correctly from C++ and Python once
//! the header and layout contract exist. Actually *publishing* one from C++
//! needs entry points, and the ones HORUS ships live in `libhorus_cpp.a`:
//! `impl_pod_topic_c_api!` emits `#[no_mangle] extern "C"` functions into that
//! archive, which a user cannot add to without editing the HORUS source tree
//! and rebuilding it.
//!
//! Neither that macro nor `impl_topic_ffi!` can be reused from outside the
//! crate either — they are not exported, and their bodies name `paste::paste!`,
//! `FfiPublisher`, `HorusPublisher` and a `topic_ffi::` path unqualified, all of
//! which resolve only inside `horus_cpp`.
//!
//! So the entry points are generated per project instead, into a small
//! staticlib the project links alongside `libhorus_cpp.a`. Nothing in the HORUS
//! tree changes.
//!
//! Symbols are prefixed `horus_gen_<package>_<type>_` so two projects loaded
//! into one process cannot collide, and so a name can never clash with the
//! built-in `horus_<type>_` set.

use super::{MsgDef, Package};

/// Lowercase-with-underscores, from a CamelCase message name.
fn snake(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    for (i, c) in name.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i != 0 {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// The C symbol prefix for one type's entry points.
///
/// Public because the Python emitter binds the same symbols with `ctypes`.
/// Deriving them separately there would be two spellings of one ABI, and the
/// disagreement would surface as a `AttributeError` at the user's first
/// `publish`, not here.
pub fn symbol(pkg: &Package, m: &MsgDef) -> String {
    format!(
        "horus_gen_{}_{}",
        pkg.name.replace('-', "_"),
        snake(&m.name)
    )
}

/// `Cargo.toml` for the FFI staticlib.
pub fn cargo_toml(pkg: &Package, horus_src: &std::path::Path, version: &str) -> String {
    let h = horus_src.display();
    let name = pkg.name.replace('-', "_");
    format!(
        "# Generated by `horus msg gen` from msgs/*.hmsg — do not edit manually.\n\
         # Edits are lost the next time messages are generated.\n\
         [package]\n\
         name = \"{name}_msgs_ffi\"\n\
         version = \"{version}\"\n\
         edition = \"2021\"\n\
         \n\
         # Its own workspace root. Unlike the `msgs` crate this is not a path\n\
         # dependency of the project, so it is never adopted as a member of the\n\
         # `.horus` workspace — and cargo then refuses to build it with\n\
         # \"current package believes it's in a workspace when it's not\".\n\
         [workspace]\n\
         \n\
         [lib]\n\
         path = \"src/lib.rs\"\n\
         # staticlib so the C++ link is self-contained, rlib so `cargo check`\n\
         # over the project still sees it as an ordinary dependency, cdylib so\n\
         # Python can open the same entry points with `ctypes.CDLL` — a static\n\
         # archive is not loadable at runtime, and without this the generated\n\
         # Python module would have types it cannot publish.\n\
         crate-type = [\"staticlib\", \"rlib\", \"cdylib\"]\n\
         \n\
         [dependencies]\n\
         horus_core = {{ path = \"{h}/horus_core\" }}\n\
         {name}_msgs = {{ path = \"../msgs\" }}\n"
    )
}

/// `src/lib.rs` for the FFI staticlib.
pub fn lib_rs(pkg: &Package) -> String {
    let crate_name = format!("{}_msgs", pkg.name.replace('-', "_"));
    let mut out = String::new();

    out.push_str(&format!(
        "//! C entry points for `{}`'s generated message types.\n\
         //!\n\
         //! Generated by `horus msg gen`. DO NOT EDIT — rewritten whenever the\n\
         //! definitions change. Edit the `.hmsg` files instead.\n\
         \n\
         use std::ffi::CStr;\n\
         use std::os::raw::c_char;\n\
         \n\
         use horus_core::communication::Topic;\n\n",
        pkg.name
    ));

    out.push_str(
        "/// Borrow a C string as `&str`, or return the fallback.\n\
         ///\n\
         /// # Safety\n\
         /// `s` must be null or a valid NUL-terminated C string.\n\
         unsafe fn as_str<'a>(s: *const c_char) -> Option<&'a str> {\n\
         \x20   if s.is_null() {\n\
         \x20       return None;\n\
         \x20   }\n\
         \x20   CStr::from_ptr(s).to_str().ok()\n\
         }\n\n",
    );

    // A null return is the only thing the C ABI can say, and "the topic did
    // not open" and "your build disagrees with the publisher about this
    // message's field layout" are very different problems. The layout-mismatch
    // error carries both hashes and the fix; throwing it away would leave a C++
    // or Python caller with a `valid() == false` and nothing to go on.
    out.push_str(
        "/// Report why a topic could not be opened, then return null.\n\
         ///\n\
         /// The C ABI can only signal failure as a null handle. The error\n\
         /// behind it — in particular the layout-mismatch one, which names both\n\
         /// hashes and says to rebuild both sides — is worth more than the\n\
         /// null, so it goes to stderr on the way out.\n\
         fn open_failed<T>(what: &str, topic: &str, e: horus_core::error::HorusError) -> *mut T {\n\
         \x20   eprintln!(\"horus: {what} for topic '{topic}' could not be opened: {e}\");\n\
         \x20   std::ptr::null_mut()\n\
         }\n\n",
    );

    for m in &pkg.messages {
        let sym = symbol(pkg, m);
        let ty = format!("{crate_name}::{}", m.name);

        out.push_str(&format!(
            "// ─── {} ─────────────────────────────────────────────────────\n\n",
            m.name
        ));

        // Publisher
        out.push_str(&format!(
            "/// Open a publisher on `topic`. Returns null if the name is not\n\
             /// valid UTF-8 or the topic cannot be created.\n\
             ///\n\
             /// # Safety\n\
             /// `topic` must be null or a valid NUL-terminated C string. The\n\
             /// returned handle must be released with `{sym}_publisher_free`\n\
             /// exactly once, and must not be used from more than one thread.\n\
             #[no_mangle]\n\
             pub unsafe extern \"C\" fn {sym}_publisher_new(topic: *const c_char) -> *mut Topic<{ty}> {{\n\
             \x20   let Some(name) = as_str(topic) else {{\n\
             \x20       return std::ptr::null_mut();\n\
             \x20   }};\n\
             \x20   // `{tyname}::topic`, not `Topic::<{tyname}>::new`: the checked\n\
             \x20   // opener binds LAYOUT_HASH to the topic. Every C++ and Python\n\
             \x20   // caller reaches shared memory through here, and this is the\n\
             \x20   // one place a cross-language layout disagreement can be caught.\n\
             \x20   match <{ty}>::topic(name) {{\n\
             \x20       Ok(t) => Box::into_raw(Box::new(t)),\n\
             \x20       Err(e) => open_failed(\"publisher\", name, e),\n\
             \x20   }}\n\
             }}\n\n",
            tyname = m.name
        ));

        out.push_str(&format!(
            "/// Publish one message. A null handle or message is ignored.\n\
             ///\n\
             /// # Safety\n\
             /// `handle` must come from `{sym}_publisher_new` and not yet be\n\
             /// freed. `msg` must point to a readable, initialised value.\n\
             #[no_mangle]\n\
             pub unsafe extern \"C\" fn {sym}_publisher_send(\n\
             \x20   handle: *mut Topic<{ty}>,\n\
             \x20   msg: *const {ty},\n\
             ) {{\n\
             \x20   if handle.is_null() || msg.is_null() {{\n\
             \x20       return;\n\
             \x20   }}\n\
             \x20   (*handle).send(std::ptr::read(msg));\n\
             }}\n\n"
        ));

        out.push_str(&format!(
            "/// Release a publisher handle. Null is ignored, so a double free\n\
             /// through a nulled variable is safe.\n\
             ///\n\
             /// # Safety\n\
             /// `handle` must come from `{sym}_publisher_new` and must not be\n\
             /// freed twice.\n\
             #[no_mangle]\n\
             pub unsafe extern \"C\" fn {sym}_publisher_free(handle: *mut Topic<{ty}>) {{\n\
             \x20   if !handle.is_null() {{\n\
             \x20       drop(Box::from_raw(handle));\n\
             \x20   }}\n\
             }}\n\n"
        ));

        // Subscriber
        out.push_str(&format!(
            "/// Open a subscriber on `topic`. Returns null if the name is not\n\
             /// valid UTF-8 or the topic cannot be created.\n\
             ///\n\
             /// # Safety\n\
             /// `topic` must be null or a valid NUL-terminated C string. The\n\
             /// returned handle must be released with `{sym}_subscriber_free`\n\
             /// exactly once, and must not be used from more than one thread —\n\
             /// the transport's consumer contract is single-threaded per handle.\n\
             #[no_mangle]\n\
             pub unsafe extern \"C\" fn {sym}_subscriber_new(topic: *const c_char) -> *mut Topic<{ty}> {{\n\
             \x20   let Some(name) = as_str(topic) else {{\n\
             \x20       return std::ptr::null_mut();\n\
             \x20   }};\n\
             \x20   // Checked, for the same reason the publisher is: a subscriber\n\
             \x20   // that disagrees about field layout reads the right number of\n\
             \x20   // bytes and the wrong values out of them.\n\
             \x20   match <{ty}>::topic(name) {{\n\
             \x20       Ok(t) => Box::into_raw(Box::new(t)),\n\
             \x20       Err(e) => open_failed(\"subscriber\", name, e),\n\
             \x20   }}\n\
             }}\n\n"
        ));

        out.push_str(&format!(
            "/// Take one message if any is waiting. Returns true when `out` was\n\
             /// written.\n\
             ///\n\
             /// # Safety\n\
             /// `handle` must come from `{sym}_subscriber_new` and not yet be\n\
             /// freed. `out` must point to writable storage of at least\n\
             /// `sizeof({})` bytes, correctly aligned.\n\
             #[no_mangle]\n\
             pub unsafe extern \"C\" fn {sym}_subscriber_recv(\n\
             \x20   handle: *mut Topic<{ty}>,\n\
             \x20   out: *mut {ty},\n\
             ) -> bool {{\n\
             \x20   if handle.is_null() || out.is_null() {{\n\
             \x20       return false;\n\
             \x20   }}\n\
             \x20   match (*handle).try_recv() {{\n\
             \x20       Some(v) => {{\n\
             \x20           std::ptr::write(out, v);\n\
             \x20           true\n\
             \x20       }}\n\
             \x20       None => false,\n\
             \x20   }}\n\
             }}\n\n",
            m.name
        ));

        out.push_str(&format!(
            "/// Release a subscriber handle. Null is ignored.\n\
             ///\n\
             /// # Safety\n\
             /// `handle` must come from `{sym}_subscriber_new` and must not be\n\
             /// freed twice.\n\
             #[no_mangle]\n\
             pub unsafe extern \"C\" fn {sym}_subscriber_free(handle: *mut Topic<{ty}>) {{\n\
             \x20   if !handle.is_null() {{\n\
             \x20       drop(Box::from_raw(handle));\n\
             \x20   }}\n\
             }}\n\n"
        ));
    }

    out
}

/// The C++ side: `extern "C"` declarations plus RAII wrappers.
///
/// Emitted into the same header as the structs so a user includes one file.
pub fn cpp_bindings(pkg: &Package) -> String {
    let mut out = String::new();
    out.push_str(
        "// ─── Topic access ───────────────────────────────────────────────────\n\
         //\n\
         // These call into the generated staticlib, which is linked alongside\n\
         // libhorus_cpp.a. The built-in message types get their entry points\n\
         // from that archive; a generated type cannot, because adding symbols to\n\
         // it would mean editing and rebuilding the HORUS source tree.\n\n\
         extern \"C\" {\n",
    );

    for m in &pkg.messages {
        let sym = symbol(pkg, m);
        out.push_str(&format!(
            "void* {sym}_publisher_new(const char* topic);\n\
             void  {sym}_publisher_send(void* handle, const {}* msg);\n\
             void  {sym}_publisher_free(void* handle);\n\
             void* {sym}_subscriber_new(const char* topic);\n\
             bool  {sym}_subscriber_recv(void* handle, {}* out);\n\
             void  {sym}_subscriber_free(void* handle);\n",
            m.name, m.name
        ));
    }
    out.push_str("}  // extern \"C\"\n\n");

    for m in &pkg.messages {
        let sym = symbol(pkg, m);
        // Move-only: the handle is owned, and copying it would free twice.
        out.push_str(&format!(
            "/// Publisher for `{name}`. Move-only: the handle is owned.\n\
             class {name}Publisher {{\n\
             public:\n\
             \x20   explicit {name}Publisher(const char* topic)\n\
             \x20       : handle_({sym}_publisher_new(topic)) {{}}\n\
             \x20   ~{name}Publisher() {{ {sym}_publisher_free(handle_); }}\n\
             \x20   {name}Publisher(const {name}Publisher&) = delete;\n\
             \x20   {name}Publisher& operator=(const {name}Publisher&) = delete;\n\
             \x20   {name}Publisher({name}Publisher&& o) noexcept : handle_(o.handle_) {{\n\
             \x20       o.handle_ = nullptr;\n\
             \x20   }}\n\
             \x20   {name}Publisher& operator=({name}Publisher&& o) noexcept {{\n\
             \x20       if (this != &o) {{\n\
             \x20           {sym}_publisher_free(handle_);\n\
             \x20           handle_ = o.handle_;\n\
             \x20           o.handle_ = nullptr;\n\
             \x20       }}\n\
             \x20       return *this;\n\
             \x20   }}\n\
             \x20   /// False when the topic could not be opened.\n\
             \x20   bool valid() const {{ return handle_ != nullptr; }}\n\
             \x20   void send(const {name}& msg) {{ {sym}_publisher_send(handle_, &msg); }}\n\
             \n\
             private:\n\
             \x20   void* handle_;\n\
             }};\n\n",
            name = m.name
        ));

        out.push_str(&format!(
            "/// Subscriber for `{name}`. Move-only, and single-threaded: the\n\
             /// transport's consumer contract is one reader per handle.\n\
             class {name}Subscriber {{\n\
             public:\n\
             \x20   explicit {name}Subscriber(const char* topic)\n\
             \x20       : handle_({sym}_subscriber_new(topic)) {{}}\n\
             \x20   ~{name}Subscriber() {{ {sym}_subscriber_free(handle_); }}\n\
             \x20   {name}Subscriber(const {name}Subscriber&) = delete;\n\
             \x20   {name}Subscriber& operator=(const {name}Subscriber&) = delete;\n\
             \x20   {name}Subscriber({name}Subscriber&& o) noexcept : handle_(o.handle_) {{\n\
             \x20       o.handle_ = nullptr;\n\
             \x20   }}\n\
             \x20   {name}Subscriber& operator=({name}Subscriber&& o) noexcept {{\n\
             \x20       if (this != &o) {{\n\
             \x20           {sym}_subscriber_free(handle_);\n\
             \x20           handle_ = o.handle_;\n\
             \x20           o.handle_ = nullptr;\n\
             \x20       }}\n\
             \x20       return *this;\n\
             \x20   }}\n\
             \x20   bool valid() const {{ return handle_ != nullptr; }}\n\
             \x20   /// True when `out` was written.\n\
             \x20   bool recv({name}& out) {{ return {sym}_subscriber_recv(handle_, &out); }}\n\
             \n\
             private:\n\
             \x20   void* handle_;\n\
             }};\n\n",
            name = m.name
        ));
    }
    out
}
