//! The generated Python module.
//!
//! `ctypes.Structure` with an explicit `_pack_`-free `_fields_` list, which
//! gives the same `repr(C)` layout the Rust and C++ sides use, plus the layout
//! hash as a module constant.
//!
//! The struct is checked against the size this generator computed for Rust, at
//! import time. A mismatch raises immediately and names the type, rather than
//! producing a shorter or longer read against shared memory.

use super::{canonical, layout, Package, Prim, Type};

fn ctypes_name(p: Prim) -> &'static str {
    match p {
        Prim::U8 => "ctypes.c_uint8",
        Prim::U16 => "ctypes.c_uint16",
        Prim::U32 => "ctypes.c_uint32",
        Prim::U64 => "ctypes.c_uint64",
        Prim::I8 => "ctypes.c_int8",
        Prim::I16 => "ctypes.c_int16",
        Prim::I32 => "ctypes.c_int32",
        Prim::I64 => "ctypes.c_int64",
        Prim::F32 => "ctypes.c_float",
        Prim::F64 => "ctypes.c_double",
        // Rust's bool is one byte; c_bool's size is not guaranteed to be.
        Prim::Bool => "ctypes.c_uint8",
    }
}

fn render(t: &Type) -> String {
    match t {
        Type::Prim(p) => ctypes_name(*p).to_string(),
        Type::Array(elem, n) => format!("{} * {}", render(elem), n),
        Type::Ref(r) => r.short.clone(),
    }
}

pub fn module(pkg: &Package, env: &layout::Env) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "\"\"\"Message types for `{}`.\n\
         \n\
         Generated by `horus msg gen` from `msgs/*.hmsg`. DO NOT EDIT — this file\n\
         is rewritten whenever the definitions change. Edit the `.hmsg` files\n\
         instead.\n\
         \"\"\"\n\n\
         import ctypes\n\n",
        pkg.name
    ));

    for m in &pkg.messages {
        out.push_str(&format!("class {}(ctypes.Structure):\n", m.name));
        if m.doc.is_empty() {
            out.push_str(&format!(
                "    \"\"\"Generated from {}:{}.\"\"\"\n\n",
                m.src
                    .file_name()
                    .map(|s| s.to_string_lossy().to_string())
                    .unwrap_or_default(),
                m.line
            ));
        } else {
            out.push_str("    \"\"\"");
            out.push_str(&m.doc.join("\n    "));
            out.push_str(&format!(
                "\n\n    Generated from {}:{}.\n    \"\"\"\n\n",
                m.src
                    .file_name()
                    .map(|s| s.to_string_lossy().to_string())
                    .unwrap_or_default(),
                m.line
            ));
        }

        out.push_str("    _fields_ = [\n");
        for f in &m.fields {
            out.push_str(&format!("        (\"{}\", {}),\n", f.name, render(&f.ty)));
        }
        out.push_str("    ]\n\n");

        out.push_str(&format!(
            "    #: FNV-1a of the canonical layout string — the number\n\
             \x20   #: ``horus msg hash {}`` prints.\n\
             \x20   LAYOUT_HASH = {}\n",
            m.name,
            canonical::layout_hash(m)
        ));
        out.push_str(&format!(
            "    LAYOUT_CANONICAL = {:?}\n",
            canonical::canonical_form(m)
        ));
        if let Some(ref topic) = m.topic {
            out.push_str(&format!("    TOPIC = {topic:?}\n"));
        }
        out.push('\n');

        if let Ok(l) = layout::compute(m, env) {
            out.push_str(&format!(
                "# The size Rust and C++ agree on. Checked at import rather than\n\
                 # trusted: a mismatch here means a read against shared memory would\n\
                 # be the wrong length, and failing now names the type.\n\
                 assert ctypes.sizeof({}) == {}, (\n\
                 \x20   f\"{} is {{ctypes.sizeof({})}} bytes in Python but {} in Rust — \"\n\
                 \x20   \"regenerate with `horus msg gen`\"\n\
                 )\n\n",
                m.name, l.size, m.name, m.name, l.size
            ));
        }
    }

    out.push_str("__all__ = [\n");
    for m in &pkg.messages {
        out.push_str(&format!("    {:?},\n", m.name));
    }
    out.push_str("]\n");
    out
}
