//! The generated Rust crate.
//!
//! A crate rather than a loose file: `.horus/Cargo.toml` declares its own
//! `[workspace]` and emits only `[[bin]]` targets, so there is no library for a
//! loose module to be included into, and the C++ side needs to depend on the
//! same types.

use super::{canonical, layout, Package, Type};

/// `Cargo.toml` for the generated crate.
///
/// Deliberately *without* a `[workspace]` table, unlike the project crate.
///
/// The crate lives at `.horus/generated/msgs`, inside the directory whose
/// `Cargo.toml` is itself a workspace root, and cargo refuses two roots in one
/// tree:
///
/// ```text
/// error: multiple workspace roots found in the same workspace:
///   .../.horus
///   .../.horus/generated/msgs
/// ```
///
/// Being a member instead is also the better answer: the project's `[patch]`
/// tables then apply here too, which they would not if this were its own root.
pub fn cargo_toml(pkg: &Package, horus_src: &std::path::Path, version: &str) -> String {
    let h = horus_src.display();
    format!(
        "# Generated by `horus msg gen` from msgs/*.hmsg — do not edit manually.\n\
         # Edits are lost the next time messages are generated.\n\
         [package]\n\
         name = \"{name}_msgs\"\n\
         version = \"{version}\"\n\
         edition = \"2021\"\n\
         \n\
         [lib]\n\
         path = \"src/lib.rs\"\n\
         \n\
         [dependencies]\n\
         horus_core = {{ path = \"{h}/horus_core\" }}\n\
         serde = {{ version = \"1\", features = [\"derive\"] }}\n",
        name = pkg.name.replace('-', "_"),
    )
}

/// `src/lib.rs` for the generated crate.
pub fn lib_rs(pkg: &Package, env: &layout::Env) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "//! Message types for `{}`.\n\
         //!\n\
         //! Generated by `horus msg gen` from `msgs/*.hmsg`. DO NOT EDIT — this\n\
         //! file is rewritten whenever the definitions change. Edit the `.hmsg`\n\
         //! files instead.\n\
         \n\
         #![allow(clippy::derive_partial_eq_without_eq)]\n\n",
        pkg.name
    ));

    for m in &pkg.messages {
        for line in &m.doc {
            out.push_str(&format!("/// {line}\n"));
        }
        if !m.doc.is_empty() {
            out.push_str("///\n");
        }
        out.push_str(&format!(
            "/// Generated from `{}:{}`.\n",
            m.src
                .file_name()
                .map(|s| s.to_string_lossy().to_string())
                .unwrap_or_default(),
            m.line
        ));

        out.push_str("#[repr(C)]\n");
        out.push_str(
            "#[derive(Debug, Clone, Copy, PartialEq, serde::Serialize, serde::Deserialize)]\n",
        );
        out.push_str(&format!("pub struct {} {{\n", m.name));
        for f in &m.fields {
            for line in &f.doc {
                out.push_str(&format!("    /// {line}\n"));
            }
            out.push_str(&format!(
                "    pub {}: {},\n",
                f.name,
                canonical::render_rust(&f.ty)
            ));
        }
        out.push_str("}\n\n");

        // `Default` by hand rather than derived: arrays longer than 32 do not
        // implement `Default`, and a message with a `[f32; 64]` history buffer
        // is an ordinary thing to write.
        out.push_str(&format!("impl Default for {} {{\n", m.name));
        out.push_str("    fn default() -> Self {\n");
        out.push_str("        // Every field is POD, so all-zeroes is a valid value.\n");
        out.push_str("        unsafe { core::mem::zeroed() }\n");
        out.push_str("    }\n}\n\n");

        // SAFETY, stated once and truthfully: the parser accepts only
        // primitives, fixed arrays of them, and other generated messages, so
        // there is no padding-uninitialised-bytes hazard beyond what
        // `#[repr(C)]` already defines, and no pointer, reference or
        // heap-owning field can appear.
        out.push_str(&format!(
            "// SAFETY: `{}` is `#[repr(C)]` and every field is a primitive, a\n\
             // fixed-size array of primitives, or another generated message.\n\
             // `horus msg gen` rejects anything else — a String, a Vec, a\n\
             // reference or a generic — because the shared-memory transport\n\
             // reads and writes messages with a raw `ptr::read`/`ptr::write`.\n",
            m.name
        ));
        out.push_str(&format!(
            "unsafe impl horus_core::bytemuck::Zeroable for {} {{}}\n",
            m.name
        ));
        out.push_str(&format!(
            "unsafe impl horus_core::bytemuck::Pod for {} {{}}\n",
            m.name
        ));
        out.push_str(&format!(
            "unsafe impl horus_core::communication::PodMessage for {} {{}}\n\n",
            m.name
        ));

        // The layout identity.
        let canonical_str = canonical::canonical_form(m);
        out.push_str(&format!("impl {} {{\n", m.name));
        out.push_str(
            "    /// The exact string this type's layout hash is computed over.\n\
             ///\n\
             /// Embedded as a literal rather than rebuilt with `stringify!`,\n\
             /// which reproduces source spacing — `[u8;32]` and `[u8; 32]`\n\
             /// hash differently. The text that was hashed and the text that\n\
             /// was emitted are the same bytes.\n",
        );
        out.push_str(&format!(
            "    pub const LAYOUT_CANONICAL: &'static str = \"{canonical_str}\";\n\n"
        ));
        out.push_str(&format!(
            "    /// FNV-1a of [`Self::LAYOUT_CANONICAL`] — the number\n\
             /// `horus msg hash {}` prints.\n",
            m.name
        ));
        out.push_str(
            "    pub const LAYOUT_HASH: u32 =\n        \
             horus_core::communication::topic::const_fnv1a(Self::LAYOUT_CANONICAL.as_bytes());\n",
        );
        if let Some(ref topic) = m.topic {
            out.push_str(&format!(
                "\n    /// The topic named by `#[topic = \"...\"]`.\n    \
                 pub const TOPIC: &'static str = \"{topic}\";\n"
            ));
        }

        // The checked opener. Types declared with `message!` get one of these
        // from the macro; generated types had only `LAYOUT_HASH`, so the only
        // way to open a topic for one was `Topic::<T>::new`, which passes no
        // hash and leaves the check inert. That is the whole cross-language
        // case: the C ABI below, and every C++ and Python caller through it,
        // reaches a topic through this function.
        out.push_str(&format!(
            "\n    /// Open a topic for this message with layout checking on.\n\
             \x20   ///\n\
             \x20   /// Equivalent to `Topic::new_checked(name, Self::LAYOUT_HASH)`,\n\
             \x20   /// and the same helper `message!` generates for hand-written\n\
             \x20   /// types. Prefer it over `Topic::<{name}>::new(name)`: it costs\n\
             \x20   /// nothing at runtime and turns a silently-misread message —\n\
             \x20   /// same name, same size, reordered fields — into an error.\n\
             \x20   pub fn topic(\n\
             \x20       name: &str,\n\
             \x20   ) -> horus_core::error::HorusResult<horus_core::communication::Topic<Self>> {{\n\
             \x20       horus_core::communication::Topic::new_checked(name, Self::LAYOUT_HASH)\n\
             \x20   }}\n",
            name = m.name
        ));
        out.push_str("}\n\n");

        // A size assertion, so a change in this file that alters the layout
        // fails the build rather than the robot.
        if let Ok(l) = layout::compute(m, env) {
            out.push_str(&format!(
                "// Layout is part of the contract: a change here is a change to\n\
                 // what every other language expects.\n\
                 const _: () = assert!(core::mem::size_of::<{}>() == {});\n\
                 const _: () = assert!(core::mem::align_of::<{}>() == {});\n\n",
                m.name, l.size, m.name, l.align
            ));
        }
    }

    // A compile-time check that the hash constant agrees with what the runtime
    // would compute for the same string.
    out.push_str(
        "/// Every generated type, for tests and for registration.\n\
         pub const GENERATED_TYPES: &[(&str, u32)] = &[\n",
    );
    for m in &pkg.messages {
        out.push_str(&format!(
            "    (\"{}\", {}::LAYOUT_HASH),\n",
            m.name, m.name
        ));
    }
    out.push_str("];\n");

    out
}

/// Whether any message references a type this generator cannot size.
pub fn unresolved_refs(pkg: &Package) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let local: Vec<&str> = pkg.messages.iter().map(|m| m.name.as_str()).collect();
    for m in &pkg.messages {
        for f in &m.fields {
            collect_refs(&f.ty, &mut |short| {
                if !local.contains(&short) {
                    out.push((m.name.clone(), short.to_string()));
                }
            });
        }
    }
    out
}

fn collect_refs(t: &Type, f: &mut impl FnMut(&str)) {
    match t {
        Type::Prim(_) => {}
        Type::Array(e, _) => collect_refs(e, f),
        Type::Ref(r) => f(&r.short),
    }
}
