//! The generated C++ header.
//!
//! The struct is written to match the Rust one field for field, and then the
//! header asserts that it does — `static_assert` on `sizeof` and on every
//! `offsetof`, checked by the C++ compiler against the numbers this generator
//! computed for Rust. If the two ever disagree, the C++ build stops.
//!
//! That check is the point. `horus_cpp`'s layout contract exists because the
//! hand-maintained Rust and C++ definitions of `JointCommand` drifted to 928
//! bytes against 88 — an 840-byte overrun on every receive, with no compiler
//! anywhere in a position to notice.

use super::{canonical, layout, Package, Prim, Type};

pub fn header(pkg: &Package, env: &layout::Env) -> String {
    let ns = pkg.name.replace('-', "_");
    let guard = format!("HORUS_GENERATED_{}_MSGS_HPP", ns.to_uppercase());

    let mut out = String::new();
    out.push_str(&format!(
        "// Message types for `{}`.\n\
         //\n\
         // Generated by `horus msg gen` from `msgs/*.hmsg`. DO NOT EDIT — this\n\
         // file is rewritten whenever the definitions change. Edit the `.hmsg`\n\
         // files instead.\n\
         \n\
         #ifndef {guard}\n\
         #define {guard}\n\
         \n\
         #include <array>\n\
         #include <cstddef>\n\
         #include <cstdint>\n\
         #include <type_traits>\n\
         \n\
         namespace {ns} {{\n\
         namespace msg {{\n\n",
        pkg.name
    ));

    for m in &pkg.messages {
        if !m.doc.is_empty() {
            for line in &m.doc {
                out.push_str(&format!("/// {line}\n"));
            }
        }
        out.push_str(&format!(
            "/// Generated from `{}:{}`.\n",
            m.src
                .file_name()
                .map(|s| s.to_string_lossy().to_string())
                .unwrap_or_default(),
            m.line
        ));
        out.push_str(&format!("struct {} {{\n", m.name));
        for f in &m.fields {
            for line in &f.doc {
                out.push_str(&format!("    /// {line}\n"));
            }
            out.push_str(&format!(
                "    {} {};\n",
                canonical::render_cpp(&f.ty),
                f.name
            ));
        }

        // `bool` is one byte in Rust with values 0 and 1; in C++ its size is
        // implementation-defined, so the field is `uint8_t` and this makes it
        // pleasant to use without changing the layout.
        let bools: Vec<&str> = m
            .fields
            .iter()
            .filter(|f| matches!(f.ty, Type::Prim(Prim::Bool)))
            .map(|f| f.name.as_str())
            .collect();
        if !bools.is_empty() {
            out.push('\n');
            out.push_str(
                "    // Rust's `bool` is exactly one byte holding 0 or 1; C++'s has an\n\
                 // implementation-defined size, so the fields above are `uint8_t` and\n\
                 // these are the accessors.\n",
            );
            for b in bools {
                out.push_str(&format!(
                    "    bool {b}_is_set() const {{ return {b} != 0; }}\n"
                ));
                out.push_str(&format!(
                    "    void set_{b}(bool v) {{ {b} = v ? 1 : 0; }}\n"
                ));
            }
        }

        out.push_str("};\n\n");

        // The contract.
        if let Ok(l) = layout::compute(m, env) {
            out.push_str(&format!(
                "// This is the layout the Rust definition has. If the C++ compiler\n\
                 // disagrees with any line below, the two languages have different\n\
                 // ideas about this message and the build stops here rather than\n\
                 // corrupting memory at runtime.\n\
                 static_assert(sizeof({}) == {}, \"{} size differs from Rust\");\n\
                 static_assert(alignof({}) == {}, \"{} alignment differs from Rust\");\n",
                m.name, l.size, m.name, m.name, l.align, m.name
            ));
            for (f, (offset, _, _)) in m.fields.iter().zip(&l.fields) {
                out.push_str(&format!(
                    "static_assert(offsetof({}, {}) == {}, \"{}.{} is at a different offset in Rust\");\n",
                    m.name, f.name, offset, m.name, f.name
                ));
            }
            out.push_str(&format!(
                "static_assert(std::is_standard_layout<{}>::value, \"{} must be standard layout to cross the ABI\");\n",
                m.name, m.name
            ));
        }

        out.push_str(&format!(
            "\n/// FNV-1a of the canonical layout string — the number `horus msg hash {}`\n\
             /// prints, and the value the Rust side carries as `LAYOUT_HASH`.\n\
             constexpr uint32_t {}_LAYOUT_HASH = {}u;\n",
            m.name,
            m.name.to_uppercase(),
            canonical::layout_hash(m)
        ));
        if let Some(ref topic) = m.topic {
            out.push_str(&format!(
                "/// The topic named by `#[topic = \"...\"]`.\n\
                 constexpr const char* {}_TOPIC = \"{}\";\n",
                m.name.to_uppercase(),
                topic
            ));
        }
        out.push('\n');
    }

    out.push_str(&format!(
        "}}  // namespace msg\n}}  // namespace {ns}\n\n#endif  // {guard}\n"
    ));
    out
}

/// `<type_traits>` is needed for the standard-layout assertion; included
/// separately so the header list stays sorted and minimal.
pub fn needs_type_traits(pkg: &Package) -> bool {
    !pkg.messages.is_empty()
}
