//! Shell integration for transparent native tool proxying.
//!
//! Generates `~/.horus/env.sh` (bash/zsh) and `~/.horus/env.fish` (fish) that
//! define shell functions shadowing `cargo`, `pip`, `pip3`, `cmake`, `conan`
//! and `vcpkg`. Inside a horus project the functions delegate to `horus
//! cargo/pip/cmake/...`; outside they pass through to the real tool.
//!
//! Shadowing six ecosystem-standard commands out of a shell rc file is a large
//! intervention on someone's machine, so `--init` describes every file it will
//! touch and every line it will add *before* touching anything, and asks. The
//! proxies themselves say so again at the moment they apply — see
//! [`crate::commands::proxy::announce_proxy`].

use anyhow::{bail, Context, Result};
use colored::*;
use std::fs;
use std::io::{IsTerminal, Write};
use std::path::{Path, PathBuf};

/// Content for `~/.horus/env.sh` (bash/zsh).
const ENV_SH: &str = r#"# Horus shell integration — transparent native tool proxying
# Source: https://horusrobotics.dev | Generated by `horus env --init`
# Remove with `horus env --uninstall`.

# Cargo proxy — inside horus projects, delegates to horus cargo
cargo() {
  if [ -x "$(command -v horus)" ] && command horus _is-project 2>/dev/null; then
    command horus cargo "$@"
  else
    command cargo "$@"
  fi
}

# Pip proxy
pip() {
  if [ -x "$(command -v horus)" ] && command horus _is-project 2>/dev/null; then
    command horus pip "$@"
  else
    command pip "$@"
  fi
}

pip3() {
  if [ -x "$(command -v horus)" ] && command horus _is-project 2>/dev/null; then
    command horus pip "$@"
  else
    command pip3 "$@"
  fi
}

# CMake proxy
cmake() {
  if [ -x "$(command -v horus)" ] && command horus _is-project 2>/dev/null; then
    command horus cmake "$@"
  else
    command cmake "$@"
  fi
}

# Conan proxy
conan() {
  if [ -x "$(command -v horus)" ] && command horus _is-project 2>/dev/null; then
    command horus conan "$@"
  else
    command conan "$@"
  fi
}

# vcpkg proxy
vcpkg() {
  if [ -x "$(command -v horus)" ] && command horus _is-project 2>/dev/null; then
    command horus vcpkg "$@"
  else
    command vcpkg "$@"
  fi
}
"#;

/// Content for `~/.horus/env.fish` (fish shell).
const ENV_FISH: &str = r#"# Horus shell integration — transparent native tool proxying
# Source: https://horusrobotics.dev | Generated by `horus env --init`
# Remove with `horus env --uninstall`.

function cargo
  if command -q horus; and command horus _is-project 2>/dev/null
    command horus cargo $argv
  else
    command cargo $argv
  end
end

function pip
  if command -q horus; and command horus _is-project 2>/dev/null
    command horus pip $argv
  else
    command pip $argv
  end
end

function pip3
  if command -q horus; and command horus _is-project 2>/dev/null
    command horus pip $argv
  else
    command pip3 $argv
  end
end

function cmake
  if command -q horus; and command horus _is-project 2>/dev/null
    command horus cmake $argv
  else
    command cmake $argv
  end
end

function conan
  if command -q horus; and command horus _is-project 2>/dev/null
    command horus conan $argv
  else
    command conan $argv
  end
end

function vcpkg
  if command -q horus; and command horus _is-project 2>/dev/null
    command horus vcpkg $argv
  else
    command vcpkg $argv
  end
end
"#;

/// The comment line written above the `source` line, and the one `--uninstall`
/// looks for when stripping it back out.
const RC_MARKER: &str = "# Horus shell integration";

/// The single line appended to `.bashrc` and `.zshrc`.
const RC_SOURCE_LINE: &str = "[ -f \"$HOME/.horus/env.sh\" ] && source \"$HOME/.horus/env.sh\"";

/// Content of fish's `conf.d` snippet.
const FISH_CONF: &str =
    "# Horus shell integration\ntest -f \"$HOME/.horus/env.fish\"; and source \"$HOME/.horus/env.fish\"\n";

/// The commands the generated shell functions shadow, in the order `ENV_SH`
/// defines them. Named in the preview so nobody has to read the file to find
/// out that their `cargo` is about to change.
const SHADOWED_TOOLS: &[&str] = &["cargo", "pip", "pip3", "cmake", "conan", "vcpkg"];

/// The rc files `--init` appends its `source` line to, if they exist.
const RC_FILES: &[&str] = &[".bashrc", ".zshrc"];

/// Get the horus config directory (`~/.horus`).
fn horus_home() -> Result<PathBuf> {
    let home = dirs::home_dir().context("Could not determine home directory")?;
    Ok(home.join(".horus"))
}

/// What `--init` would do to one file.
///
/// `--init` used to write every file and edit `.bashrc`/`.zshrc` before it
/// printed a word, so its whole output was past tense: by the time you read
/// that your shell now shadows `cargo`, it already did, and the word
/// `--uninstall` never appeared. Deciding the whole plan up front lets the same
/// data drive the preview, the prompt and the writes, so the preview cannot
/// drift from what actually lands.
enum EnvChange {
    /// Write one of the generated integration files (overwrites in place).
    Integration {
        path: PathBuf,
        content: &'static str,
        /// Which shells the file is for, for the preview.
        shells: &'static str,
    },
    /// Append [`RC_MARKER`] + [`RC_SOURCE_LINE`] to an rc file that lacks them.
    AppendRc { path: PathBuf },
    /// Create fish's `conf.d` snippet.
    FishConf { path: PathBuf },
}

impl EnvChange {
    fn path(&self) -> &Path {
        match self {
            EnvChange::Integration { path, .. }
            | EnvChange::AppendRc { path }
            | EnvChange::FishConf { path } => path,
        }
    }

    /// True for the changes that touch a file the *user* owns, as opposed to
    /// the two files under `~/.horus` that horus owns outright.
    fn edits_user_shell_config(&self) -> bool {
        !matches!(self, EnvChange::Integration { .. })
    }
}

/// Work out every file `--init` would touch under `home`, without touching any.
fn plan_env_init(home: &Path) -> Vec<EnvChange> {
    let horus_dir = home.join(".horus");
    let mut plan = vec![
        EnvChange::Integration {
            path: horus_dir.join("env.sh"),
            content: ENV_SH,
            shells: "bash and zsh",
        },
        EnvChange::Integration {
            path: horus_dir.join("env.fish"),
            content: ENV_FISH,
            shells: "fish",
        },
    ];

    // Only rc files that already exist are edited — creating a .zshrc for
    // someone who does not use zsh would be a surprise of its own.
    for rc_name in RC_FILES {
        let rc_path = home.join(rc_name);
        if rc_path.exists() && !rc_sources_horus(&rc_path) {
            plan.push(EnvChange::AppendRc { path: rc_path });
        }
    }

    // Same for fish: only if the user has a fish config directory.
    let fish_conf = home.join(".config/fish/conf.d/horus.fish");
    if fish_conf
        .parent()
        .is_some_and(|dir| dir.exists() && !fish_conf.exists())
    {
        plan.push(EnvChange::FishConf { path: fish_conf });
    }

    plan
}

/// Whether an rc file already sources `~/.horus/env.sh`.
fn rc_sources_horus(rc_path: &Path) -> bool {
    fs::read_to_string(rc_path)
        .unwrap_or_default()
        .contains(".horus/env.sh")
}

/// Render the plan as the exact paths and the exact lines that will be added.
///
/// Returned as a string rather than printed so the wording is testable — the
/// finding this addresses was precisely that the output never said what it was
/// about to do, or how to reverse it.
fn render_env_init_preview(plan: &[EnvChange]) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "{} will change {} {} on this machine:\n\n",
        "horus env --init".bold(),
        plan.len(),
        if plan.len() == 1 { "file" } else { "files" }
    ));

    for change in plan {
        let path = change.path().display();
        match change {
            EnvChange::Integration { shells, .. } => {
                out.push_str(&format!("  {}  {path}\n", "write ".cyan()));
                out.push_str(&format!("            shell functions for {shells}\n"));
            }
            EnvChange::AppendRc { .. } => {
                out.push_str(&format!("  {}  {path}\n", "append".yellow()));
                out.push_str(&format!("            + {RC_MARKER}\n"));
                out.push_str(&format!("            + {RC_SOURCE_LINE}\n"));
            }
            EnvChange::FishConf { .. } => {
                out.push_str(&format!("  {}  {path}\n", "create".yellow()));
                for line in FISH_CONF.lines() {
                    out.push_str(&format!("            + {line}\n"));
                }
            }
        }
    }

    out.push_str(&format!(
        "\nThose files define shell functions named {}.\n",
        SHADOWED_TOOLS.join(", ")
    ));
    out.push_str(
        "Inside a horus project (any directory with a horus.toml at or above it)\n\
         they run `horus cargo`, `horus pip`, ... instead of the real tool. Anywhere\n\
         else they call the real tool unchanged. After this, `cargo build` in a horus\n\
         project is not plain cargo.\n\n",
    );
    out.push_str(&format!(
        "  {}              print the exact file contents without installing\n",
        "horus env".cyan()
    ));
    out.push_str(&format!(
        "  {}  undo all of the above\n",
        "horus env --uninstall".cyan()
    ));

    out
}

/// Ask before editing the user's shell configuration.
///
/// Follows the same contract as `setup_rt::confirm` and `new::can_prompt`:
/// `HORUS_ASSUME_YES=1` accepts without asking. The difference is the
/// non-interactive default — this one accepts, because `--init` is only ever
/// reached when someone asked for it by name, and install.sh pipes the script
/// through stdin, so reading a line there would eat the rest of the installer.
fn confirm_env_init() -> Result<bool> {
    if std::env::var("HORUS_ASSUME_YES")
        .map(|v| v == "1" || v.eq_ignore_ascii_case("true") || v.eq_ignore_ascii_case("yes"))
        .unwrap_or(false)
    {
        return Ok(true);
    }

    if !std::io::stdin().is_terminal() {
        println!(
            "\n{} Not a terminal — proceeding. Undo with `horus env --uninstall`.",
            "?".cyan()
        );
        return Ok(true);
    }

    print!("\n{} Install shell integration? [Y/n]: ", "?".cyan());
    std::io::stdout().flush().ok();
    let mut input = String::new();
    std::io::stdin().read_line(&mut input)?;
    Ok(matches!(
        input.trim().to_lowercase().as_str(),
        "" | "y" | "yes"
    ))
}

/// Carry out a plan produced by [`plan_env_init`].
fn apply_env_init(plan: &[EnvChange]) -> Result<()> {
    for change in plan {
        match change {
            EnvChange::Integration { path, content, .. } => {
                if let Some(parent) = path.parent() {
                    fs::create_dir_all(parent)?;
                }
                fs::write(path, content)
                    .with_context(|| format!("Failed to write {}", path.display()))?;
                println!("{} Wrote {}", "*".green(), path.display());
            }
            EnvChange::AppendRc { path } => {
                let mut content = fs::read_to_string(path).unwrap_or_default();
                if !content.is_empty() && !content.ends_with('\n') {
                    content.push('\n');
                }
                content.push('\n');
                content.push_str(RC_MARKER);
                content.push('\n');
                content.push_str(RC_SOURCE_LINE);
                content.push('\n');
                fs::write(path, content)
                    .with_context(|| format!("Failed to update {}", path.display()))?;
                println!("{} Added source line to {}", "*".green(), path.display());
            }
            EnvChange::FishConf { path } => {
                fs::write(path, FISH_CONF)
                    .with_context(|| format!("Failed to write {}", path.display()))?;
                println!("{} Created {}", "*".green(), path.display());
            }
        }
    }
    Ok(())
}

/// Generate and write shell integration files to `~/.horus/`.
pub fn run_env_init() -> Result<()> {
    let home = dirs::home_dir().context("Could not determine home directory")?;
    run_env_init_in(&home, confirm_env_init)
}

/// `run_env_init` against an explicit home directory and an explicit source of
/// the yes/no answer, so the whole flow can be exercised against a scratch
/// directory without a terminal attached.
fn run_env_init_in(home: &Path, confirm: impl FnOnce() -> Result<bool>) -> Result<()> {
    let plan = plan_env_init(home);
    let sh_path = home.join(".horus/env.sh");

    // A re-run over an installation that is already wired up (install.sh runs
    // `--init` on every upgrade) only refreshes the two files horus owns. That
    // is not a new intervention, so it does not ask again.
    let refresh_only = sh_path.exists()
        && !plan.iter().any(EnvChange::edits_user_shell_config)
        && RC_FILES.iter().any(|rc| rc_sources_horus(&home.join(rc)));

    if refresh_only {
        apply_env_init(&plan)?;
        println!();
        println!("Shell integration was already installed; files refreshed.");
        println!(
            "Shadows {} inside horus projects. Undo with: {}",
            SHADOWED_TOOLS.join(", "),
            "horus env --uninstall".cyan()
        );
        return Ok(());
    }

    print!("{}", render_env_init_preview(&plan));

    if !confirm()? {
        bail!("Declined — no files were changed. Run `horus env --init` any time to install.");
    }
    println!();

    apply_env_init(&plan)?;

    println!();
    println!("Shell integration installed. Restart your shell or run:");
    println!("  source {}", sh_path.display());
    println!("Undo at any time with: {}", "horus env --uninstall".cyan());

    Ok(())
}

/// Print shell integration to stdout (for manual eval).
pub fn run_env_print() -> Result<()> {
    // Detect shell from $SHELL or $FISH_VERSION
    if std::env::var("FISH_VERSION").is_ok() {
        print!("{}", ENV_FISH);
    } else {
        print!("{}", ENV_SH);
    }
    Ok(())
}

/// Remove shell integration from RC files and delete env.sh/env.fish.
pub fn run_env_uninstall() -> Result<()> {
    let horus_dir = horus_home()?;

    let sh_path = horus_dir.join("env.sh");
    let fish_path = horus_dir.join("env.fish");

    if sh_path.exists() {
        fs::remove_file(&sh_path)?;
        println!("{} Removed {}", "*".green(), sh_path.display());
    }
    if fish_path.exists() {
        fs::remove_file(&fish_path)?;
        println!("{} Removed {}", "*".green(), fish_path.display());
    }

    // Remove source lines from shell RC
    remove_source_lines()?;

    println!("{} Shell integration uninstalled.", "*".green());
    println!("  Open a new shell — the current one still has the functions defined.");
    Ok(())
}

/// Remove horus source lines from shell RC files.
fn remove_source_lines() -> Result<()> {
    let home = dirs::home_dir().context("Could not determine home directory")?;

    for rc_name in RC_FILES {
        let rc_path = home.join(rc_name);
        if rc_path.exists() {
            let content = fs::read_to_string(&rc_path).unwrap_or_default();
            if content.contains(".horus/env.sh") {
                let filtered: Vec<&str> = content
                    .lines()
                    .filter(|line| !line.contains(".horus/env.sh") && !line.trim().eq(RC_MARKER))
                    .collect();
                fs::write(&rc_path, filtered.join("\n") + "\n")?;
                println!("{} Removed source line from {}", "*".green(), rc_name);
            }
        }
    }

    let fish_conf = home.join(".config/fish/conf.d/horus.fish");
    if fish_conf.exists() {
        fs::remove_file(&fish_conf)?;
        println!("{} Removed {}", "*".green(), fish_conf.display());
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A scratch home with the shell config files a plan is supposed to notice.
    fn fake_home(with_bashrc: bool, with_zshrc: bool, with_fish: bool) -> tempfile::TempDir {
        let home = tempfile::tempdir().unwrap();
        if with_bashrc {
            fs::write(home.path().join(".bashrc"), "export PATH=$PATH\n").unwrap();
        }
        if with_zshrc {
            fs::write(home.path().join(".zshrc"), "autoload -Uz compinit\n").unwrap();
        }
        if with_fish {
            fs::create_dir_all(home.path().join(".config/fish/conf.d")).unwrap();
        }
        home
    }

    #[test]
    fn plan_lists_every_file_init_would_touch() {
        let home = fake_home(true, true, true);
        let plan = plan_env_init(home.path());

        let paths: Vec<_> = plan.iter().map(|c| c.path().to_path_buf()).collect();
        assert_eq!(
            paths,
            vec![
                home.path().join(".horus/env.sh"),
                home.path().join(".horus/env.fish"),
                home.path().join(".bashrc"),
                home.path().join(".zshrc"),
                home.path().join(".config/fish/conf.d/horus.fish"),
            ]
        );
    }

    #[test]
    fn plan_skips_shell_config_the_user_does_not_have() {
        let home = fake_home(true, false, false);
        let plan = plan_env_init(home.path());

        let paths: Vec<_> = plan.iter().map(|c| c.path().to_path_buf()).collect();
        assert!(paths.contains(&home.path().join(".bashrc")));
        assert!(!paths.contains(&home.path().join(".zshrc")));
        assert!(!paths.contains(&home.path().join(".config/fish/conf.d/horus.fish")));
    }

    /// The finding: the output never said what was about to change, which files
    /// it edits, or that `--uninstall` exists.
    #[test]
    fn preview_names_the_files_the_lines_and_the_undo() {
        let home = fake_home(true, true, false);
        let preview = render_env_init_preview(&plan_env_init(home.path()));

        // Every path it will touch, spelled out.
        assert!(preview.contains(&home.path().join(".bashrc").display().to_string()));
        assert!(preview.contains(&home.path().join(".zshrc").display().to_string()));
        assert!(preview.contains(&home.path().join(".horus/env.sh").display().to_string()));
        // The exact line that gets appended.
        assert!(preview.contains(RC_SOURCE_LINE));
        // What it shadows, and how to get out.
        for tool in SHADOWED_TOOLS {
            assert!(preview.contains(tool), "preview never mentions {tool}");
        }
        assert!(preview.contains("horus env --uninstall"));
    }

    #[test]
    fn apply_writes_exactly_what_the_plan_promised() {
        let home = fake_home(true, false, true);
        let plan = plan_env_init(home.path());
        apply_env_init(&plan).unwrap();

        assert_eq!(
            fs::read_to_string(home.path().join(".horus/env.sh")).unwrap(),
            ENV_SH
        );
        assert_eq!(
            fs::read_to_string(home.path().join(".horus/env.fish")).unwrap(),
            ENV_FISH
        );
        let bashrc = fs::read_to_string(home.path().join(".bashrc")).unwrap();
        assert!(bashrc.contains(RC_SOURCE_LINE));
        assert!(bashrc.starts_with("export PATH=$PATH\n"));
        assert!(home.path().join(".config/fish/conf.d/horus.fish").exists());
    }

    #[test]
    fn second_run_does_not_append_the_source_line_twice() {
        let home = fake_home(true, true, true);
        apply_env_init(&plan_env_init(home.path())).unwrap();

        let second = plan_env_init(home.path());
        assert!(
            !second.iter().any(EnvChange::edits_user_shell_config),
            "a re-run would edit the user's shell config again"
        );

        apply_env_init(&second).unwrap();
        let bashrc = fs::read_to_string(home.path().join(".bashrc")).unwrap();
        assert_eq!(bashrc.matches(RC_SOURCE_LINE).count(), 1);
    }

    #[test]
    fn accepting_installs_everything_in_the_plan() {
        let home = fake_home(true, false, false);
        run_env_init_in(home.path(), || Ok(true)).unwrap();
        assert!(home.path().join(".horus/env.sh").exists());
        assert!(fs::read_to_string(home.path().join(".bashrc"))
            .unwrap()
            .contains(RC_SOURCE_LINE));
    }

    /// The point of the prompt: saying no has to leave the machine alone.
    #[test]
    fn declining_writes_nothing_at_all() {
        let home = fake_home(true, false, false);
        let err = run_env_init_in(home.path(), || Ok(false)).unwrap_err();

        assert!(err.to_string().contains("no files were changed"));
        assert!(!home.path().join(".horus/env.sh").exists());
        assert_eq!(
            fs::read_to_string(home.path().join(".bashrc")).unwrap(),
            "export PATH=$PATH\n"
        );
    }

    /// install.sh runs `--init` on every upgrade. Once the rc edits are in
    /// place, refreshing the two files horus owns is not a new intervention, so
    /// it must not ask again — a prompt there would block the installer.
    #[test]
    fn refresh_of_an_installed_setup_does_not_ask_again() {
        let home = fake_home(true, false, false);
        run_env_init_in(home.path(), || Ok(true)).unwrap();

        // Simulate an upgrade shipping different file content.
        fs::write(home.path().join(".horus/env.sh"), "# stale\n").unwrap();
        run_env_init_in(home.path(), || {
            panic!("a refresh must not prompt");
        })
        .unwrap();
        assert_eq!(
            fs::read_to_string(home.path().join(".horus/env.sh")).unwrap(),
            ENV_SH
        );
    }
}
