//! Shell integration for transparent native tool proxying.
//!
//! Generates `~/.horus/env.sh` (bash/zsh) and `~/.horus/env.fish` (fish) that
//! define shell functions shadowing `cargo`, `pip`, and `cmake`. Inside a horus
//! project the functions delegate to `horus cargo/pip/cmake`; outside they pass
//! through to the real tool.
//!
//! The horus installer sources these files automatically.

use anyhow::{Context, Result};
use colored::*;
use std::fs;
use std::path::PathBuf;

/// Content for `~/.horus/env.sh` (bash/zsh).
const ENV_SH: &str = r#"# Horus shell integration — transparent native tool proxying
# Source: https://horusrobotics.dev | Generated by `horus env --init`
# This file is auto-sourced by the horus installer.

# Cargo proxy — inside horus projects, delegates to horus cargo
cargo() {
  if [ -x "$(command -v horus)" ] && command horus _is-project 2>/dev/null; then
    command horus cargo "$@"
  else
    command cargo "$@"
  fi
}

# Pip proxy
pip() {
  if [ -x "$(command -v horus)" ] && command horus _is-project 2>/dev/null; then
    command horus pip "$@"
  else
    command pip "$@"
  fi
}

pip3() {
  if [ -x "$(command -v horus)" ] && command horus _is-project 2>/dev/null; then
    command horus pip "$@"
  else
    command pip3 "$@"
  fi
}

# CMake proxy
cmake() {
  if [ -x "$(command -v horus)" ] && command horus _is-project 2>/dev/null; then
    command horus cmake "$@"
  else
    command cmake "$@"
  fi
}

# Conan proxy
conan() {
  if [ -x "$(command -v horus)" ] && command horus _is-project 2>/dev/null; then
    command horus conan "$@"
  else
    command conan "$@"
  fi
}

# vcpkg proxy
vcpkg() {
  if [ -x "$(command -v horus)" ] && command horus _is-project 2>/dev/null; then
    command horus vcpkg "$@"
  else
    command vcpkg "$@"
  fi
}
"#;

/// Content for `~/.horus/env.fish` (fish shell).
const ENV_FISH: &str = r#"# Horus shell integration — transparent native tool proxying
# Source: https://horusrobotics.dev | Generated by `horus env --init`

function cargo
  if command -q horus; and command horus _is-project 2>/dev/null
    command horus cargo $argv
  else
    command cargo $argv
  end
end

function pip
  if command -q horus; and command horus _is-project 2>/dev/null
    command horus pip $argv
  else
    command pip $argv
  end
end

function pip3
  if command -q horus; and command horus _is-project 2>/dev/null
    command horus pip $argv
  else
    command pip3 $argv
  end
end

function cmake
  if command -q horus; and command horus _is-project 2>/dev/null
    command horus cmake $argv
  else
    command cmake $argv
  end
end

function conan
  if command -q horus; and command horus _is-project 2>/dev/null
    command horus conan $argv
  else
    command conan $argv
  end
end

function vcpkg
  if command -q horus; and command horus _is-project 2>/dev/null
    command horus vcpkg $argv
  else
    command vcpkg $argv
  end
end
"#;

/// Get the horus config directory (`~/.horus`).
fn horus_home() -> Result<PathBuf> {
    let home = dirs::home_dir().context("Could not determine home directory")?;
    Ok(home.join(".horus"))
}

/// Generate and write shell integration files to `~/.horus/`.
pub fn run_env_init() -> Result<()> {
    let horus_dir = horus_home()?;
    fs::create_dir_all(&horus_dir)?;

    // Write env.sh
    let sh_path = horus_dir.join("env.sh");
    fs::write(&sh_path, ENV_SH).context("Failed to write env.sh")?;
    println!("{} Wrote {}", "*".green(), sh_path.display());

    // Write env.fish
    let fish_path = horus_dir.join("env.fish");
    fs::write(&fish_path, ENV_FISH).context("Failed to write env.fish")?;
    println!("{} Wrote {}", "*".green(), fish_path.display());

    // Try to add source line to shell RC files
    add_source_line_if_missing()?;

    println!();
    println!(
        "Shell integration installed. Restart your shell or run:"
    );
    println!("  source {}", sh_path.display());

    Ok(())
}

/// Print shell integration to stdout (for manual eval).
pub fn run_env_print() -> Result<()> {
    // Detect shell from $SHELL or $FISH_VERSION
    if std::env::var("FISH_VERSION").is_ok() {
        print!("{}", ENV_FISH);
    } else {
        print!("{}", ENV_SH);
    }
    Ok(())
}

/// Remove shell integration from RC files and delete env.sh/env.fish.
pub fn run_env_uninstall() -> Result<()> {
    let horus_dir = horus_home()?;

    let sh_path = horus_dir.join("env.sh");
    let fish_path = horus_dir.join("env.fish");

    if sh_path.exists() {
        fs::remove_file(&sh_path)?;
        println!("{} Removed {}", "*".green(), sh_path.display());
    }
    if fish_path.exists() {
        fs::remove_file(&fish_path)?;
        println!("{} Removed {}", "*".green(), fish_path.display());
    }

    // Remove source lines from shell RC
    remove_source_lines()?;

    println!("{} Shell integration uninstalled.", "*".green());
    Ok(())
}

/// Add `source ~/.horus/env.sh` to `.bashrc` and `.zshrc` if not already present.
fn add_source_line_if_missing() -> Result<()> {
    let home = dirs::home_dir().context("Could not determine home directory")?;
    let source_line = "[ -f \"$HOME/.horus/env.sh\" ] && source \"$HOME/.horus/env.sh\"";

    for rc_name in &[".bashrc", ".zshrc"] {
        let rc_path = home.join(rc_name);
        if rc_path.exists() {
            let content = fs::read_to_string(&rc_path).unwrap_or_default();
            if !content.contains(".horus/env.sh") {
                let mut new_content = content;
                if !new_content.ends_with('\n') {
                    new_content.push('\n');
                }
                new_content.push_str("\n# Horus shell integration\n");
                new_content.push_str(source_line);
                new_content.push('\n');
                fs::write(&rc_path, new_content)?;
                println!("{} Added source line to {}", "*".green(), rc_name);
            }
        }
    }

    // Fish shell
    let fish_dir = home.join(".config/fish/conf.d");
    if fish_dir.exists() {
        let fish_conf = fish_dir.join("horus.fish");
        if !fish_conf.exists() {
            fs::write(
                &fish_conf,
                "# Horus shell integration\ntest -f \"$HOME/.horus/env.fish\"; and source \"$HOME/.horus/env.fish\"\n",
            )?;
            println!("{} Created {}", "*".green(), fish_conf.display());
        }
    }

    Ok(())
}

/// Remove horus source lines from shell RC files.
fn remove_source_lines() -> Result<()> {
    let home = dirs::home_dir().context("Could not determine home directory")?;

    for rc_name in &[".bashrc", ".zshrc"] {
        let rc_path = home.join(rc_name);
        if rc_path.exists() {
            let content = fs::read_to_string(&rc_path).unwrap_or_default();
            if content.contains(".horus/env.sh") {
                let filtered: Vec<&str> = content
                    .lines()
                    .filter(|line| {
                        !line.contains(".horus/env.sh")
                            && !line.trim().eq("# Horus shell integration")
                    })
                    .collect();
                fs::write(&rc_path, filtered.join("\n") + "\n")?;
                println!("{} Removed source line from {}", "*".green(), rc_name);
            }
        }
    }

    let fish_conf = home.join(".config/fish/conf.d/horus.fish");
    if fish_conf.exists() {
        fs::remove_file(&fish_conf)?;
        println!("{} Removed {}", "*".green(), fish_conf.display());
    }

    Ok(())
}
