// GENERATED by horus C++ bindings — do not edit manually.
// Source: horus_library/messages/control.rs, cmd_vel.rs
#pragma once

#include <cstddef>
#include <cstdint>

namespace horus { namespace msg {

/// 2D velocity command — the most common robotics message (16 bytes)
struct CmdVel {
    uint64_t timestamp_ns;
    float linear;   // m/s forward velocity
    float angular;  // rad/s turning velocity
};

/// Single motor control command
struct MotorCommand {
    float target_velocity;   // rad/s or m/s
    float target_position;   // radians or meters
    float kp;                // proportional gain
    float kd;                // derivative gain
    float max_effort;        // maximum torque/force
    uint64_t timestamp_ns;
};

/// Differential drive (two-wheel) command
struct DifferentialDriveCommand {
    float left_velocity;     // m/s
    float right_velocity;    // m/s
    uint64_t timestamp_ns;
};

/// Servo/continuous actuator command
struct ServoCommand {
    float target_position;   // radians or meters
    float target_velocity;   // rad/s or m/s
    float max_force;         // maximum force/torque
    uint64_t timestamp_ns;
};

/// PID controller tuning parameters
struct PidConfig {
    float kp;
    float ki;
    float kd;
    float integral_limit;
    float derivative_filter;
    uint64_t timestamp_ns;
};

/// Trajectory waypoint
struct TrajectoryPoint {
    double positions[3];
    double velocities[3];
    double accelerations[3];
    double effort[3];
    uint64_t time_from_start_ns;
};

/// Joint command
struct JointCommand {
    uint8_t joint_id[32];    // null-terminated
    double target[3];
    double velocity[3];
    uint64_t timestamp_ns;
};

static_assert(sizeof(CmdVel) == 16, "CmdVel size mismatch");

}} // namespace horus::msg
