// GENERATED by horus C++ bindings — do not edit manually.
// Source: horus-robotics/messages/detection.rs, landmark.rs, tracking.rs, perception.rs
#pragma once

#include <cstddef>
#include <cstdint>

namespace horus { namespace msg {

/// 2D bounding box
struct BoundingBox2D {
    float center_x;
    float center_y;
    float width;
    float height;
    float angle;     // radians
};

/// 3D bounding box
struct BoundingBox3D {
    double center[3];
    double size[3];
    double rotation[4];  // quaternion
    float confidence;
};

/// 2D object detection
struct Detection {
    BoundingBox2D bbox;
    uint32_t class_id;
    float confidence;
    uint64_t timestamp_ns;
};

/// 3D object detection with velocity
struct Detection3D {
    BoundingBox3D bbox;
    uint32_t class_id;
    float confidence;
    double velocity[3];
    uint64_t timestamp_ns;
};

/// 2D landmark
struct Landmark {
    uint32_t id;
    double x;
    double y;
    double covariance[4];  // 2x2
    uint64_t timestamp_ns;
};

/// Tracked object
struct TrackedObject {
    uint64_t track_id;
    double position[3];
    double velocity[3];
    float confidence;
    uint32_t age;
    uint64_t timestamp_ns;
};

/// Tracking header/metadata
struct TrackingHeader {
    uint64_t timestamp_ns;
    uint64_t frame_count;
    uint32_t active_tracks;
};

/// Plane detection result
struct PlaneDetection {
    double coefficients[4]; // ax+by+cz+d=0
    uint32_t inliers;
    uint64_t timestamp_ns;
};

/// Segmentation mask metadata (pixel data handled via Image/TensorPool)
struct SegmentationMask {
    uint32_t width;
    uint32_t height;
    uint32_t num_classes;
    uint32_t mask_type;
    uint64_t timestamp_ns;
    uint64_t seq;
    uint8_t frame_id[32];
};

/// 3D landmark
struct Landmark3D {
    float x;
    float y;
    float z;
    float visibility;
    uint32_t index;
} __attribute__((packed));

/// Array of landmarks with metadata
struct LandmarkArray {
    uint32_t num_landmarks;
    uint32_t dimension;
    uint32_t instance_id;
    float confidence;
    uint64_t timestamp_ns;
    float bbox_x;
    float bbox_y;
    float bbox_width;
    float bbox_height;
};

/// Point field descriptor (for point clouds)
struct PointField {
    uint8_t name[16];
    uint32_t offset;
    uint8_t datatype;   // 0=f32, 1=f64, 2=u8, 3=i32
    uint32_t count;
};

}} // namespace horus::msg
