// GENERATED by horus C++ bindings — do not edit manually.
// Source: horus_library/messages/detection.rs, landmark.rs, tracking.rs, perception.rs
#pragma once

#include <cstddef>
#include <cstdint>

namespace horus { namespace msg {

/// 2D bounding box
struct BoundingBox2D {
    float center_x;
    float center_y;
    float width;
    float height;
    float angle;     // radians
};

/// 3D bounding box
struct BoundingBox3D {
    double center[3];
    double size[3];
    double rotation[4];  // quaternion
    float confidence;
};

/// 2D object detection
struct Detection {
    BoundingBox2D bbox;
    uint32_t class_id;
    float confidence;
    uint64_t timestamp_ns;
};

/// 3D object detection with velocity
struct Detection3D {
    BoundingBox3D bbox;
    uint32_t class_id;
    float confidence;
    double velocity[3];
    uint64_t timestamp_ns;
};

/// 2D landmark
struct Landmark {
    uint32_t id;
    double x;
    double y;
    double covariance[4];  // 2x2
    uint64_t timestamp_ns;
};

/// Tracked object
struct TrackedObject {
    uint64_t track_id;
    double position[3];
    double velocity[3];
    float confidence;
    uint32_t age;
    uint64_t timestamp_ns;
};

/// Tracking header/metadata
struct TrackingHeader {
    uint64_t timestamp_ns;
    uint64_t frame_count;
    uint32_t active_tracks;
};

/// Plane detection result
struct PlaneDetection {
    double coefficients[4]; // ax+by+cz+d=0
    uint32_t inliers;
    uint64_t timestamp_ns;
};

}} // namespace horus::msg
