// GENERATED by horus C++ bindings — do not edit manually.
// Source: horus_library/messages/diagnostics.rs
#pragma once

#include <cstddef>
#include <cstdint>

namespace horus { namespace msg {

/// Node heartbeat / liveness signal
struct Heartbeat {
    uint8_t node_id[32];     // null-terminated node name
    uint64_t sequence;
    bool alive;
    float cpu_usage;         // 0.0-100.0 percent
    float memory_usage;      // megabytes
    uint64_t timestamp_ns;
};

/// Diagnostic status message
struct DiagnosticStatus {
    uint8_t level;           // 0=OK, 1=WARN, 2=ERROR, 3=CRITICAL
    uint8_t message[256];    // null-terminated
    uint16_t message_len;
    uint64_t timestamp_ns;
};

/// Emergency stop signal
struct EmergencyStop {
    bool engaged;
    bool auto_reset;
    uint8_t reason[64];      // null-terminated
    uint8_t source[64];      // null-terminated
    uint64_t timestamp_ns;
};

/// System resource usage
struct ResourceUsage {
    float cpu_percent;
    float memory_mb;
    float disk_percent;
    uint64_t timestamp_ns;
};

/// Per-node heartbeat with detailed metrics
struct NodeHeartbeat {
    uint8_t node_name[32];
    float tick_rate;         // Hz
    float cpu_usage;         // percent
    float memory_mb;
    uint64_t uptime_ms;
    uint64_t timestamp_ns;
};

/// Safety system status
struct SafetyStatus {
    bool safe;
    float confidence;        // 0.0-1.0
    uint8_t last_fault[128]; // null-terminated
    uint16_t last_fault_len;
    uint64_t timestamp_ns;
};

}} // namespace horus::msg
