// GENERATED by horus C++ bindings — do not edit manually.
// Source: horus-robotics/messages/force.rs
// Layout: identical to Rust #[repr(C)] structs for zero-copy SHM IPC.
//
// Every struct here mirrors its Rust counterpart FIELD FOR FIELD. The C ABI
// `_send`/`_recv` entry points do a raw `std::ptr::read`/`std::ptr::write` of
// the RUST struct through the pointer you pass, so any divergence in size or
// field meaning is memory corruption or silent misinterpretation.
// Verified by static_asserts in <horus/layout_contract.hpp>.
//
// Boolean-ish flags are declared `u8` on the Rust side and are mirrored here as
// `uint8_t` rather than C++ `bool`, whose size is implementation-defined.
#pragma once

#include <cstddef>
#include <cstdint>

#include "geometry.hpp"  // horus::msg::Vector3, horus::msg::Point3

namespace horus { namespace msg {

/// Force and torque measurement (wrench) — 112 bytes.
/// Rust: horus_robotics::messages::force::WrenchStamped
struct WrenchStamped {
    Vector3 force;                  ///< [fx, fy, fz] in Newtons
    Vector3 torque;                 ///< [tx, ty, tz] in Newton-meters
    Point3 point_of_application;    ///< relative to sensor frame
    uint8_t frame_id[32];
    uint64_t timestamp_ns;
};

/// Impedance control parameters — 208 bytes.
/// Rust: horus_robotics::messages::force::ImpedanceParameters
///
/// All 6-element vectors are the matrix diagonal, ordered
/// [x, y, z, rx, ry, rz].
struct ImpedanceParameters {
    double stiffness[6];    ///< [Kx, Ky, Kz, Krx, Kry, Krz]
    double damping[6];      ///< [Dx, Dy, Dz, Drx, Dry, Drz]
    double inertia[6];      ///< [Mx, My, Mz, Mrx, Mry, Mrz]
    double force_limits[6]; ///< [Fx_max, Fy_max, Fz_max, Tx_max, Ty_max, Tz_max]
    uint8_t enabled;        ///< Rust u8 flag: 0 = off, 1 = on
    uint64_t timestamp_ns;
};

/// Force control command — 224 bytes.
/// Rust: horus_robotics::messages::force::ForceCommand
struct ForceCommand {
    Vector3 target_force;           ///< desired force [fx, fy, fz]
    Vector3 target_torque;          ///< desired torque [tx, ty, tz]
    /// Per-axis control mode [fx, fy, fz, tx, ty, tz]:
    /// 1 = force control, 0 = position control.
    uint8_t force_mode[6];
    Vector3 position_setpoint;      ///< for position-controlled axes
    Vector3 orientation_setpoint;   ///< Euler angles
    Vector3 max_deviation;          ///< max allowed deviation from setpoint
    double gains[6];                ///< [Kp_fx, Kp_fy, Kp_fz, Kp_tx, Kp_ty, Kp_tz]
    double timeout_seconds;         ///< 0 = no timeout
    uint8_t frame_id[32];
    uint64_t timestamp_ns;
};

/// Contact state values for `ContactInfo::state`.
/// Rust: horus_robotics::messages::force::ContactState, #[repr(u8)].
/// Mirrored as constants rather than a C++ enum so `ContactInfo` stays a
/// plain aggregate with an exactly-known 1-byte field.
enum : uint8_t {
    CONTACT_STATE_NO_CONTACT      = 0,
    CONTACT_STATE_INITIAL_CONTACT = 1,
    CONTACT_STATE_STABLE_CONTACT  = 2,
    CONTACT_STATE_CONTACT_LOSS    = 3,
    CONTACT_STATE_SLIDING         = 4,
    CONTACT_STATE_IMPACT          = 5,
};

/// Contact detection and classification — 136 bytes.
/// Rust: horus_robotics::messages::force::ContactInfo
struct ContactInfo {
    uint8_t state;              ///< one of CONTACT_STATE_*
    double contact_force;       ///< contact force magnitude
    Vector3 contact_normal;     ///< estimated contact normal
    Point3 contact_point;       ///< estimated contact point
    double stiffness;           ///< estimated contact stiffness
    double damping;             ///< estimated contact damping
    float confidence;           ///< detection confidence, 0.0-1.0
    uint64_t contact_start_time;///< ns, time contact was first detected
    uint8_t frame_id[32];
    uint64_t timestamp_ns;
};

/// Haptic feedback command — 56 bytes.
/// Rust: horus_robotics::messages::force::HapticFeedback
struct HapticFeedback {
    float vibration_intensity;  ///< 0.0-1.0
    float vibration_frequency;  ///< Hz
    float duration_seconds;
    Vector3 force_feedback;
    uint8_t pattern_type;       ///< 0 = constant, 1 = pulse, 2 = ramp
    uint8_t enabled;            ///< Rust u8 flag: 0 = off, 1 = on
    uint64_t timestamp_ns;
};

// NOTE: horus_robotics::messages::force::TactileArray is intentionally absent.
// It is #[derive(...)]-only (repr(Rust), not #[repr(C)]) and contains a
// `Vec<f32>`, so it has no stable ABI and is not a POD message — it travels
// over the serde path, not the zero-copy path. It must never be mirrored here.

}} // namespace horus::msg
