// GENERATED by horus C++ bindings — do not edit manually.
// Source: horus_library/messages/force.rs
#pragma once

#include <cstddef>
#include <cstdint>

namespace horus { namespace msg {

/// Force/torque measurement with frame
struct WrenchStamped {
    uint8_t frame_id[32];
    double force[3];     // Newtons [x,y,z]
    double torque[3];    // Newton-meters [x,y,z]
    uint64_t timestamp_ns;
};

/// Impedance control parameters
struct ImpedanceParameters {
    double stiffness[3];
    double damping[3];
    double mass[3];
    uint64_t timestamp_ns;
};

/// Force control command
struct ForceCommand {
    uint8_t frame_id[32];
    double force[3];
    double torque[3];
    double max_force;
    uint64_t timestamp_ns;
};

/// Contact point information
struct ContactInfo {
    double position[3];
    double normal[3];
    double force;
    uint64_t timestamp_ns;
};

/// Haptic feedback command
struct HapticFeedback {
    float amplitude;     // 0.0-1.0
    float frequency;     // Hz
    uint32_t duration_ms;
    uint8_t pattern;     // 0=constant, 1=pulse, 2=ramp
    uint64_t timestamp_ns;
};

}} // namespace horus::msg
