// GENERATED by horus C++ bindings — do not edit manually.
// Source: horus_types/src/math.rs  (crate `horus_types`)
// Layout: identical to Rust #[repr(C)] structs for zero-copy SHM IPC.
//
// Every field below mirrors its Rust counterpart 1:1 in order, width and
// padding. The C ABI (`horus_publisher_*_send` / `horus_subscriber_*_recv`)
// does a raw `ptr::read` / `ptr::write` of the RUST struct through the pointer
// you pass here, so any divergence is memory corruption, not a type error.
// The authoritative offsets live in <horus/layout_contract.hpp>.
#pragma once

#include <cstddef>
#include <cstdint>

namespace horus { namespace msg {

/// 3D point — Rust `horus_types::Point3` (24 bytes)
struct Point3 {
    double x;
    double y;
    double z;
};

/// 3D vector — Rust `horus_types::Vector3` (24 bytes)
struct Vector3 {
    double x;
    double y;
    double z;
};

/// Quaternion rotation [x,y,z,w] Hamilton convention —
/// Rust `horus_types::Quaternion` (32 bytes)
struct Quaternion {
    double x;
    double y;
    double z;
    double w;
};

/// Full 6-DOF velocity — linear + angular.
/// Rust `horus_types::Twist` (56 bytes)
struct Twist {
    double linear[3];   // m/s [x, y, z]
    double angular[3];  // rad/s [roll, pitch, yaw]
    uint64_t timestamp_ns;
};

/// 2D pose — position + orientation.
/// Rust `horus_types::Pose2D` (32 bytes)
struct Pose2D {
    double x;      // meters
    double y;      // meters
    double theta;  // radians
    uint64_t timestamp_ns;
};

/// 3D transform — translation + quaternion rotation.
/// Rust `horus_types::TransformStamped` (64 bytes)
struct TransformStamped {
    double translation[3];  // meters [x, y, z]
    double rotation[4];     // quaternion [x, y, z, w]
    uint64_t timestamp_ns;
};

/// 3D pose — position + orientation.
/// Rust `horus_types::Pose3D` (64 bytes)
struct Pose3D {
    Point3 position;
    Quaternion orientation;
    uint64_t timestamp_ns;
};

/// Stamped 3D pose with frame ID.
/// Rust `horus_types::PoseStamped` (104 bytes)
struct PoseStamped {
    Pose3D pose;
    uint8_t frame_id[32];  // null-terminated, max 31 chars
    uint64_t timestamp_ns;
};

/// 3D pose with 6x6 covariance matrix.
/// Rust `horus_types::PoseWithCovariance` (392 bytes)
struct PoseWithCovariance {
    Pose3D pose;
    double covariance[36];  // 6x6 row-major: x,y,z,roll,pitch,yaw
    uint8_t frame_id[32];   // null-terminated, max 31 chars
    uint64_t timestamp_ns;
};

/// 6-DOF velocity with 6x6 covariance matrix.
/// Rust `horus_types::TwistWithCovariance` (384 bytes)
struct TwistWithCovariance {
    Twist twist;
    double covariance[36];  // 6x6 row-major: vx,vy,vz,wx,wy,wz
    uint8_t frame_id[32];   // null-terminated, max 31 chars
    uint64_t timestamp_ns;
};

/// 6-DOF acceleration — linear + angular.
/// Rust `horus_types::Accel` (56 bytes)
struct Accel {
    double linear[3];   // m/s^2 [x, y, z]
    double angular[3];  // rad/s^2 [roll, pitch, yaw]
    uint64_t timestamp_ns;
};

/// Stamped acceleration with frame ID.
/// Rust `horus_types::AccelStamped` (96 bytes)
struct AccelStamped {
    Accel accel;
    uint8_t frame_id[32];  // null-terminated, max 31 chars
    uint64_t timestamp_ns;
};

// ─── Layout Assertions ──────────────────────────────────────────────
// These verify the C++ structs match the Rust #[repr(C)] layout.
// If any assertion fails, the C++ and Rust sides have diverged.
// <horus/layout_contract.hpp> carries the full generated field-by-field
// oracle; the subset below keeps this header self-checking on its own.

static_assert(sizeof(Point3) == 24, "Point3 size mismatch");
static_assert(sizeof(Vector3) == 24, "Vector3 size mismatch");
static_assert(sizeof(Quaternion) == 32, "Quaternion size mismatch");
static_assert(sizeof(Twist) == 56, "Twist size mismatch");
static_assert(sizeof(Pose2D) == 32, "Pose2D size mismatch");
static_assert(sizeof(TransformStamped) == 64, "TransformStamped size mismatch");
static_assert(sizeof(Pose3D) == 64, "Pose3D size mismatch");
static_assert(sizeof(PoseStamped) == 104, "PoseStamped size mismatch");
static_assert(sizeof(PoseWithCovariance) == 392, "PoseWithCovariance size mismatch");
static_assert(sizeof(TwistWithCovariance) == 384, "TwistWithCovariance size mismatch");
static_assert(sizeof(Accel) == 56, "Accel size mismatch");
static_assert(sizeof(AccelStamped) == 96, "AccelStamped size mismatch");

// Composite types: verify the nested member boundaries, where a wrong
// nested struct or missing padding would silently shift every later field.
static_assert(offsetof(Pose3D, position) == 0, "Pose3D::position offset");
static_assert(offsetof(Pose3D, orientation) == 24, "Pose3D::orientation offset");
static_assert(offsetof(Pose3D, timestamp_ns) == 56, "Pose3D::timestamp_ns offset");

static_assert(offsetof(PoseStamped, pose) == 0, "PoseStamped::pose offset");
static_assert(offsetof(PoseStamped, frame_id) == 64, "PoseStamped::frame_id offset");
static_assert(offsetof(PoseStamped, timestamp_ns) == 96, "PoseStamped::timestamp_ns offset");

static_assert(offsetof(PoseWithCovariance, pose) == 0, "PoseWithCovariance::pose offset");
static_assert(offsetof(PoseWithCovariance, covariance) == 64, "PoseWithCovariance::covariance offset");
static_assert(offsetof(PoseWithCovariance, frame_id) == 352, "PoseWithCovariance::frame_id offset");
static_assert(offsetof(PoseWithCovariance, timestamp_ns) == 384, "PoseWithCovariance::timestamp_ns offset");

static_assert(offsetof(TwistWithCovariance, twist) == 0, "TwistWithCovariance::twist offset");
static_assert(offsetof(TwistWithCovariance, covariance) == 56, "TwistWithCovariance::covariance offset");
static_assert(offsetof(TwistWithCovariance, frame_id) == 344, "TwistWithCovariance::frame_id offset");
static_assert(offsetof(TwistWithCovariance, timestamp_ns) == 376, "TwistWithCovariance::timestamp_ns offset");

static_assert(offsetof(AccelStamped, accel) == 0, "AccelStamped::accel offset");
static_assert(offsetof(AccelStamped, frame_id) == 56, "AccelStamped::frame_id offset");
static_assert(offsetof(AccelStamped, timestamp_ns) == 88, "AccelStamped::timestamp_ns offset");

}} // namespace horus::msg
