// GENERATED by horus C++ bindings — do not edit manually.
// Source: horus_library/messages/keyboard_input_msg.rs, joystick_msg.rs, audio.rs
#pragma once

#include <cstddef>
#include <cstdint>

namespace horus { namespace msg {

/// Keyboard input event
struct KeyboardInput {
    uint32_t key;
    uint32_t code;
    uint8_t key_name[32];
    uint8_t modifiers;   // bit flags: shift=1, ctrl=2, alt=4, super=8
    bool is_pressed;
    uint64_t timestamp_ns;
};

/// Joystick/gamepad input
struct JoystickInput {
    float axes[8];
    uint8_t buttons[16];
    uint8_t button_count;
    uint8_t axis_count;
    uint64_t timestamp_ns;
};

/// Audio frame (PCM)
struct AudioFrame {
    int16_t data[4096];
    uint32_t sample_count;
    uint32_t sample_rate;
    uint8_t encoding;    // 0=PCM16, 1=PCM32, 2=ULAW, 3=ALAW
    uint64_t timestamp_ns;
};

}} // namespace horus::msg
