// GENERATED by horus C++ bindings — do not edit manually.
// Source: horus-robotics/messages/keyboard_input_msg.rs, joystick_msg.rs, audio.rs
//
// Every struct below mirrors its `#[repr(C)]` Rust counterpart FIELD-FOR-FIELD.
// The Rust definition is the ABI: these structs are memcpy'd in and out of shared
// memory by horus_cpp/src/c_api.rs, so field order, types and explicit padding
// members must match exactly. Verified by include/horus/layout_contract.hpp.
//
// Rust `bool` is mirrored as `uint8_t` (Rust bool is exactly 1 byte; uint8_t is
// portable across compilers where `bool` size/representation is implementation
// defined).
#pragma once

#include <cstddef>
#include <cstdint>

namespace horus { namespace msg {

/// Maximum audio samples per frame (horus_robotics::MAX_AUDIO_SAMPLES).
/// 48 kHz at 100 ms chunks. Multi-channel audio is interleaved (L R L R ...).
static constexpr size_t MAX_AUDIO_SAMPLES = 4800;

/// Audio encoding format — mirrors Rust `#[repr(u8)] enum AudioEncoding`.
/// Stored in AudioFrame::encoding as a raw uint8_t.
enum AudioEncoding : uint8_t {
    AUDIO_ENCODING_F32 = 0,  ///< 32-bit float, range [-1.0, 1.0]
    AUDIO_ENCODING_I16 = 1,  ///< 16-bit signed integer, range [-32768, 32767]
};

/// Audio data from a microphone or audio source.
/// Mirrors Rust `horus_robotics::messages::audio::AudioFrame` (19256 bytes).
struct AudioFrame {
    /// Audio sample data, interleaved for multi-channel. f32, NOT i16.
    float samples[MAX_AUDIO_SAMPLES];      // offset     0
    /// Number of valid samples in the buffer. For stereo: frames * 2.
    uint32_t num_samples;                  // offset 19200
    /// Sample rate in Hz (e.g. 8000, 16000, 44100, 48000).
    uint32_t sample_rate;                  // offset 19204
    /// Number of audio channels (1 = mono, 2 = stereo).
    uint8_t channels;                      // offset 19208
    /// Audio encoding format — an AudioEncoding value.
    uint8_t encoding;                      // offset 19209
    /// Explicit padding present in the Rust struct.
    uint8_t _pad[2];                       // offset 19210
    /// Timestamp in nanoseconds since epoch.
    uint64_t timestamp_ns;                 // offset 19216
    /// Sensor/source identifier, null-terminated (e.g. "mic_left").
    uint8_t frame_id[32];                  // offset 19224
};

/// Modifier bit flags for KeyboardInput::modifier_flags.
/// Mirrors the MODIFIER_* constants in keyboard_input_msg.rs.
static constexpr uint32_t MODIFIER_CTRL  = 1u << 0;
static constexpr uint32_t MODIFIER_ALT   = 1u << 1;
static constexpr uint32_t MODIFIER_SHIFT = 1u << 2;
static constexpr uint32_t MODIFIER_SUPER = 1u << 3;
static constexpr uint32_t MODIFIER_HYPER = 1u << 4;
static constexpr uint32_t MODIFIER_META  = 1u << 5;

/// Cross-platform keyboard event.
/// Mirrors Rust `horus_robotics::messages::keyboard_input_msg::KeyboardInput` (72 bytes).
struct KeyboardInput {
    /// Fixed-size key name buffer, null-terminated (e.g. "a", "Enter").
    uint8_t key_name[32];                  // offset  0
    /// Raw key code.
    uint32_t code;                         // offset 32
    /// Bit flags for modifiers — see MODIFIER_* above.
    uint32_t modifier_flags;               // offset 36
    /// 1 for press, 0 for release.
    uint8_t pressed;                       // offset 40
    /// Unix timestamp in MILLISECONDS (not nanoseconds).
    uint64_t timestamp_ms;                 // offset 48
    /// Explicit padding present in the Rust struct (pads to JoystickInput's 72 bytes).
    uint8_t _padding[16];                  // offset 56
};

/// Cross-platform joystick / gamepad event.
/// Mirrors Rust `horus_robotics::messages::joystick_msg::JoystickInput` (72 bytes).
///
/// This is a single EVENT, not a full controller state snapshot: there are no
/// axes[]/buttons[] arrays. `event_type` selects the meaning of the other fields.
struct JoystickInput {
    /// Joystick/controller ID (0, 1, 2, 3...).
    uint32_t joystick_id;                  // offset  0
    /// Fixed-size event type buffer, null-terminated:
    /// "button", "axis", "hat", "connection".
    uint8_t event_type[16];                // offset  4
    /// Button/axis/hat number.
    uint32_t element_id;                   // offset 20
    /// Fixed-size element name buffer, null-terminated (e.g. "A", "LeftStickX").
    uint8_t element_name[32];              // offset 24
    /// Button: 0.0/1.0, Axis: -1.0 to 1.0, Hat: directional.
    float value;                           // offset 56
    /// For buttons: 1 when pressed, 0 when released.
    uint8_t pressed;                       // offset 60
    /// Unix timestamp in MILLISECONDS (not nanoseconds).
    uint64_t timestamp_ms;                 // offset 64
};

}} // namespace horus::msg
