// GENERATED by horus C++ bindings — do not edit manually.
// Source: horus_library/messages/navigation.rs
#pragma once

#include <cstddef>
#include <cstdint>

namespace horus { namespace msg {

/// Navigation goal (2D target)
struct NavGoal {
    double target_x;
    double target_y;
    double target_theta;
    float tolerance;
    uint64_t timestamp_ns;
};

/// Navigation goal result
struct GoalResult {
    bool success;
    float distance_error;
    float angle_error;
    uint64_t timestamp_ns;
};

/// Single waypoint in a path
struct Waypoint {
    double x;
    double y;
    double heading;
    float velocity;
    uint64_t timestamp_ns;
};

/// Velocity obstacle for collision avoidance
struct VelocityObstacle {
    double center[2];
    double velocity[2];
    double radius;
};

}} // namespace horus::msg
