// GENERATED by horus C++ bindings — do not edit manually.
// Source: horus_library/messages/navigation.rs
#pragma once

#include <cstddef>
#include <cstdint>

namespace horus { namespace msg {

/// Navigation goal (2D target)
struct NavGoal {
    double target_x;
    double target_y;
    double target_theta;
    float tolerance;
    uint64_t timestamp_ns;
};

/// Navigation goal result
struct GoalResult {
    bool success;
    float distance_error;
    float angle_error;
    uint64_t timestamp_ns;
};

/// Single waypoint in a path
struct Waypoint {
    double x;
    double y;
    double heading;
    float velocity;
    uint64_t timestamp_ns;
};

/// Velocity obstacle for collision avoidance
struct VelocityObstacle {
    double center[2];
    double velocity[2];
    double radius;
};

/// Path plan with fixed waypoint buffer
struct PathPlan {
    float waypoint_data[768];     // 256 waypoints x 3 floats (x, y, heading)
    float goal_pose[3];           // [x, y, theta]
    uint16_t waypoint_count;
    uint64_t timestamp_ns;
};

}} // namespace horus::msg
