// GENERATED by horus C++ bindings — do not edit manually.
// Source: horus-robotics/messages/sensor.rs
#pragma once

#include <cstddef>
#include <cstdint>
#include "geometry.hpp"

namespace horus { namespace msg {

/// 2D LiDAR scan — 360 fixed range readings
struct LaserScan {
    float ranges[360];       // meters (0 = invalid)
    float angle_min;         // radians
    float angle_max;         // radians
    float min_range;         // meters
    float max_range;         // meters
    float time_increment;    // seconds between measurements
    float scan_time;         // seconds for full scan
    uint64_t timestamp_ns;
};

/// Inertial Measurement Unit — orientation + angular velocity + linear acceleration
struct Imu {
    double orientation[4];                   // quaternion [x,y,z,w]
    double orientation_covariance[9];        // 3x3 row-major (-1 = no data)
    double angular_velocity[3];              // rad/s [x,y,z]
    double angular_velocity_covariance[9];   // 3x3 row-major
    double linear_acceleration[3];           // m/s^2 [x,y,z]
    double linear_acceleration_covariance[9];// 3x3 row-major
    uint64_t timestamp_ns;
};

/// Odometry — pose + velocity with covariance
struct Odometry {
    Pose2D pose;
    Twist twist;
    double pose_covariance[36];   // 6x6 row-major
    double twist_covariance[36];  // 6x6 row-major
    uint64_t timestamp_ns;
};

/// Range sensor (ultrasonic/infrared)
struct RangeSensor {
    uint8_t sensor_type;  // 0=ultrasonic, 1=infrared
    float field_of_view;  // radians
    float min_range;      // meters
    float max_range;      // meters
    float range;          // meters (current reading)
    uint64_t timestamp_ns;
};

/// Battery state monitoring
struct BatteryState {
    float voltage;        // volts
    float current;        // amperes (negative = discharging)
    float charge;         // amp-hours (NaN if unknown)
    float capacity;       // amp-hours (NaN if unknown)
    float percentage;     // 0.0-1.0 (NaN if unknown)
    uint8_t health;       // 0=unknown, 1=good, 2=overheat, 3=dead, 4=overvoltage, 5=bad_cell
    uint8_t status;       // 0=unknown, 1=charging, 2=discharging, 3=not_charging, 4=full
    uint64_t timestamp_ns;
};

/// GPS/GNSS fix
struct NavSatFix {
    double latitude;      // degrees (positive = North)
    double longitude;     // degrees (positive = East)
    double altitude;      // meters above WGS84
    double position_covariance[9]; // diagonal [lat,lon,alt]
    int8_t status;        // -1=no fix, 0=fix, 1=SBAS, 2=GBAS
    uint8_t satellites;   // visible satellites
    uint64_t timestamp_ns;
};

/// Magnetometer reading
struct MagneticField {
    double magnetic_field[3];             // Tesla [x,y,z]
    double magnetic_field_covariance[9];  // 3x3 row-major
    uint8_t frame_id[32];
    uint64_t timestamp_ns;
};

/// Temperature sensor
struct Temperature {
    double temperature;   // degrees Celsius
    double variance;      // 0 if exact
    uint8_t frame_id[32];
    uint64_t timestamp_ns;
};

/// Pressure sensor
struct FluidPressure {
    double fluid_pressure; // Pascals
    double variance;
    uint8_t frame_id[32];
    uint64_t timestamp_ns;
};

/// Light sensor
struct Illuminance {
    double illuminance;   // Lux
    double variance;
    uint8_t frame_id[32];
    uint64_t timestamp_ns;
};

/// Joint state — positions, velocities, efforts for up to 16 joints
struct JointState {
    uint8_t names[16][32];    // null-terminated joint names
    uint8_t joint_count;
    double positions[16];     // radians or meters
    double velocities[16];    // rad/s or m/s
    double efforts[16];       // Nm or N
    uint64_t timestamp_ns;
};

// Layout assertions for critical types
static_assert(sizeof(Imu) == 304, "Imu size mismatch");
static_assert(sizeof(Twist) == 56, "Twist size dependency");
static_assert(sizeof(Pose2D) == 32, "Pose2D size dependency");

}} // namespace horus::msg
