// GENERATED by horus C++ bindings — do not edit manually.
// Source: horus_types/src/time.rs
//
// Every struct below mirrors its Rust `#[repr(C)]` counterpart in
// `horus_types::time` EXACTLY — field order, widths and explicit padding.
// The C ABI (`horus_publisher_*_send` / `horus_subscriber_*_recv`) does a raw
// `std::ptr::read` / `std::ptr::write` of the RUST struct through the pointer
// you pass, so any divergence here is memory corruption, not a type error.
//
// Rust `bool`/`u8` discriminants are mirrored as `uint8_t` (Rust bool is
// exactly 1 byte; `uint8_t` is portable where C++ `bool` is only
// implementation-defined).
#pragma once

#include <cstddef>
#include <cstdint>

namespace horus { namespace msg {

/// Simulation/replay time broadcast.
/// Mirrors Rust `horus_types::time::Clock` (40 bytes).
///
/// `source` values: SOURCE_WALL = 0, SOURCE_SIM = 1, SOURCE_REPLAY = 2.
/// `paused` values: 0 = running, 1 = paused.
struct Clock {
    /// Current simulation/replay time in nanoseconds.
    uint64_t clock_ns;
    /// Wall clock time for comparison.
    uint64_t realtime_ns;
    /// Playback speed (1.0 = real-time, 2.0 = 2x, 0.5 = half speed).
    double sim_speed;
    /// 0 = running, 1 = paused. (Rust `u8`, not a bool.)
    uint8_t paused;
    /// SOURCE_WALL=0, SOURCE_SIM=1, SOURCE_REPLAY=2.
    uint8_t source;
    /// Explicit padding present in the Rust struct — do not remove.
    uint8_t _pad[6];
    /// Timestamp when this message was published.
    uint64_t timestamp_ns;
};

/// External time-source reference (GPS / NTP / PTP).
/// Mirrors Rust `horus_types::time::TimeReference` (56 bytes).
struct TimeReference {
    /// External reference time in nanoseconds.
    uint64_t time_ref_ns;
    /// Source identifier (e.g. "gps", "ntp", "ptp"), null-terminated.
    uint8_t source[32];
    /// Signed offset: local_time - reference_time (nanoseconds).
    int64_t offset_ns;
    /// Timestamp when this message was published.
    uint64_t timestamp_ns;
};

/// Lockstep simulation step handshake.
/// Mirrors Rust `horus_types::time::SimSync` (32 bytes).
///
/// `state` values: IDLE = 0, WAITING = 1 (sim waiting for controller),
/// DONE = 2 (controller done).
///
/// NOTE: this type has no C ABI entry point in `c_api.rs`, so
/// `layout_contract.hpp` emits no assertions for it; the layout below is
/// derived directly from the Rust source.
struct SimSync {
    /// Simulation step number (monotonically increasing).
    uint64_t step;
    /// Simulation time in nanoseconds at this step.
    uint64_t sim_time_ns;
    /// Physics timestep in nanoseconds (e.g. 1'000'000 for 1ms).
    uint64_t dt_ns;
    /// 0 = IDLE, 1 = WAITING, 2 = DONE.
    uint8_t state;
    /// Explicit padding present in the Rust struct — do not remove.
    uint8_t _pad[7];
};

/// Dynamic rate-negotiation request.
/// Mirrors Rust `horus_types::time::RateRequest` (72 bytes).
///
/// NOTE: this type has no C ABI entry point in `c_api.rs`, so
/// `layout_contract.hpp` emits no assertions for it; the layout below is
/// derived directly from the Rust source.
struct RateRequest {
    /// Topic name being negotiated (null-terminated, max 31 chars).
    uint8_t topic_name[32];
    /// Desired rate in Hz.
    double desired_hz;
    /// Minimum acceptable rate in Hz.
    double min_hz;
    /// Maximum acceptable rate in Hz.
    double max_hz;
    /// ID of the requesting node/process.
    uint64_t requester_id;
    /// Timestamp in nanoseconds.
    uint64_t timestamp_ns;
};

}} // namespace horus::msg
