// GENERATED by horus C++ bindings — do not edit manually.
// Source: horus_library/messages/clock.rs
#pragma once

#include <cstddef>
#include <cstdint>

namespace horus { namespace msg {

/// System clock (supports wall, sim, replay modes)
struct Clock {
    uint64_t timestamp_ns;
    uint64_t wall_time_ns;
    bool is_simulated;
};

/// Time reference for synchronization
struct TimeReference {
    uint8_t time_ref_source[64];  // null-terminated
    uint64_t timestamp_ns;
    uint64_t wall_time_ns;
};

/// Simulator time synchronization
struct SimSync {
    uint64_t sim_time_ns;
    uint64_t wall_time_ns;
    uint64_t step_size_ns;
    bool paused;
};

/// Rate control request
struct RateRequest {
    double rate_hz;
    uint64_t deadline_ns;
    uint64_t timestamp_ns;
};

}} // namespace horus::msg
