// GENERATED by horus C++ bindings — do not edit manually.
// Source: horus_library/messages/vision.rs
#pragma once

#include <cstddef>
#include <cstdint>

namespace horus { namespace msg {

/// Camera intrinsic calibration parameters
struct CameraInfo {
    uint32_t width;
    uint32_t height;
    double fx;               // focal length x (pixels)
    double fy;               // focal length y (pixels)
    double cx;               // principal point x (pixels)
    double cy;               // principal point y (pixels)
    double distortion[5];    // distortion coefficients [k1,k2,p1,p2,k3]
    uint64_t timestamp_ns;
};

/// Region of interest
struct RegionOfInterest {
    uint32_t x_offset;
    uint32_t y_offset;
    uint32_t height;
    uint32_t width;
    bool do_rectify;
};

/// Stereo camera calibration
struct StereoInfo {
    CameraInfo left;
    CameraInfo right;
    double baseline;         // meters between cameras
    uint64_t timestamp_ns;
};

}} // namespace horus::msg
