//! Generate `.horus/Cargo.toml` from `horus.toml` dependencies.
//!
//! This module is the bridge between the unified horus manifest and the Cargo
//! build system. It reads `[dependencies]` from `horus.toml`, filters for
//! Rust-relevant deps (crates.io, path, git, registry), and produces a
//! valid `Cargo.toml` inside `.horus/`.
//!
//! The generated file is always gitignored and treated as a build artifact.

use anyhow::{Context, Result};
use colored::Colorize;
use std::collections::BTreeMap;
use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::{Path, PathBuf};

use crate::manifest::{DepSource, DependencyValue, HorusManifest};

/// The `.horus` build directory name.
const HORUS_DIR: &str = ".horus";

/// Generate `.horus/Cargo.toml` from a `HorusManifest`.
///
/// - Filters crates.io, path, git, and registry deps from `[dependencies]`
/// - Adds horus_core/horus_library as path deps (found via `find_horus_source_dir`)
/// - Creates `[[bin]]` entries from source files
/// - Returns the path to the generated `Cargo.toml`
///
/// # Arguments
///
/// * `manifest` - The parsed horus.toml manifest
/// * `project_dir` - The project root directory (where horus.toml lives)
/// * `source_files` - List of .rs source files to create [[bin]] entries for
/// * `include_dev` - Whether to include dev-dependencies (for `horus test`)
pub fn generate(
    manifest: &HorusManifest,
    project_dir: &Path,
    source_files: &[PathBuf],
    include_dev: bool,
) -> Result<(PathBuf, String)> {
    let horus_dir = project_dir.join(HORUS_DIR);
    fs::create_dir_all(&horus_dir).context("Failed to create .horus directory")?;

    let project_name = &manifest.package.name;
    let version = &manifest.package.version;

    let mut cargo = String::with_capacity(2048);

    // ── Header ───────────────────────────────────────────────────────────
    writeln!(
        cargo,
        "# Generated by horus from horus.toml — do not edit manually"
    )
    .unwrap();
    writeln!(cargo, "[package]").unwrap();
    writeln!(cargo, "name = \"{}\"", sanitize_cargo_name(project_name)).unwrap();
    writeln!(cargo, "version = \"{}\"", version).unwrap();
    writeln!(cargo, "edition = \"2021\"").unwrap();
    writeln!(cargo).unwrap();

    // ── Workspace isolation ──────────────────────────────────────────────
    // Prevents inheriting a parent workspace
    writeln!(cargo, "[workspace]").unwrap();
    writeln!(cargo).unwrap();

    // ── Binary targets ───────────────────────────────────────────────────
    if source_files.is_empty() {
        // Default: look for main.rs in project root
        let main_rs = project_dir.join("main.rs");
        let src_main = project_dir.join("src/main.rs");
        if main_rs.exists() {
            write_bin_entry(
                &mut cargo,
                project_name,
                &relative_to_horus(&main_rs, &horus_dir),
            );
        } else if src_main.exists() {
            write_bin_entry(
                &mut cargo,
                project_name,
                &relative_to_horus(&src_main, &horus_dir),
            );
        }
    } else if source_files.len() == 1 {
        let rel = relative_to_horus(&source_files[0], &horus_dir);
        write_bin_entry(&mut cargo, project_name, &rel);
    } else {
        for file in source_files {
            let stem = file
                .file_stem()
                .map(|s| s.to_string_lossy().to_string())
                .unwrap_or_else(|| "main".to_string());
            let rel = relative_to_horus(file, &horus_dir);
            write_bin_entry(&mut cargo, &stem, &rel);
        }
    }

    // ── Auto-install missing registry deps ────────────────────────────────
    auto_install_registry_deps(&manifest.dependencies, project_dir, &horus_dir)?;
    if include_dev && !manifest.dev_dependencies.is_empty() {
        auto_install_registry_deps(&manifest.dev_dependencies, project_dir, &horus_dir)?;
    }

    // ── Dependencies ─────────────────────────────────────────────────────
    writeln!(cargo, "[dependencies]").unwrap();

    // Add horus core path deps
    if let Ok(horus_source) = crate::commands::run::find_horus_source_dir() {
        write_horus_path_deps(&mut cargo, &horus_source, manifest);
    }

    // Add user deps from horus.toml
    write_deps_section(&mut cargo, &manifest.dependencies, project_dir, &horus_dir)?;

    // Add driver dependencies from [drivers] config tables
    write_driver_deps(&mut cargo, &manifest.drivers);

    // ── Dev dependencies ─────────────────────────────────────────────────
    if include_dev && !manifest.dev_dependencies.is_empty() {
        writeln!(cargo).unwrap();
        writeln!(cargo, "[dev-dependencies]").unwrap();
        write_deps_section(
            &mut cargo,
            &manifest.dev_dependencies,
            project_dir,
            &horus_dir,
        )?;
    }

    // ── Write file ───────────────────────────────────────────────────────
    let cargo_toml_path = horus_dir.join("Cargo.toml");
    fs::write(&cargo_toml_path, &cargo)
        .with_context(|| format!("Failed to write {}", cargo_toml_path.display()))?;

    Ok((cargo_toml_path, cargo))
}

/// Write driver dependencies from `[drivers]` config tables.
///
/// For each `[drivers.NAME]` entry:
/// - `terra = "dynamixel"` → adds `terra-serial = { version = "0.2", features = ["dynamixel"] }`
/// - `package = "horus-driver-x"` → adds `horus-driver-x = "*"`
/// - `node = "MyDriver"` → no dependency (local code)
/// - `camera = "opencv"` / `gps = true` → no dependency (legacy, handled by feature flags)
fn write_driver_deps(
    cargo: &mut String,
    drivers: &std::collections::BTreeMap<String, crate::manifest::DriverValue>,
) {
    use crate::manifest::DriverValue;

    // Track crates already added to avoid duplicates (e.g., two drivers using terra-serial)
    let mut added_crates: std::collections::HashMap<String, Vec<String>> =
        std::collections::HashMap::new();

    for value in drivers.values() {
        match value {
            DriverValue::Config(cfg) => {
                // Terra drivers: no longer auto-resolved — user adds terra-horus
                // as a normal dependency in [dependencies]. Skip terra entries.
                if let Some(package) = &cfg.package {
                    if !added_crates.contains_key(package) {
                        added_crates.insert(package.clone(), Vec::new());
                    }
                } else if let Some(crate_name) = &cfg.crate_name {
                    // CratesIo driver — add the crate as a dependency
                    let _version = cfg.params.get("version")
                        .and_then(|v| v.as_str())
                        .unwrap_or("*")
                        .to_string();
                    added_crates.entry(crate_name.clone()).or_insert_with(|| {
                        // Store version as first "feature" entry (hacky but works with existing output logic)
                        // TODO: separate version tracking from features
                        Vec::new()
                    });
                }
                // pip/exec/sim3d/node → no Cargo dep needed
            }
            DriverValue::Backend(_) | DriverValue::Enabled(_) => {
                // Legacy — handled by feature flags in get_cargo_features_from_drivers()
            }
        }
    }

    if !added_crates.is_empty() {
        writeln!(cargo, "\n# Driver dependencies (from [drivers])").unwrap();
        for (crate_name, features) in &added_crates {
            if features.is_empty() {
                writeln!(cargo, "{} = \"*\"", crate_name).unwrap();
            } else {
                let features_str = features
                    .iter()
                    .map(|f| format!("\"{}\"", f))
                    .collect::<Vec<_>>()
                    .join(", ");
                writeln!(
                    cargo,
                    "{} = {{ version = \"*\", features = [{}] }}",
                    crate_name, features_str
                )
                .unwrap();
            }
        }
    }
}

/// Write a `[[bin]]` entry.
fn write_bin_entry(cargo: &mut String, name: &str, path: &str) {
    writeln!(cargo, "[[bin]]").unwrap();
    writeln!(cargo, "name = \"{}\"", sanitize_cargo_name(name)).unwrap();
    writeln!(cargo, "path = \"{}\"", path).unwrap();
    writeln!(cargo).unwrap();
}

/// Write horus core/library/macros path dependencies.
fn write_horus_path_deps(cargo: &mut String, horus_source: &Path, manifest: &HorusManifest) {
    // Detect hardware features from manifest
    let hw_features: Vec<&str> = manifest
        .drivers
        .keys()
        .filter_map(|k| match k.as_str() {
            "camera" => Some("camera"),
            "lidar" => Some("lidar"),
            "imu" => Some("imu"),
            "gps" => Some("gps"),
            _ => None,
        })
        .collect();

    for dep_name in &["horus", "horus_core", "horus_library", "horus_macros"] {
        let dep_path = horus_source.join(dep_name);
        if dep_path.exists() && dep_path.join("Cargo.toml").exists() {
            if (*dep_name == "horus" || *dep_name == "horus_library") && !hw_features.is_empty() {
                writeln!(
                    cargo,
                    "{} = {{ path = \"{}\", features = [{}] }}",
                    dep_name,
                    dep_path.display(),
                    hw_features
                        .iter()
                        .map(|f| format!("\"{}\"", f))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
                .unwrap();
            } else {
                writeln!(
                    cargo,
                    "{} = {{ path = \"{}\" }}",
                    dep_name,
                    dep_path.display()
                )
                .unwrap();
            }
        }
    }
}

/// Write dependencies from a BTreeMap to Cargo.toml format.
///
/// Filters for Rust-compatible deps: crates.io, path, git.
/// Registry deps are resolved to path deps pointing to .horus/packages/.
/// PyPI and System deps are skipped (not relevant for Cargo).
///
/// For Simple deps that default to Registry, the smart source resolver is
/// consulted — if the package is a well-known crate, it's treated as crates.io.
fn write_deps_section(
    cargo: &mut String,
    deps: &std::collections::BTreeMap<String, DependencyValue>,
    project_dir: &Path,
    horus_dir: &Path,
) -> Result<()> {
    use crate::manifest::Language;
    use crate::source_resolver::PackageSourceResolver;
    let resolver = PackageSourceResolver::new(&[Language::Rust]);

    for (name, dep) in deps {
        let source = match dep.effective_source() {
            DepSource::Registry => {
                // Simple deps default to Registry — use smart resolver to check
                // if it's actually a well-known crates.io package.
                // Only upgrade with High confidence to avoid false positives.
                let resolved = resolver.resolve(name);
                if resolved.confidence == crate::source_resolver::Confidence::High {
                    resolved.source
                } else {
                    DepSource::Registry
                }
            }
            other => other,
        };
        match source {
            DepSource::CratesIo => {
                write_crates_io_dep(cargo, name, dep);
            }
            DepSource::Path => {
                if let DependencyValue::Detailed(d) = dep {
                    if let Some(ref p) = d.path {
                        // Resolve path relative to project dir, then make relative to .horus/
                        let abs_path = project_dir.join(p);
                        let rel = relative_to_horus(&abs_path, horus_dir);
                        writeln!(cargo, "{} = {{ path = \"{}\" }}", name, rel).unwrap();
                    }
                }
            }
            DepSource::Git => {
                if let DependencyValue::Detailed(d) = dep {
                    write_git_dep(cargo, name, d);
                }
            }
            DepSource::Registry => {
                // Registry packages are installed to .horus/packages/<name>/
                // If the package dir exists, add as path dep
                let pkg_dir = horus_dir.join("packages").join(name);
                if pkg_dir.exists() && pkg_dir.join("Cargo.toml").exists() {
                    writeln!(cargo, "{} = {{ path = \"packages/{}\" }}", name, name).unwrap();
                } else {
                    writeln!(
                        cargo,
                        "# {} = \"{}\" (registry, not yet installed)",
                        name,
                        dep.version().unwrap_or("*")
                    )
                    .unwrap();
                }
            }
            DepSource::PyPI | DepSource::System => {
                // Not Cargo deps — skip silently
            }
        }
    }
    Ok(())
}

/// Auto-install missing registry dependencies before Cargo.toml generation.
///
/// Scans the dependency map for `DepSource::Registry` entries, checks if each
/// is already present in `.horus/packages/<name>/`, and silently installs any
/// that are missing from the horus registry. This ensures `write_deps_section`
/// can emit real path deps instead of commented-out placeholders.
///
/// Failures are logged as warnings — the build continues and cargo will report
/// the missing crate with a clear error if auto-install didn't succeed.
fn auto_install_registry_deps(
    deps: &BTreeMap<String, DependencyValue>,
    project_dir: &Path,
    horus_dir: &Path,
) -> Result<()> {
    use crate::source_resolver::PackageSourceResolver;
    use crate::manifest::Language;

    let resolver = PackageSourceResolver::new(&[Language::Rust]);
    let mut missing: Vec<(String, Option<String>)> = Vec::new();

    for (name, dep) in deps {
        let source = match dep.effective_source() {
            DepSource::Registry => {
                let resolved = resolver.resolve(name);
                if resolved.confidence == crate::source_resolver::Confidence::High {
                    resolved.source
                } else {
                    DepSource::Registry
                }
            }
            other => other,
        };

        if source == DepSource::Registry {
            let pkg_dir = horus_dir.join("packages").join(name);
            if !pkg_dir.exists() || !pkg_dir.join("Cargo.toml").exists() {
                missing.push((name.clone(), dep.version().map(String::from)));
            }
        }
    }

    if missing.is_empty() {
        return Ok(());
    }

    eprintln!(
        "  {} Auto-installing {} registry package(s)...",
        crate::cli_output::ICON_INFO.cyan(),
        missing.len()
    );

    let client = crate::registry::RegistryClient::new();
    let target = crate::workspace::InstallTarget::Local(project_dir.to_path_buf());

    for (name, version) in &missing {
        eprintln!("    {} {}...", "v".cyan(), name);
        match client.install_from_registry(name, version.as_deref(), target.clone()) {
            Ok(v) => {
                eprintln!(
                    "    {} {} v{}",
                    crate::cli_output::ICON_SUCCESS.green(),
                    name,
                    v
                );
            }
            Err(e) => {
                // Warn but don't fail — cargo build will give a clear error
                eprintln!(
                    "    {} Failed to auto-install {}: {}",
                    crate::cli_output::ICON_WARN.yellow(),
                    name,
                    e
                );
            }
        }
    }

    Ok(())
}

/// Write a crates.io dependency line.
fn write_crates_io_dep(cargo: &mut String, name: &str, dep: &DependencyValue) {
    match dep {
        DependencyValue::Simple(v) => {
            writeln!(cargo, "{} = \"{}\"", name, v).unwrap();
        }
        DependencyValue::Detailed(d) => {
            let version = d.version.as_deref().unwrap_or("*");
            if d.features.is_empty() && !d.optional {
                writeln!(cargo, "{} = \"{}\"", name, version).unwrap();
            } else {
                let mut parts = vec![format!("version = \"{}\"", version)];
                if !d.features.is_empty() {
                    let feats = d
                        .features
                        .iter()
                        .map(|f| format!("\"{}\"", f))
                        .collect::<Vec<_>>()
                        .join(", ");
                    parts.push(format!("features = [{}]", feats));
                }
                if d.optional {
                    parts.push("optional = true".to_string());
                }
                writeln!(cargo, "{} = {{ {} }}", name, parts.join(", ")).unwrap();
            }
        }
    }
}

/// Write a git dependency line.
fn write_git_dep(cargo: &mut String, name: &str, d: &crate::manifest::DetailedDependency) {
    let git_url = d.git.as_deref().unwrap_or("");
    let mut parts = vec![format!("git = \"{}\"", git_url)];
    if let Some(ref branch) = d.branch {
        parts.push(format!("branch = \"{}\"", branch));
    }
    if let Some(ref tag) = d.tag {
        parts.push(format!("tag = \"{}\"", tag));
    }
    if let Some(ref rev) = d.rev {
        parts.push(format!("rev = \"{}\"", rev));
    }
    writeln!(cargo, "{} = {{ {} }}", name, parts.join(", ")).unwrap();
}

/// Compute a relative path from `.horus/` to a file.
///
/// e.g., `/home/user/project/main.rs` from `/home/user/project/.horus/`
/// → `../main.rs`
fn relative_to_horus(file: &Path, horus_dir: &Path) -> String {
    // Try to compute relative path
    if let Ok(rel) = pathdiff(file, horus_dir) {
        rel
    } else {
        // Fallback to absolute
        file.to_string_lossy().to_string()
    }
}

/// Simple relative path computation (from -> to).
fn pathdiff(target: &Path, base: &Path) -> Result<String, ()> {
    // Canonicalize if possible, otherwise use as-is
    let target = target
        .canonicalize()
        .unwrap_or_else(|_| target.to_path_buf());
    let base = base.canonicalize().unwrap_or_else(|_| base.to_path_buf());

    let mut target_parts: Vec<_> = target.components().collect();
    let mut base_parts: Vec<_> = base.components().collect();

    // Remove common prefix
    while !target_parts.is_empty() && !base_parts.is_empty() && target_parts[0] == base_parts[0] {
        target_parts.remove(0);
        base_parts.remove(0);
    }

    // Go up for remaining base parts, then down for target parts
    let mut result = String::new();
    for _ in &base_parts {
        if !result.is_empty() {
            result.push('/');
        }
        result.push_str("..");
    }
    for part in &target_parts {
        if !result.is_empty() {
            result.push('/');
        }
        result.push_str(&part.as_os_str().to_string_lossy());
    }

    if result.is_empty() {
        result.push('.');
    }

    Ok(result)
}

/// Sanitize a name for use as a Cargo package/bin name.
///
/// Replaces characters that are invalid in Cargo names with underscores.
pub fn sanitize_cargo_name(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' || c == '-' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

// ─── Workspace generation ────────────────────────────────────────────────────

use crate::manifest::{resolve_workspace_members, TargetType};

/// Smart dispatcher: routes to single-package or workspace generation.
///
/// If the manifest has `[workspace]`, generates a Cargo workspace.
/// Otherwise, falls through to the existing single-package `generate()`.
pub fn generate_for_manifest(
    manifest: &HorusManifest,
    project_dir: &Path,
    source_files: &[PathBuf],
    include_dev: bool,
) -> Result<(PathBuf, String)> {
    if let Some(ref ws) = manifest.workspace {
        let members = resolve_workspace_members(ws, project_dir)?;
        generate_workspace(manifest, project_dir, &members)
    } else {
        generate(manifest, project_dir, source_files, include_dev)
    }
}

/// Generate a Cargo workspace from a multi-member horus workspace.
///
/// Produces:
/// - `.horus/Cargo.toml` with `[workspace]` section
/// - `.horus/{member_name}/Cargo.toml` for each member
///
/// Returns the root path and its content for fingerprinting.
pub fn generate_workspace(
    root_manifest: &HorusManifest,
    project_dir: &Path,
    members: &[(PathBuf, HorusManifest)],
) -> Result<(PathBuf, String)> {
    let horus_dir = project_dir.join(HORUS_DIR);
    fs::create_dir_all(&horus_dir).context("Failed to create .horus directory")?;

    // ── Auto-install missing registry deps (workspace + all members) ─────
    if let Some(ref ws) = root_manifest.workspace {
        if !ws.dependencies.is_empty() {
            auto_install_registry_deps(&ws.dependencies, project_dir, &horus_dir)?;
        }
    }
    for (_, member_manifest) in members {
        if !member_manifest.dependencies.is_empty() {
            auto_install_registry_deps(&member_manifest.dependencies, project_dir, &horus_dir)?;
        }
    }

    let mut root_cargo = String::with_capacity(2048);

    // ── Header ────────────────────────────────────────────────────────────
    writeln!(root_cargo, "# Generated by horus from horus.toml — do not edit manually").unwrap();

    // ── Workspace section ─────────────────────────────────────────────────
    writeln!(root_cargo, "[workspace]").unwrap();
    writeln!(root_cargo, "resolver = \"2\"").unwrap();

    // Members list — use sanitized package names as directory names within .horus/
    let member_names: Vec<String> = members
        .iter()
        .map(|(_, m)| sanitize_cargo_name(&m.package.name))
        .collect();
    write!(root_cargo, "members = [").unwrap();
    for (i, name) in member_names.iter().enumerate() {
        if i > 0 {
            write!(root_cargo, ", ").unwrap();
        }
        write!(root_cargo, "\"{}\"", name).unwrap();
    }
    writeln!(root_cargo, "]").unwrap();
    writeln!(root_cargo).unwrap();

    // ── Workspace dependencies ────────────────────────────────────────────
    let ws = root_manifest.workspace.as_ref();
    let ws_deps = ws.map(|w| &w.dependencies);
    let has_ws_deps = ws_deps.is_some_and(|d| !d.is_empty());

    if has_ws_deps || true {
        // Always write [workspace.dependencies] to include horus core deps
        writeln!(root_cargo, "[workspace.dependencies]").unwrap();

        // Auto-inject horus core path deps
        if let Ok(horus_source) = crate::commands::run::find_horus_source_dir() {
            for dep_name in &["horus", "horus_core", "horus_library", "horus_macros"] {
                let dep_path = horus_source.join(dep_name);
                if dep_path.exists() && dep_path.join("Cargo.toml").exists() {
                    writeln!(
                        root_cargo,
                        "{} = {{ path = \"{}\" }}",
                        dep_name,
                        dep_path.display()
                    )
                    .unwrap();
                }
            }
        }

        // User workspace deps
        if let Some(deps) = ws_deps {
            write_deps_section(&mut root_cargo, deps, project_dir, &horus_dir)?;
        }
        writeln!(root_cargo).unwrap();
    }

    // ── If root also has a [package], include it as a member ──────────────
    if !root_manifest.package.name.is_empty() {
        // Root package goes into .horus/ directly (uses the root's source files)
        // For now, root packages in workspace mode use the single-package generate()
        // which already writes to .horus/Cargo.toml — skip for virtual workspaces.
    }

    // ── Generate per-member Cargo.toml ────────────────────────────────────
    for (rel_path, member_manifest) in members {
        let member_name = sanitize_cargo_name(&member_manifest.package.name);
        let member_horus_dir = horus_dir.join(&member_name);
        fs::create_dir_all(&member_horus_dir)
            .with_context(|| format!("Failed to create .horus/{}", member_name))?;

        let member_source_dir = project_dir.join(rel_path);
        let member_cargo = generate_member_cargo(
            &member_name,
            member_manifest,
            &member_source_dir,
            &member_horus_dir,
            root_manifest,
            members,
            &horus_dir,
        )?;

        let member_cargo_path = member_horus_dir.join("Cargo.toml");
        fs::write(&member_cargo_path, &member_cargo)
            .with_context(|| format!("Failed to write {}", member_cargo_path.display()))?;
    }

    // ── Write root Cargo.toml ─────────────────────────────────────────────
    let root_path = horus_dir.join("Cargo.toml");
    fs::write(&root_path, &root_cargo)
        .with_context(|| format!("Failed to write {}", root_path.display()))?;

    Ok((root_path, root_cargo))
}

/// Generate a member's Cargo.toml content.
fn generate_member_cargo(
    member_name: &str,
    member_manifest: &HorusManifest,
    member_source_dir: &Path,
    member_horus_dir: &Path,
    _root_manifest: &HorusManifest,
    all_members: &[(PathBuf, HorusManifest)],
    horus_dir: &Path,
) -> Result<String> {
    let mut cargo = String::with_capacity(1024);

    writeln!(cargo, "# Generated by horus — do not edit").unwrap();

    // ── [package] ─────────────────────────────────────────────────────────
    writeln!(cargo, "[package]").unwrap();
    writeln!(cargo, "name = \"{}\"", member_name).unwrap();
    writeln!(cargo, "version = \"{}\"", member_manifest.package.version).unwrap();
    let edition = member_manifest
        .package
        .rust_edition
        .as_deref()
        .unwrap_or("2021");
    writeln!(cargo, "edition = \"{}\"", edition).unwrap();
    writeln!(cargo).unwrap();

    // ── Target sections ───────────────────────────────────────────────────
    let target = &member_manifest.package.target_type;

    if matches!(target, TargetType::Lib | TargetType::Both) {
        let lib_path = member_source_dir.join("src/lib.rs");
        if lib_path.exists() {
            let rel = relative_to_horus(&lib_path, member_horus_dir);
            writeln!(cargo, "[lib]").unwrap();
            writeln!(cargo, "path = \"{}\"", rel).unwrap();
            writeln!(cargo).unwrap();
        }
    }

    if matches!(target, TargetType::Bin | TargetType::Both) {
        let main_path = member_source_dir.join("src/main.rs");
        let root_main = member_source_dir.join("main.rs");
        if main_path.exists() {
            let rel = relative_to_horus(&main_path, member_horus_dir);
            write_bin_entry(&mut cargo, &member_manifest.package.name, &rel);
        } else if root_main.exists() {
            let rel = relative_to_horus(&root_main, member_horus_dir);
            write_bin_entry(&mut cargo, &member_manifest.package.name, &rel);
        }
    }

    // ── [dependencies] ────────────────────────────────────────────────────
    writeln!(cargo, "[dependencies]").unwrap();

    // Horus core deps as workspace = true
    for dep_name in &["horus", "horus_core", "horus_library", "horus_macros"] {
        writeln!(cargo, "{}.workspace = true", dep_name).unwrap();
    }

    for (name, dep) in &member_manifest.dependencies {
        // workspace = true deps
        if let DependencyValue::Detailed(d) = dep {
            if d.workspace {
                if d.features.is_empty() {
                    writeln!(cargo, "{}.workspace = true", name).unwrap();
                } else {
                    writeln!(
                        cargo,
                        "{} = {{ workspace = true, features = [{}] }}",
                        name,
                        d.features
                            .iter()
                            .map(|f| format!("\"{}\"", f))
                            .collect::<Vec<_>>()
                            .join(", ")
                    )
                    .unwrap();
                }
                continue;
            }
        }

        // Inter-member path deps — rewrite to .horus/ sibling
        if let DependencyValue::Detailed(d) = dep {
            if let Some(ref original_path) = d.path {
                if let Some(rewritten) = rewrite_member_path_dep(
                    original_path,
                    member_source_dir,
                    all_members,
                    horus_dir,
                    member_horus_dir,
                ) {
                    writeln!(cargo, "{} = {{ path = \"{}\" }}", name, rewritten).unwrap();
                    continue;
                }
                // Non-member path dep — relativize from member_horus_dir
                let abs_path = member_source_dir.join(original_path);
                let rel = relative_to_horus(&abs_path, member_horus_dir);
                writeln!(cargo, "{} = {{ path = \"{}\" }}", name, rel).unwrap();
                continue;
            }
        }

        // Regular deps (crates.io, git, etc.) — write as-is
        write_single_dep(&mut cargo, name, dep);
    }

    writeln!(cargo).unwrap();
    Ok(cargo)
}

/// Write a single dependency in Cargo.toml format.
fn write_single_dep(cargo: &mut String, name: &str, dep: &DependencyValue) {
    match dep {
        DependencyValue::Simple(v) => {
            writeln!(cargo, "{} = \"{}\"", name, v).unwrap();
        }
        DependencyValue::Detailed(d) => {
            let version = d.version.as_deref().unwrap_or("*");
            if !d.features.is_empty() {
                let feats = d
                    .features
                    .iter()
                    .map(|f| format!("\"{}\"", f))
                    .collect::<Vec<_>>()
                    .join(", ");
                if d.optional {
                    writeln!(
                        cargo,
                        "{} = {{ version = \"{}\", features = [{}], optional = true }}",
                        name, version, feats
                    )
                    .unwrap();
                } else {
                    writeln!(
                        cargo,
                        "{} = {{ version = \"{}\", features = [{}] }}",
                        name, version, feats
                    )
                    .unwrap();
                }
            } else if let Some(ref git) = d.git {
                let mut parts = format!("{} = {{ git = \"{}\"", name, git);
                if let Some(ref branch) = d.branch {
                    parts.push_str(&format!(", branch = \"{}\"", branch));
                }
                if let Some(ref tag) = d.tag {
                    parts.push_str(&format!(", tag = \"{}\"", tag));
                }
                if let Some(ref rev) = d.rev {
                    parts.push_str(&format!(", rev = \"{}\"", rev));
                }
                parts.push_str(" }");
                writeln!(cargo, "{}", parts).unwrap();
            } else if d.optional {
                writeln!(
                    cargo,
                    "{} = {{ version = \"{}\", optional = true }}",
                    name, version
                )
                .unwrap();
            } else {
                writeln!(cargo, "{} = \"{}\"", name, version).unwrap();
            }
        }
    }
}

/// Detect inter-member path deps and rewrite to `.horus/` sibling directories.
fn rewrite_member_path_dep(
    original_path: &str,
    member_source_dir: &Path,
    all_members: &[(PathBuf, HorusManifest)],
    horus_dir: &Path,
    member_horus_dir: &Path,
) -> Option<String> {
    let target_dir = member_source_dir.join(original_path);
    let target_canonical = target_dir.canonicalize().ok()?;

    let project_dir = horus_dir.parent()?;

    for (rel_path, member_manifest) in all_members {
        let member_dir = project_dir.join(rel_path);
        if let Ok(member_canonical) = member_dir.canonicalize() {
            if member_canonical == target_canonical {
                let target_name = sanitize_cargo_name(&member_manifest.package.name);
                let target_horus = horus_dir.join(&target_name);
                return Some(relative_to_horus(&target_horus, member_horus_dir));
            }
        }
    }

    None
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::*;
    use std::collections::BTreeMap;

    fn test_manifest(deps: BTreeMap<String, DependencyValue>) -> HorusManifest {
        HorusManifest {
            package: PackageInfo {
                name: "test-project".to_string(),
                version: "0.1.0".to_string(),
                description: None,
                authors: vec![],
                license: None,
                edition: "1".to_string(),
                repository: None,
                package_type: None,
                categories: vec![],
                standard: None,
                rust_edition: None,
                target_type: TargetType::default(),
            },
            workspace: None,
            robot: None,
            dependencies: deps,
            dev_dependencies: BTreeMap::new(),
            sim_dependencies: BTreeMap::new(),
            hardware: BTreeMap::new(),
            drivers: BTreeMap::new(),
            sim_drivers: BTreeMap::new(),
            scripts: BTreeMap::new(),
            ignore: IgnoreConfig::default(),
            enable: vec![],
            cpp: None,
            hooks: Default::default(),
            network: None,
        }
    }

    #[test]
    fn generate_minimal_cargo_toml() {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(dir.path().join(".horus")).unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), &[], false);
        assert!(result.is_ok());

        let (cargo_path, _) = result.unwrap();
        let content = fs::read_to_string(&cargo_path).unwrap();
        assert!(content.contains("name = \"test-project\""));
        assert!(content.contains("edition = \"2021\""));
        assert!(content.contains("[workspace]"));
        assert!(content.contains("[[bin]]"));
        assert!(content.contains("../main.rs"));
    }

    #[test]
    fn generate_with_crates_io_deps() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "serde".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some("1.0".to_string()),
                source: Some(DepSource::CratesIo),
                features: vec!["derive".to_string()],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
                apt: None,
                cmake_package: None,
                lang: None,
                workspace: false,
            }),
        );
        deps.insert(
            "tokio".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some("1.0".to_string()),
                source: Some(DepSource::CratesIo),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
                apt: None,
                cmake_package: None,
                lang: None,
                workspace: false,
            }),
        );

        let manifest = test_manifest(deps);
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("serde = { version = \"1.0\", features = [\"derive\"] }"));
        assert!(content.contains("tokio = \"1.0\""));
    }

    #[test]
    fn generate_skips_pypi_deps() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "numpy".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some(">=1.24".to_string()),
                source: Some(DepSource::PyPI),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
                apt: None,
                cmake_package: None,
                lang: None,
                workspace: false,
            }),
        );
        deps.insert(
            "serde".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some("1.0".to_string()),
                source: Some(DepSource::CratesIo),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
                apt: None,
                cmake_package: None,
                lang: None,
                workspace: false,
            }),
        );

        let manifest = test_manifest(deps);
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        // PyPI dep should not appear
        assert!(!content.contains("numpy"));
        // Crates.io dep should appear
        assert!(content.contains("serde = \"1.0\""));
    }

    #[test]
    fn generate_with_git_dep() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "my-fork".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: None,
                source: Some(DepSource::Git),
                features: vec![],
                optional: false,
                path: None,
                git: Some("https://github.com/org/repo".to_string()),
                branch: Some("main".to_string()),
                tag: None,
                rev: None,
                apt: None,
                cmake_package: None,
                lang: None,
                workspace: false,
            }),
        );

        let manifest = test_manifest(deps);
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content
            .contains("my-fork = { git = \"https://github.com/org/repo\", branch = \"main\" }"));
    }

    #[test]
    fn generate_multiple_bin_entries() {
        let dir = tempfile::tempdir().unwrap();
        let f1 = dir.path().join("node1.rs");
        let f2 = dir.path().join("node2.rs");
        fs::write(&f1, "fn main() {}").unwrap();
        fs::write(&f2, "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let (result, _) = generate(&manifest, dir.path(), &[f1, f2], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("name = \"node1\""));
        assert!(content.contains("name = \"node2\""));
        // Should have two [[bin]] entries
        assert_eq!(content.matches("[[bin]]").count(), 2);
    }

    #[test]
    fn generate_with_dev_deps() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut dev_deps = BTreeMap::new();
        dev_deps.insert(
            "criterion".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some("0.5".to_string()),
                source: Some(DepSource::CratesIo),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
                apt: None,
                cmake_package: None,
                lang: None,
                workspace: false,
            }),
        );

        let mut manifest = test_manifest(BTreeMap::new());
        manifest.dev_dependencies = dev_deps;

        // Without include_dev
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(&result).unwrap();
        assert!(!content.contains("[dev-dependencies]"));

        // With include_dev
        let (result, _) = generate(&manifest, dir.path(), &[], true).unwrap();
        let content = fs::read_to_string(result).unwrap();
        assert!(content.contains("[dev-dependencies]"));
        assert!(content.contains("criterion = \"0.5\""));
    }

    #[test]
    fn sanitize_cargo_name_works() {
        assert_eq!(sanitize_cargo_name("my-robot"), "my-robot");
        assert_eq!(sanitize_cargo_name("my_robot"), "my_robot");
        assert_eq!(sanitize_cargo_name("my@robot/v2"), "my_robot_v2");
    }

    #[test]
    fn relative_path_computation() {
        let horus = PathBuf::from("/home/user/project/.horus");
        let file = PathBuf::from("/home/user/project/main.rs");
        let rel = pathdiff(&file, &horus).unwrap();
        assert_eq!(rel, "../main.rs");
    }

    // ── Battle tests ────────────────────────────────────────────────────────

    /// Helper to build a detailed dep with explicit source.
    fn detailed(
        source: DepSource,
        version: Option<&str>,
        features: &[&str],
        optional: bool,
    ) -> DependencyValue {
        DependencyValue::Detailed(DetailedDependency {
            version: version.map(|v| v.to_string()),
            source: Some(source),
            features: features.iter().map(|s| s.to_string()).collect(),
            optional,
            path: None,
            git: None,
            branch: None,
            tag: None,
            rev: None,
            apt: None,
            cmake_package: None,
            lang: None,
            workspace: false,
        })
    }

    fn git_dep(
        url: &str,
        branch: Option<&str>,
        tag: Option<&str>,
        rev: Option<&str>,
    ) -> DependencyValue {
        DependencyValue::Detailed(DetailedDependency {
            version: None,
            source: Some(DepSource::Git),
            features: vec![],
            optional: false,
            path: None,
            git: Some(url.to_string()),
            branch: branch.map(|s| s.to_string()),
            tag: tag.map(|s| s.to_string()),
            rev: rev.map(|s| s.to_string()),
            apt: None,
            cmake_package: None,
            lang: None,
            workspace: false,
        })
    }

    fn path_dep(p: &str) -> DependencyValue {
        DependencyValue::Detailed(DetailedDependency {
            version: None,
            source: Some(DepSource::Path),
            features: vec![],
            optional: false,
            path: Some(p.to_string()),
            git: None,
            branch: None,
            tag: None,
            rev: None,
            apt: None,
            cmake_package: None,
            lang: None,
            workspace: false,
        })
    }

    #[test]
    fn battle_mixed_deps_filters_correctly() {
        // Mix of crates.io, pypi, git, path, system — only Rust-relevant ones survive
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "serde".into(),
            detailed(DepSource::CratesIo, Some("1.0"), &[], false),
        );
        deps.insert(
            "numpy".into(),
            detailed(DepSource::PyPI, Some(">=1.24"), &[], false),
        );
        deps.insert(
            "libz-sys".into(),
            detailed(DepSource::System, Some("1.0"), &[], false),
        );
        deps.insert(
            "my-fork".into(),
            git_dep("https://github.com/org/repo", Some("dev"), None, None),
        );

        // Create path dep directory so relative path resolves
        let lib_dir = dir.path().join("libs/mylib");
        fs::create_dir_all(&lib_dir).unwrap();
        deps.insert("mylib".into(), path_dep("libs/mylib"));

        let manifest = test_manifest(deps);
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        // crates.io dep present
        assert!(content.contains("serde = \"1.0\""), "crates.io dep missing");
        // git dep present
        assert!(
            content
                .contains("my-fork = { git = \"https://github.com/org/repo\", branch = \"dev\" }"),
            "git dep missing"
        );
        // path dep present
        assert!(content.contains("mylib = { path ="), "path dep missing");
        // pypi dep filtered out
        assert!(!content.contains("numpy"), "pypi dep should be filtered");
        // system dep filtered out
        assert!(
            !content.contains("libz-sys"),
            "system dep should be filtered"
        );
    }

    #[test]
    fn battle_driver_features_propagation_camera_lidar() {
        // Drivers with camera + lidar should propagate features to horus/horus_library path deps.
        // We can't test the actual write_horus_path_deps without the horus source dir existing,
        // but we can test the hw_features extraction logic directly.
        let mut manifest = test_manifest(BTreeMap::new());
        manifest
            .drivers
            .insert("camera".into(), DriverValue::Backend("opencv".into()));
        manifest
            .drivers
            .insert("lidar".into(), DriverValue::Backend("rplidar-a2".into()));
        manifest.drivers.insert(
            "custom_sensor".into(),
            DriverValue::Backend("custom".into()),
        );

        // Extract features using the same logic as write_horus_path_deps
        let hw_features: Vec<&str> = manifest
            .drivers
            .keys()
            .filter_map(|k| match k.as_str() {
                "camera" => Some("camera"),
                "lidar" => Some("lidar"),
                "imu" => Some("imu"),
                "gps" => Some("gps"),
                _ => None,
            })
            .collect();

        assert!(hw_features.contains(&"camera"), "camera feature missing");
        assert!(hw_features.contains(&"lidar"), "lidar feature missing");
        assert_eq!(
            hw_features.len(),
            2,
            "custom_sensor should not produce a feature"
        );
    }

    #[test]
    fn battle_driver_features_all_four() {
        let mut manifest = test_manifest(BTreeMap::new());
        manifest
            .drivers
            .insert("camera".into(), DriverValue::Backend("v4l2".into()));
        manifest
            .drivers
            .insert("lidar".into(), DriverValue::Backend("velodyne".into()));
        manifest
            .drivers
            .insert("imu".into(), DriverValue::Backend("bno055".into()));
        manifest
            .drivers
            .insert("gps".into(), DriverValue::Backend("ublox".into()));

        let hw_features: Vec<&str> = manifest
            .drivers
            .keys()
            .filter_map(|k| match k.as_str() {
                "camera" => Some("camera"),
                "lidar" => Some("lidar"),
                "imu" => Some("imu"),
                "gps" => Some("gps"),
                _ => None,
            })
            .collect();

        assert_eq!(hw_features.len(), 4);
    }

    #[test]
    fn battle_optional_dep_flag() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "serde_json".into(),
            detailed(DepSource::CratesIo, Some("1.0"), &[], true),
        );

        let manifest = test_manifest(deps);
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(
            content.contains("optional = true"),
            "optional flag missing: {}",
            content
        );
        assert!(content.contains("serde_json"), "dep name missing");
    }

    #[test]
    fn battle_optional_dep_with_features() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "tokio".into(),
            detailed(
                DepSource::CratesIo,
                Some("1.36"),
                &["rt", "macros", "net"],
                true,
            ),
        );

        let manifest = test_manifest(deps);
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("optional = true"), "optional missing");
        assert!(
            content.contains("features = [\"rt\", \"macros\", \"net\"]"),
            "features wrong: {}",
            content
        );
    }

    #[test]
    fn battle_dev_deps_gated_off() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut dev_deps = BTreeMap::new();
        dev_deps.insert(
            "proptest".into(),
            detailed(DepSource::CratesIo, Some("1.4"), &[], false),
        );
        dev_deps.insert(
            "insta".into(),
            detailed(DepSource::CratesIo, Some("1.0"), &["yaml"], false),
        );

        let mut manifest = test_manifest(BTreeMap::new());
        manifest.dev_dependencies = dev_deps;

        // include_dev = false: no [dev-dependencies] section
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();
        assert!(
            !content.contains("proptest"),
            "dev dep leaked when include_dev=false"
        );
        assert!(
            !content.contains("insta"),
            "dev dep leaked when include_dev=false"
        );
        assert!(!content.contains("[dev-dependencies]"), "section leaked");
    }

    #[test]
    fn battle_dev_deps_gated_on_with_features() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut dev_deps = BTreeMap::new();
        dev_deps.insert(
            "insta".into(),
            detailed(
                DepSource::CratesIo,
                Some("1.0"),
                &["yaml", "redactions"],
                false,
            ),
        );
        dev_deps.insert(
            "pytest-helper".into(),
            detailed(DepSource::PyPI, Some(">=3.0"), &[], false),
        );

        let mut manifest = test_manifest(BTreeMap::new());
        manifest.dev_dependencies = dev_deps;

        let (result, _) = generate(&manifest, dir.path(), &[], true).unwrap();
        let content = fs::read_to_string(result).unwrap();
        assert!(content.contains("[dev-dependencies]"), "section missing");
        assert!(
            content
                .contains("insta = { version = \"1.0\", features = [\"yaml\", \"redactions\"] }"),
            "dev dep wrong: {}",
            content
        );
        // PyPI dev dep filtered
        assert!(
            !content.contains("pytest-helper"),
            "pypi dev dep should be filtered"
        );
    }

    #[test]
    fn battle_workspace_isolation_present() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(
            content.contains("[workspace]"),
            "workspace section missing for isolation"
        );
        // Verify [workspace] comes after [package]
        let pkg_pos = content.find("[package]").unwrap();
        let ws_pos = content.find("[workspace]").unwrap();
        assert!(ws_pos > pkg_pos, "[workspace] should come after [package]");
    }

    #[test]
    fn battle_registry_dep_not_installed() {
        // Registry deps that haven't been installed yet get a comment
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "horus-nav".into(),
            DependencyValue::Simple("0.3.0".to_string()),
        );

        let manifest = test_manifest(deps);
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        // Simple version defaults to Registry source, package not installed → comment
        assert!(
            content.contains("# horus-nav = \"0.3.0\" (registry, not yet installed)"),
            "expected commented-out registry dep: {}",
            content
        );
    }

    #[test]
    fn battle_registry_dep_installed() {
        // Registry dep that has been installed (package dir exists)
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        // Create the installed package directory
        let pkg_dir = dir.path().join(".horus/packages/horus-nav");
        fs::create_dir_all(&pkg_dir).unwrap();
        fs::write(
            pkg_dir.join("Cargo.toml"),
            "[package]\nname = \"horus-nav\"",
        )
        .unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "horus-nav".into(),
            detailed(DepSource::Registry, Some("0.3.0"), &[], false),
        );

        let manifest = test_manifest(deps);
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(
            content.contains("horus-nav = { path = \"packages/horus-nav\" }"),
            "installed registry dep should be a path dep: {}",
            content
        );
    }

    #[test]
    fn battle_multiple_bin_entries_three_files() {
        let dir = tempfile::tempdir().unwrap();
        let f1 = dir.path().join("driver.rs");
        let f2 = dir.path().join("controller.rs");
        let f3 = dir.path().join("planner.rs");
        fs::write(&f1, "fn main() {}").unwrap();
        fs::write(&f2, "fn main() {}").unwrap();
        fs::write(&f3, "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let (result, _) = generate(&manifest, dir.path(), &[f1, f2, f3], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert_eq!(
            content.matches("[[bin]]").count(),
            3,
            "expected 3 [[bin]] entries"
        );
        assert!(content.contains("name = \"driver\""));
        assert!(content.contains("name = \"controller\""));
        assert!(content.contains("name = \"planner\""));
    }

    #[test]
    fn battle_single_source_file_uses_project_name() {
        let dir = tempfile::tempdir().unwrap();
        let f1 = dir.path().join("whatever.rs");
        fs::write(&f1, "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let (result, _) = generate(&manifest, dir.path(), &[f1], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        // Single file uses project name, not file stem
        assert!(
            content.contains("name = \"test-project\""),
            "single bin should use project name: {}",
            content
        );
        assert_eq!(content.matches("[[bin]]").count(), 1);
    }

    #[test]
    fn battle_git_dep_with_tag() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "bevy".into(),
            git_dep(
                "https://github.com/bevyengine/bevy",
                None,
                Some("v0.15.0"),
                None,
            ),
        );

        let manifest = test_manifest(deps);
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(
            content.contains(
                "bevy = { git = \"https://github.com/bevyengine/bevy\", tag = \"v0.15.0\" }"
            ),
            "git+tag dep wrong: {}",
            content
        );
    }

    #[test]
    fn battle_git_dep_with_rev() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "rapier".into(),
            git_dep(
                "https://github.com/dimforge/rapier",
                None,
                None,
                Some("abc123def"),
            ),
        );

        let manifest = test_manifest(deps);
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(
            content.contains(
                "rapier = { git = \"https://github.com/dimforge/rapier\", rev = \"abc123def\" }"
            ),
            "git+rev dep wrong: {}",
            content
        );
    }

    #[test]
    fn battle_sanitize_special_chars() {
        assert_eq!(sanitize_cargo_name("my robot v2"), "my_robot_v2");
        assert_eq!(sanitize_cargo_name("pkg@1.0/beta"), "pkg_1_0_beta");
        assert_eq!(sanitize_cargo_name("valid-name_ok"), "valid-name_ok");
        assert_eq!(sanitize_cargo_name(""), "");
        assert_eq!(sanitize_cargo_name("a!b#c$d%e"), "a_b_c_d_e");
    }

    #[test]
    fn battle_header_always_present() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(
            content.starts_with("# Generated by horus from horus.toml"),
            "missing generated header"
        );
    }

    #[test]
    fn battle_path_dep_relativizes_to_horus_dir() {
        // Path dep "../shared" from project root should become "../../shared" from .horus/
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        // Create sibling directory
        let shared_dir = dir.path().join("libs/shared");
        fs::create_dir_all(&shared_dir).unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("shared".into(), path_dep("libs/shared"));

        let manifest = test_manifest(deps);
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        // The path should be relative to .horus/, pointing back up
        assert!(
            content.contains("shared = { path ="),
            "path dep missing: {}",
            content
        );
        // It should contain ".." to go up from .horus/
        assert!(
            content.contains(".."),
            "path should be relative: {}",
            content
        );
    }

    #[test]
    fn battle_empty_deps_still_has_deps_section() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(
            content.contains("[dependencies]"),
            "should always have [dependencies] section"
        );
    }

    #[test]
    fn battle_crates_io_simple_version_string() {
        // Simple version string with explicit crates.io source
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "anyhow".into(),
            detailed(DepSource::CratesIo, Some("1.0.86"), &[], false),
        );
        deps.insert(
            "thiserror".into(),
            detailed(DepSource::CratesIo, Some("1.0"), &[], false),
        );

        let manifest = test_manifest(deps);
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(
            content.contains("anyhow = \"1.0.86\""),
            "simple version dep wrong: {}",
            content
        );
        assert!(
            content.contains("thiserror = \"1.0\""),
            "simple version dep wrong: {}",
            content
        );
    }

    #[test]
    fn battle_crates_io_wildcard_version() {
        // No version → "*"
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "rand".into(),
            detailed(DepSource::CratesIo, None, &[], false),
        );

        let manifest = test_manifest(deps);
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(
            content.contains("rand = \"*\""),
            "wildcard version wrong: {}",
            content
        );
    }

    #[test]
    fn battle_src_main_fallback() {
        // No source files provided but src/main.rs exists
        let dir = tempfile::tempdir().unwrap();
        let src_dir = dir.path().join("src");
        fs::create_dir_all(&src_dir).unwrap();
        fs::write(src_dir.join("main.rs"), "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(
            content.contains("[[bin]]"),
            "should have bin entry for src/main.rs"
        );
        assert!(
            content.contains("src/main.rs") || content.contains("main.rs"),
            "should reference main.rs: {}",
            content
        );
    }

    #[test]
    fn battle_no_main_rs_no_bin() {
        // No main.rs files at all — should not have [[bin]] entry
        let dir = tempfile::tempdir().unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(
            !content.contains("[[bin]]"),
            "should not have bin entry without main.rs: {}",
            content
        );
    }

    // ── Workspace generation tests ────────────────────────────────────────

    /// Helper: build a minimal HorusManifest without Default derive.
    fn empty_manifest() -> HorusManifest {
        HorusManifest {
            package: PackageInfo::default(),
            workspace: None,
            robot: None,
            dependencies: BTreeMap::new(),
            dev_dependencies: BTreeMap::new(),
            sim_dependencies: BTreeMap::new(),
            hardware: BTreeMap::new(),
            drivers: BTreeMap::new(),
            sim_drivers: BTreeMap::new(),
            scripts: BTreeMap::new(),
            ignore: IgnoreConfig::default(),
            enable: vec![],
            cpp: None,
            hooks: Default::default(),
            network: None,
        }
    }

    /// Helper: create a workspace root manifest + two member manifests for testing.
    ///
    /// Returns (root_manifest, members_vec, tempdir) where tempdir owns the
    /// filesystem lifetime. Caller must keep it alive.
    fn create_workspace_project() -> (
        HorusManifest,
        Vec<(PathBuf, HorusManifest)>,
        tempfile::TempDir,
    ) {
        let dir = tempfile::tempdir().unwrap();

        // Create directory structure:
        //   crates/messages/src/lib.rs
        //   crates/controller/src/main.rs
        let messages_dir = dir.path().join("crates/messages");
        let controller_dir = dir.path().join("crates/controller");
        fs::create_dir_all(messages_dir.join("src")).unwrap();
        fs::create_dir_all(controller_dir.join("src")).unwrap();
        fs::write(messages_dir.join("src/lib.rs"), "pub fn hello() {}").unwrap();
        fs::write(controller_dir.join("src/main.rs"), "fn main() {}").unwrap();

        // Root manifest — virtual workspace (empty package name)
        let root = HorusManifest {
            package: PackageInfo::default(), // name = "" → virtual workspace
            workspace: Some(WorkspaceConfig {
                members: vec!["crates/*".to_string()],
                exclude: vec![],
                dependencies: BTreeMap::from([(
                    "serde".to_string(),
                    DependencyValue::Simple("1.0".to_string()),
                )]),
            }),
            ..empty_manifest()
        };

        // Member: messages (lib)
        let messages = HorusManifest {
            package: PackageInfo {
                name: "my-messages".to_string(),
                version: "0.1.0".to_string(),
                target_type: TargetType::Lib,
                ..PackageInfo::default()
            },
            dependencies: BTreeMap::from([(
                "serde".to_string(),
                DependencyValue::Detailed(DetailedDependency {
                    workspace: true,
                    ..DetailedDependency::default()
                }),
            )]),
            ..empty_manifest()
        };

        // Member: controller (bin)
        let controller = HorusManifest {
            package: PackageInfo {
                name: "my-controller".to_string(),
                version: "0.2.0".to_string(),
                target_type: TargetType::Bin,
                ..PackageInfo::default()
            },
            dependencies: BTreeMap::new(),
            ..empty_manifest()
        };

        let members = vec![
            (PathBuf::from("crates/messages"), messages),
            (PathBuf::from("crates/controller"), controller),
        ];

        (root, members, dir)
    }

    // ── 1. Basic workspace generation ─────────────────────────────────────

    #[test]
    fn workspace_generate_root_cargo_toml() {
        let (root, members, dir) = create_workspace_project();
        let (path, content) = generate_workspace(&root, dir.path(), &members).unwrap();

        assert!(path.ends_with(".horus/Cargo.toml"), "wrong root path: {:?}", path);
        assert!(content.contains("[workspace]"), "missing [workspace]: {}", content);
        assert!(
            content.contains("resolver = \"2\""),
            "missing resolver = \"2\": {}",
            content
        );
        assert!(
            content.contains("\"my-messages\""),
            "missing my-messages member: {}",
            content
        );
        assert!(
            content.contains("\"my-controller\""),
            "missing my-controller member: {}",
            content
        );
        assert!(
            content.contains("[workspace.dependencies]"),
            "missing [workspace.dependencies]: {}",
            content
        );
        assert!(
            content.contains("serde = \"1.0\""),
            "missing serde workspace dep: {}",
            content
        );
    }

    #[test]
    fn workspace_generate_member_lib_cargo_toml() {
        let (root, members, dir) = create_workspace_project();
        generate_workspace(&root, dir.path(), &members).unwrap();

        let member_cargo_path = dir.path().join(".horus/my-messages/Cargo.toml");
        assert!(member_cargo_path.exists(), "member Cargo.toml not created");
        let content = fs::read_to_string(&member_cargo_path).unwrap();

        // [package] section
        assert!(
            content.contains("name = \"my-messages\""),
            "missing package name: {}",
            content
        );
        assert!(
            content.contains("version = \"0.1.0\""),
            "missing version: {}",
            content
        );

        // [lib] section with path back to source
        assert!(content.contains("[lib]"), "missing [lib] section: {}", content);
        assert!(
            content.contains("src/lib.rs"),
            "lib path should reference src/lib.rs: {}",
            content
        );

        // No [[bin]] section for a lib target
        assert!(
            !content.contains("[[bin]]"),
            "lib member should not have [[bin]]: {}",
            content
        );

        // workspace = true dep
        assert!(
            content.contains("serde.workspace = true"),
            "missing serde.workspace = true: {}",
            content
        );
    }

    #[test]
    fn workspace_generate_member_bin_cargo_toml() {
        let (root, members, dir) = create_workspace_project();
        generate_workspace(&root, dir.path(), &members).unwrap();

        let member_cargo_path = dir.path().join(".horus/my-controller/Cargo.toml");
        assert!(member_cargo_path.exists(), "member Cargo.toml not created");
        let content = fs::read_to_string(&member_cargo_path).unwrap();

        // [package] section
        assert!(
            content.contains("name = \"my-controller\""),
            "missing package name: {}",
            content
        );
        assert!(
            content.contains("version = \"0.2.0\""),
            "missing version: {}",
            content
        );

        // [[bin]] section with path back to source
        assert!(
            content.contains("[[bin]]"),
            "missing [[bin]] section: {}",
            content
        );
        assert!(
            content.contains("src/main.rs"),
            "bin path should reference src/main.rs: {}",
            content
        );

        // No [lib] section for a bin-only target
        assert!(
            !content.contains("[lib]"),
            "bin member should not have [lib]: {}",
            content
        );
    }

    #[test]
    fn workspace_generate_creates_directories() {
        let (root, members, dir) = create_workspace_project();
        generate_workspace(&root, dir.path(), &members).unwrap();

        assert!(
            dir.path().join(".horus").is_dir(),
            ".horus/ not created"
        );
        assert!(
            dir.path().join(".horus/my-messages").is_dir(),
            ".horus/my-messages/ not created"
        );
        assert!(
            dir.path().join(".horus/my-controller").is_dir(),
            ".horus/my-controller/ not created"
        );
    }

    // ── 5-7. Dependency handling ──────────────────────────────────────────

    #[test]
    fn workspace_generate_workspace_dep_inheritance() {
        let (root, members, dir) = create_workspace_project();
        generate_workspace(&root, dir.path(), &members).unwrap();

        // messages member has serde = { workspace = true }
        let content =
            fs::read_to_string(dir.path().join(".horus/my-messages/Cargo.toml")).unwrap();
        assert!(
            content.contains("serde.workspace = true"),
            "workspace dep inheritance missing: {}",
            content
        );
    }

    #[test]
    fn workspace_generate_workspace_dep_with_extra_features() {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(dir.path().join("crates/serde-user/src")).unwrap();
        fs::write(
            dir.path().join("crates/serde-user/src/lib.rs"),
            "pub fn f() {}",
        )
        .unwrap();

        let root = HorusManifest {
            workspace: Some(WorkspaceConfig {
                members: vec!["crates/*".to_string()],
                exclude: vec![],
                dependencies: BTreeMap::from([(
                    "serde".to_string(),
                    DependencyValue::Simple("1.0".to_string()),
                )]),
            }),
            ..empty_manifest()
        };

        let member = HorusManifest {
            package: PackageInfo {
                name: "serde-user".to_string(),
                version: "0.1.0".to_string(),
                target_type: TargetType::Lib,
                ..PackageInfo::default()
            },
            dependencies: BTreeMap::from([(
                "serde".to_string(),
                DependencyValue::Detailed(DetailedDependency {
                    workspace: true,
                    features: vec!["alloc".to_string()],
                    ..DetailedDependency::default()
                }),
            )]),
            ..empty_manifest()
        };

        let members = vec![(PathBuf::from("crates/serde-user"), member)];
        generate_workspace(&root, dir.path(), &members).unwrap();

        let content =
            fs::read_to_string(dir.path().join(".horus/serde-user/Cargo.toml")).unwrap();
        assert!(
            content.contains("serde = { workspace = true, features = [\"alloc\"] }"),
            "workspace dep with features wrong: {}",
            content
        );
    }

    #[test]
    fn workspace_generate_regular_dep() {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(dir.path().join("crates/rand-user/src")).unwrap();
        fs::write(
            dir.path().join("crates/rand-user/src/lib.rs"),
            "pub fn f() {}",
        )
        .unwrap();

        let root = HorusManifest {
            workspace: Some(WorkspaceConfig {
                members: vec!["crates/*".to_string()],
                exclude: vec![],
                dependencies: BTreeMap::new(),
            }),
            ..empty_manifest()
        };

        let member = HorusManifest {
            package: PackageInfo {
                name: "rand-user".to_string(),
                version: "0.1.0".to_string(),
                target_type: TargetType::Lib,
                ..PackageInfo::default()
            },
            dependencies: BTreeMap::from([(
                "rand".to_string(),
                detailed(DepSource::CratesIo, Some("0.8"), &[], false),
            )]),
            ..empty_manifest()
        };

        let members = vec![(PathBuf::from("crates/rand-user"), member)];
        generate_workspace(&root, dir.path(), &members).unwrap();

        let content =
            fs::read_to_string(dir.path().join(".horus/rand-user/Cargo.toml")).unwrap();
        assert!(
            content.contains("rand = \"0.8\""),
            "regular dep should appear directly: {}",
            content
        );
    }

    // ── 8. Inter-member path deps ─────────────────────────────────────────

    #[test]
    fn workspace_generate_inter_member_path_dep() {
        let dir = tempfile::tempdir().unwrap();

        // Create member directories
        fs::create_dir_all(dir.path().join("crates/messages/src")).unwrap();
        fs::create_dir_all(dir.path().join("crates/controller/src")).unwrap();
        fs::write(
            dir.path().join("crates/messages/src/lib.rs"),
            "pub fn msg() {}",
        )
        .unwrap();
        fs::write(
            dir.path().join("crates/controller/src/main.rs"),
            "fn main() {}",
        )
        .unwrap();

        let root = HorusManifest {
            workspace: Some(WorkspaceConfig {
                members: vec!["crates/*".to_string()],
                exclude: vec![],
                dependencies: BTreeMap::new(),
            }),
            ..empty_manifest()
        };

        let messages = HorusManifest {
            package: PackageInfo {
                name: "my-messages".to_string(),
                version: "0.1.0".to_string(),
                target_type: TargetType::Lib,
                ..PackageInfo::default()
            },
            ..empty_manifest()
        };

        // controller depends on messages via relative path
        let controller = HorusManifest {
            package: PackageInfo {
                name: "my-controller".to_string(),
                version: "0.2.0".to_string(),
                target_type: TargetType::Bin,
                ..PackageInfo::default()
            },
            dependencies: BTreeMap::from([(
                "my-messages".to_string(),
                DependencyValue::Detailed(DetailedDependency {
                    source: Some(DepSource::Path),
                    path: Some("../messages".to_string()),
                    ..DetailedDependency::default()
                }),
            )]),
            ..empty_manifest()
        };

        let members = vec![
            (PathBuf::from("crates/messages"), messages),
            (PathBuf::from("crates/controller"), controller),
        ];
        generate_workspace(&root, dir.path(), &members).unwrap();

        let content = fs::read_to_string(
            dir.path().join(".horus/my-controller/Cargo.toml"),
        )
        .unwrap();

        // The path dep should be rewritten to point to the sibling .horus/ dir
        assert!(
            content.contains("my-messages = { path ="),
            "inter-member path dep missing: {}",
            content
        );
        // Should point to ../my-messages (sibling within .horus/)
        assert!(
            content.contains("../my-messages"),
            "path dep should be rewritten to ../my-messages: {}",
            content
        );
    }

    // ── 9. Target type Both ───────────────────────────────────────────────

    #[test]
    fn workspace_generate_both_target() {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(dir.path().join("crates/hybrid/src")).unwrap();
        fs::write(
            dir.path().join("crates/hybrid/src/lib.rs"),
            "pub fn lib_fn() {}",
        )
        .unwrap();
        fs::write(
            dir.path().join("crates/hybrid/src/main.rs"),
            "fn main() {}",
        )
        .unwrap();

        let root = HorusManifest {
            workspace: Some(WorkspaceConfig {
                members: vec!["crates/*".to_string()],
                exclude: vec![],
                dependencies: BTreeMap::new(),
            }),
            ..empty_manifest()
        };

        let member = HorusManifest {
            package: PackageInfo {
                name: "hybrid".to_string(),
                version: "0.1.0".to_string(),
                target_type: TargetType::Both,
                ..PackageInfo::default()
            },
            ..empty_manifest()
        };

        let members = vec![(PathBuf::from("crates/hybrid"), member)];
        generate_workspace(&root, dir.path(), &members).unwrap();

        let content =
            fs::read_to_string(dir.path().join(".horus/hybrid/Cargo.toml")).unwrap();

        assert!(
            content.contains("[lib]"),
            "Both target should have [lib]: {}",
            content
        );
        assert!(
            content.contains("[[bin]]"),
            "Both target should have [[bin]]: {}",
            content
        );
        assert!(
            content.contains("src/lib.rs"),
            "lib path missing: {}",
            content
        );
        assert!(
            content.contains("src/main.rs"),
            "bin path missing: {}",
            content
        );
    }

    // ── 10-11. Dispatcher tests ───────────────────────────────────────────

    #[test]
    fn workspace_generate_for_manifest_dispatches_workspace() {
        let (root, _members, dir) = create_workspace_project();

        // Write horus.toml files so resolve_workspace_members can find them
        fs::write(
            dir.path().join("crates/messages/horus.toml"),
            "[package]\nname = \"my-messages\"\nversion = \"0.1.0\"\n\
             [package.target_type]\ntype = \"lib\"\n",
        )
        .unwrap();
        fs::write(
            dir.path().join("crates/controller/horus.toml"),
            "[package]\nname = \"my-controller\"\nversion = \"0.2.0\"\n",
        )
        .unwrap();

        let result = generate_for_manifest(&root, dir.path(), &[], false);
        // generate_for_manifest uses resolve_workspace_members which reads horus.toml
        // from disk — it may fail if the toml doesn't parse perfectly, but the key
        // thing to test is that it tries the workspace path (has [workspace] set).
        // If it succeeds, the output has [workspace]:
        if let Ok((_path, content)) = result {
            assert!(
                content.contains("[workspace]"),
                "dispatcher should produce workspace output: {}",
                content
            );
            assert!(
                !content.contains("members =\n") || content.contains("members = ["),
                "should have members list"
            );
        }
        // If resolve_workspace_members fails (e.g. glob issues in test env),
        // that's still correct dispatch — it tried the workspace path.
    }

    #[test]
    fn workspace_generate_for_manifest_dispatches_single() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        // Regular manifest — no workspace field
        let manifest = test_manifest(BTreeMap::new());
        let (_path, content) =
            generate_for_manifest(&manifest, dir.path(), &[], false).unwrap();

        assert!(
            content.contains("[package]"),
            "single dispatch should have [package]: {}",
            content
        );
        // Single-package generate() adds an empty [workspace] for isolation,
        // but should NOT have "members =" (that's workspace-mode only)
        assert!(
            !content.contains("members = ["),
            "single dispatch should not have workspace members: {}",
            content
        );
    }

    // ── 12-14. Battle tests ───────────────────────────────────────────────

    #[test]
    fn battle_workspace_generate_idempotent() {
        let (root, members, dir) = create_workspace_project();

        let (_path1, content1) = generate_workspace(&root, dir.path(), &members).unwrap();
        let (_path2, content2) = generate_workspace(&root, dir.path(), &members).unwrap();

        assert_eq!(
            content1, content2,
            "workspace generation should be idempotent"
        );

        // Also check member files are identical
        let m1 =
            fs::read_to_string(dir.path().join(".horus/my-messages/Cargo.toml")).unwrap();
        let m2 =
            fs::read_to_string(dir.path().join(".horus/my-messages/Cargo.toml")).unwrap();
        assert_eq!(m1, m2, "member Cargo.toml should be idempotent");
    }

    #[test]
    fn battle_workspace_single_member() {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(dir.path().join("crates/only/src")).unwrap();
        fs::write(
            dir.path().join("crates/only/src/main.rs"),
            "fn main() {}",
        )
        .unwrap();

        let root = HorusManifest {
            workspace: Some(WorkspaceConfig {
                members: vec!["crates/*".to_string()],
                exclude: vec![],
                dependencies: BTreeMap::new(),
            }),
            ..empty_manifest()
        };

        let member = HorusManifest {
            package: PackageInfo {
                name: "only".to_string(),
                version: "1.0.0".to_string(),
                target_type: TargetType::Bin,
                ..PackageInfo::default()
            },
            ..empty_manifest()
        };

        let members = vec![(PathBuf::from("crates/only"), member)];
        let (_path, content) = generate_workspace(&root, dir.path(), &members).unwrap();

        assert!(content.contains("[workspace]"), "missing [workspace]");
        assert!(
            content.contains("members = [\"only\"]"),
            "single member list wrong: {}",
            content
        );

        let member_path = dir.path().join(".horus/only/Cargo.toml");
        assert!(member_path.exists(), "single member Cargo.toml not created");
        let member_content = fs::read_to_string(&member_path).unwrap();
        assert!(
            member_content.contains("name = \"only\""),
            "member name wrong: {}",
            member_content
        );
    }

    #[test]
    fn battle_workspace_empty_deps() {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(dir.path().join("crates/bare/src")).unwrap();
        fs::write(
            dir.path().join("crates/bare/src/lib.rs"),
            "// empty lib",
        )
        .unwrap();

        let root = HorusManifest {
            workspace: Some(WorkspaceConfig {
                members: vec!["crates/*".to_string()],
                exclude: vec![],
                dependencies: BTreeMap::new(),
            }),
            ..empty_manifest()
        };

        let member = HorusManifest {
            package: PackageInfo {
                name: "bare".to_string(),
                version: "0.0.1".to_string(),
                target_type: TargetType::Lib,
                ..PackageInfo::default()
            },
            // No dependencies at all
            ..empty_manifest()
        };

        let members = vec![(PathBuf::from("crates/bare"), member)];
        let result = generate_workspace(&root, dir.path(), &members);
        assert!(result.is_ok(), "empty deps should not error: {:?}", result);

        let member_content =
            fs::read_to_string(dir.path().join(".horus/bare/Cargo.toml")).unwrap();
        assert!(
            member_content.contains("[dependencies]"),
            "should still have [dependencies] section: {}",
            member_content
        );
        assert!(
            member_content.contains("[package]"),
            "should still have [package] section: {}",
            member_content
        );
    }

    #[test]
    fn driver_crate_name_generates_crates_io_dep() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut manifest = test_manifest(BTreeMap::new());
        manifest.drivers.insert(
            "lidar".into(),
            DriverValue::Config(crate::manifest::DriverTableConfig {
                crate_name: Some("rplidar-driver".to_string()),
                ..Default::default()
            }),
        );

        let (result, _) = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(
            content.contains("rplidar-driver = \"*\""),
            "crate_name driver should produce crates.io dep: {}",
            content
        );
    }
}
