//! Generate `.horus/Cargo.toml` from `horus.toml` dependencies.
//!
//! This module is the bridge between the unified horus manifest and the Cargo
//! build system. It reads `[dependencies]` from `horus.toml`, filters for
//! Rust-relevant deps (crates.io, path, git, registry), and produces a
//! valid `Cargo.toml` inside `.horus/`.
//!
//! The generated file is always gitignored and treated as a build artifact.

use anyhow::{Context, Result};
use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::{Path, PathBuf};

use crate::manifest::{DepSource, DependencyValue, HorusManifest};

/// The `.horus` build directory name.
const HORUS_DIR: &str = ".horus";

/// Generate `.horus/Cargo.toml` from a `HorusManifest`.
///
/// - Filters crates.io, path, git, and registry deps from `[dependencies]`
/// - Adds horus_core/horus_library as path deps (found via `find_horus_source_dir`)
/// - Creates `[[bin]]` entries from source files
/// - Returns the path to the generated `Cargo.toml`
///
/// # Arguments
///
/// * `manifest` - The parsed horus.toml manifest
/// * `project_dir` - The project root directory (where horus.toml lives)
/// * `source_files` - List of .rs source files to create [[bin]] entries for
/// * `include_dev` - Whether to include dev-dependencies (for `horus test`)
pub fn generate(
    manifest: &HorusManifest,
    project_dir: &Path,
    source_files: &[PathBuf],
    include_dev: bool,
) -> Result<PathBuf> {
    let horus_dir = project_dir.join(HORUS_DIR);
    fs::create_dir_all(&horus_dir).context("Failed to create .horus directory")?;

    let project_name = &manifest.package.name;
    let version = &manifest.package.version;

    let mut cargo = String::with_capacity(2048);

    // ── Header ───────────────────────────────────────────────────────────
    writeln!(cargo, "# Generated by horus from horus.toml — do not edit manually").unwrap();
    writeln!(cargo, "[package]").unwrap();
    writeln!(cargo, "name = \"{}\"", sanitize_cargo_name(project_name)).unwrap();
    writeln!(cargo, "version = \"{}\"", version).unwrap();
    writeln!(cargo, "edition = \"2021\"").unwrap();
    writeln!(cargo).unwrap();

    // ── Workspace isolation ──────────────────────────────────────────────
    // Prevents inheriting a parent workspace
    writeln!(cargo, "[workspace]").unwrap();
    writeln!(cargo).unwrap();

    // ── Binary targets ───────────────────────────────────────────────────
    if source_files.is_empty() {
        // Default: look for main.rs in project root
        let main_rs = project_dir.join("main.rs");
        let src_main = project_dir.join("src/main.rs");
        if main_rs.exists() {
            write_bin_entry(&mut cargo, project_name, &relative_to_horus(&main_rs, &horus_dir));
        } else if src_main.exists() {
            write_bin_entry(&mut cargo, project_name, &relative_to_horus(&src_main, &horus_dir));
        }
    } else if source_files.len() == 1 {
        let rel = relative_to_horus(&source_files[0], &horus_dir);
        write_bin_entry(&mut cargo, project_name, &rel);
    } else {
        for file in source_files {
            let stem = file
                .file_stem()
                .map(|s| s.to_string_lossy().to_string())
                .unwrap_or_else(|| "main".to_string());
            let rel = relative_to_horus(file, &horus_dir);
            write_bin_entry(&mut cargo, &stem, &rel);
        }
    }

    // ── Dependencies ─────────────────────────────────────────────────────
    writeln!(cargo, "[dependencies]").unwrap();

    // Add horus core path deps
    if let Ok(horus_source) = crate::commands::run::find_horus_source_dir() {
        write_horus_path_deps(&mut cargo, &horus_source, manifest);
    }

    // Add user deps from horus.toml
    write_deps_section(&mut cargo, &manifest.dependencies, project_dir, &horus_dir)?;

    // ── Dev dependencies ─────────────────────────────────────────────────
    if include_dev && !manifest.dev_dependencies.is_empty() {
        writeln!(cargo).unwrap();
        writeln!(cargo, "[dev-dependencies]").unwrap();
        write_deps_section(&mut cargo, &manifest.dev_dependencies, project_dir, &horus_dir)?;
    }

    // ── Write file ───────────────────────────────────────────────────────
    let cargo_toml_path = horus_dir.join("Cargo.toml");
    fs::write(&cargo_toml_path, &cargo)
        .with_context(|| format!("Failed to write {}", cargo_toml_path.display()))?;

    Ok(cargo_toml_path)
}

/// Write a `[[bin]]` entry.
fn write_bin_entry(cargo: &mut String, name: &str, path: &str) {
    writeln!(cargo, "[[bin]]").unwrap();
    writeln!(cargo, "name = \"{}\"", sanitize_cargo_name(name)).unwrap();
    writeln!(cargo, "path = \"{}\"", path).unwrap();
    writeln!(cargo).unwrap();
}

/// Write horus core/library/macros path dependencies.
fn write_horus_path_deps(cargo: &mut String, horus_source: &Path, manifest: &HorusManifest) {
    // Detect hardware features from manifest
    let hw_features: Vec<&str> = manifest
        .drivers
        .keys()
        .filter_map(|k| match k.as_str() {
            "camera" => Some("camera"),
            "lidar" => Some("lidar"),
            "imu" => Some("imu"),
            "gps" => Some("gps"),
            _ => None,
        })
        .collect();

    for dep_name in &["horus", "horus_core", "horus_library", "horus_macros"] {
        let dep_path = horus_source.join(dep_name);
        if dep_path.exists() && dep_path.join("Cargo.toml").exists() {
            if (*dep_name == "horus" || *dep_name == "horus_library") && !hw_features.is_empty() {
                writeln!(
                    cargo,
                    "{} = {{ path = \"{}\", features = [{}] }}",
                    dep_name,
                    dep_path.display(),
                    hw_features
                        .iter()
                        .map(|f| format!("\"{}\"", f))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
                .unwrap();
            } else {
                writeln!(
                    cargo,
                    "{} = {{ path = \"{}\" }}",
                    dep_name,
                    dep_path.display()
                )
                .unwrap();
            }
        }
    }
}

/// Write dependencies from a BTreeMap to Cargo.toml format.
///
/// Filters for Rust-compatible deps: crates.io, path, git.
/// Registry deps are resolved to path deps pointing to .horus/packages/.
/// PyPI and System deps are skipped (not relevant for Cargo).
fn write_deps_section(
    cargo: &mut String,
    deps: &std::collections::BTreeMap<String, DependencyValue>,
    project_dir: &Path,
    horus_dir: &Path,
) -> Result<()> {
    for (name, dep) in deps {
        match dep.effective_source() {
            DepSource::CratesIo => {
                write_crates_io_dep(cargo, name, dep);
            }
            DepSource::Path => {
                if let DependencyValue::Detailed(d) = dep {
                    if let Some(ref p) = d.path {
                        // Resolve path relative to project dir, then make relative to .horus/
                        let abs_path = project_dir.join(p);
                        let rel = relative_to_horus(&abs_path, horus_dir);
                        writeln!(cargo, "{} = {{ path = \"{}\" }}", name, rel).unwrap();
                    }
                }
            }
            DepSource::Git => {
                if let DependencyValue::Detailed(d) = dep {
                    write_git_dep(cargo, name, d);
                }
            }
            DepSource::Registry => {
                // Registry packages are installed to .horus/packages/<name>/
                // If the package dir exists, add as path dep
                let pkg_dir = horus_dir.join("packages").join(name);
                if pkg_dir.exists() && pkg_dir.join("Cargo.toml").exists() {
                    writeln!(cargo, "{} = {{ path = \"packages/{}\" }}", name, name).unwrap();
                } else {
                    writeln!(cargo, "# {} = \"{}\" (registry, not yet installed)", name,
                        dep.version().unwrap_or("*")).unwrap();
                }
            }
            DepSource::PyPI | DepSource::System => {
                // Not Cargo deps — skip silently
            }
        }
    }
    Ok(())
}

/// Write a crates.io dependency line.
fn write_crates_io_dep(cargo: &mut String, name: &str, dep: &DependencyValue) {
    match dep {
        DependencyValue::Simple(v) => {
            writeln!(cargo, "{} = \"{}\"", name, v).unwrap();
        }
        DependencyValue::Detailed(d) => {
            let version = d.version.as_deref().unwrap_or("*");
            if d.features.is_empty() && !d.optional {
                writeln!(cargo, "{} = \"{}\"", name, version).unwrap();
            } else {
                let mut parts = vec![format!("version = \"{}\"", version)];
                if !d.features.is_empty() {
                    let feats = d
                        .features
                        .iter()
                        .map(|f| format!("\"{}\"", f))
                        .collect::<Vec<_>>()
                        .join(", ");
                    parts.push(format!("features = [{}]", feats));
                }
                if d.optional {
                    parts.push("optional = true".to_string());
                }
                writeln!(cargo, "{} = {{ {} }}", name, parts.join(", ")).unwrap();
            }
        }
    }
}

/// Write a git dependency line.
fn write_git_dep(cargo: &mut String, name: &str, d: &crate::manifest::DetailedDependency) {
    let git_url = d.git.as_deref().unwrap_or("");
    let mut parts = vec![format!("git = \"{}\"", git_url)];
    if let Some(ref branch) = d.branch {
        parts.push(format!("branch = \"{}\"", branch));
    }
    if let Some(ref tag) = d.tag {
        parts.push(format!("tag = \"{}\"", tag));
    }
    if let Some(ref rev) = d.rev {
        parts.push(format!("rev = \"{}\"", rev));
    }
    writeln!(cargo, "{} = {{ {} }}", name, parts.join(", ")).unwrap();
}

/// Compute a relative path from `.horus/` to a file.
///
/// e.g., `/home/user/project/main.rs` from `/home/user/project/.horus/`
/// → `../main.rs`
fn relative_to_horus(file: &Path, horus_dir: &Path) -> String {
    // Try to compute relative path
    if let Ok(rel) = pathdiff(file, horus_dir) {
        rel
    } else {
        // Fallback to absolute
        file.to_string_lossy().to_string()
    }
}

/// Simple relative path computation (from -> to).
fn pathdiff(target: &Path, base: &Path) -> Result<String, ()> {
    // Canonicalize if possible, otherwise use as-is
    let target = target.canonicalize().unwrap_or_else(|_| target.to_path_buf());
    let base = base.canonicalize().unwrap_or_else(|_| base.to_path_buf());

    let mut target_parts: Vec<_> = target.components().collect();
    let mut base_parts: Vec<_> = base.components().collect();

    // Remove common prefix
    while !target_parts.is_empty()
        && !base_parts.is_empty()
        && target_parts[0] == base_parts[0]
    {
        target_parts.remove(0);
        base_parts.remove(0);
    }

    // Go up for remaining base parts, then down for target parts
    let mut result = String::new();
    for _ in &base_parts {
        if !result.is_empty() {
            result.push('/');
        }
        result.push_str("..");
    }
    for part in &target_parts {
        if !result.is_empty() {
            result.push('/');
        }
        result.push_str(&part.as_os_str().to_string_lossy());
    }

    if result.is_empty() {
        result.push('.');
    }

    Ok(result)
}

/// Sanitize a name for use as a Cargo package/bin name.
///
/// Replaces characters that are invalid in Cargo names with underscores.
pub fn sanitize_cargo_name(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' || c == '-' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::*;
    use std::collections::BTreeMap;

    fn test_manifest(deps: BTreeMap<String, DependencyValue>) -> HorusManifest {
        HorusManifest {
            package: PackageInfo {
                name: "test-project".to_string(),
                version: "0.1.0".to_string(),
                description: None,
                authors: vec![],
                license: None,
                edition: "1".to_string(),
                repository: None,
                package_type: None,
                categories: vec![],
            },
            dependencies: deps,
            dev_dependencies: BTreeMap::new(),
            drivers: BTreeMap::new(),
            scripts: BTreeMap::new(),
            ignore: IgnoreConfig::default(),
            enable: vec![],
        }
    }

    #[test]
    fn generate_minimal_cargo_toml() {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(dir.path().join(".horus")).unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), &[], false);
        assert!(result.is_ok());

        let cargo_path = result.unwrap();
        let content = fs::read_to_string(&cargo_path).unwrap();
        assert!(content.contains("name = \"test-project\""));
        assert!(content.contains("edition = \"2021\""));
        assert!(content.contains("[workspace]"));
        assert!(content.contains("[[bin]]"));
        assert!(content.contains("../main.rs"));
    }

    #[test]
    fn generate_with_crates_io_deps() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "serde".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some("1.0".to_string()),
                source: Some(DepSource::CratesIo),
                features: vec!["derive".to_string()],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );
        deps.insert(
            "tokio".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some("1.0".to_string()),
                source: Some(DepSource::CratesIo),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("serde = { version = \"1.0\", features = [\"derive\"] }"));
        assert!(content.contains("tokio = \"1.0\""));
    }

    #[test]
    fn generate_skips_pypi_deps() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "numpy".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some(">=1.24".to_string()),
                source: Some(DepSource::PyPI),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );
        deps.insert(
            "serde".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some("1.0".to_string()),
                source: Some(DepSource::CratesIo),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        // PyPI dep should not appear
        assert!(!content.contains("numpy"));
        // Crates.io dep should appear
        assert!(content.contains("serde = \"1.0\""));
    }

    #[test]
    fn generate_with_git_dep() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "my-fork".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: None,
                source: Some(DepSource::Git),
                features: vec![],
                optional: false,
                path: None,
                git: Some("https://github.com/org/repo".to_string()),
                branch: Some("main".to_string()),
                tag: None,
                rev: None,
            }),
        );

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("my-fork = { git = \"https://github.com/org/repo\", branch = \"main\" }"));
    }

    #[test]
    fn generate_multiple_bin_entries() {
        let dir = tempfile::tempdir().unwrap();
        let f1 = dir.path().join("node1.rs");
        let f2 = dir.path().join("node2.rs");
        fs::write(&f1, "fn main() {}").unwrap();
        fs::write(&f2, "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), &[f1, f2], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("name = \"node1\""));
        assert!(content.contains("name = \"node2\""));
        // Should have two [[bin]] entries
        assert_eq!(content.matches("[[bin]]").count(), 2);
    }

    #[test]
    fn generate_with_dev_deps() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut dev_deps = BTreeMap::new();
        dev_deps.insert(
            "criterion".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some("0.5".to_string()),
                source: Some(DepSource::CratesIo),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );

        let mut manifest = test_manifest(BTreeMap::new());
        manifest.dev_dependencies = dev_deps;

        // Without include_dev
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(&result).unwrap();
        assert!(!content.contains("[dev-dependencies]"));

        // With include_dev
        let result = generate(&manifest, dir.path(), &[], true).unwrap();
        let content = fs::read_to_string(result).unwrap();
        assert!(content.contains("[dev-dependencies]"));
        assert!(content.contains("criterion = \"0.5\""));
    }

    #[test]
    fn sanitize_cargo_name_works() {
        assert_eq!(sanitize_cargo_name("my-robot"), "my-robot");
        assert_eq!(sanitize_cargo_name("my_robot"), "my_robot");
        assert_eq!(sanitize_cargo_name("my@robot/v2"), "my_robot_v2");
    }

    #[test]
    fn relative_path_computation() {
        let horus = PathBuf::from("/home/user/project/.horus");
        let file = PathBuf::from("/home/user/project/main.rs");
        let rel = pathdiff(&file, &horus).unwrap();
        assert_eq!(rel, "../main.rs");
    }
}
