//! Generate `.horus/Cargo.toml` from `horus.toml` dependencies.
//!
//! This module is the bridge between the unified horus manifest and the Cargo
//! build system. It reads `[dependencies]` from `horus.toml`, filters for
//! Rust-relevant deps (crates.io, path, git, registry), and produces a
//! valid `Cargo.toml` inside `.horus/`.
//!
//! The generated file is always gitignored and treated as a build artifact.

use anyhow::{Context, Result};
use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::{Path, PathBuf};

use crate::manifest::{DepSource, DependencyValue, HorusManifest};

/// The `.horus` build directory name.
const HORUS_DIR: &str = ".horus";

/// Generate `.horus/Cargo.toml` from a `HorusManifest`.
///
/// - Filters crates.io, path, git, and registry deps from `[dependencies]`
/// - Adds horus_core/horus_library as path deps (found via `find_horus_source_dir`)
/// - Creates `[[bin]]` entries from source files
/// - Returns the path to the generated `Cargo.toml`
///
/// # Arguments
///
/// * `manifest` - The parsed horus.toml manifest
/// * `project_dir` - The project root directory (where horus.toml lives)
/// * `source_files` - List of .rs source files to create [[bin]] entries for
/// * `include_dev` - Whether to include dev-dependencies (for `horus test`)
pub fn generate(
    manifest: &HorusManifest,
    project_dir: &Path,
    source_files: &[PathBuf],
    include_dev: bool,
) -> Result<PathBuf> {
    let horus_dir = project_dir.join(HORUS_DIR);
    fs::create_dir_all(&horus_dir).context("Failed to create .horus directory")?;

    let project_name = &manifest.package.name;
    let version = &manifest.package.version;

    let mut cargo = String::with_capacity(2048);

    // ── Header ───────────────────────────────────────────────────────────
    writeln!(cargo, "# Generated by horus from horus.toml — do not edit manually").unwrap();
    writeln!(cargo, "[package]").unwrap();
    writeln!(cargo, "name = \"{}\"", sanitize_cargo_name(project_name)).unwrap();
    writeln!(cargo, "version = \"{}\"", version).unwrap();
    writeln!(cargo, "edition = \"2021\"").unwrap();
    writeln!(cargo).unwrap();

    // ── Workspace isolation ──────────────────────────────────────────────
    // Prevents inheriting a parent workspace
    writeln!(cargo, "[workspace]").unwrap();
    writeln!(cargo).unwrap();

    // ── Binary targets ───────────────────────────────────────────────────
    if source_files.is_empty() {
        // Default: look for main.rs in project root
        let main_rs = project_dir.join("main.rs");
        let src_main = project_dir.join("src/main.rs");
        if main_rs.exists() {
            write_bin_entry(&mut cargo, project_name, &relative_to_horus(&main_rs, &horus_dir));
        } else if src_main.exists() {
            write_bin_entry(&mut cargo, project_name, &relative_to_horus(&src_main, &horus_dir));
        }
    } else if source_files.len() == 1 {
        let rel = relative_to_horus(&source_files[0], &horus_dir);
        write_bin_entry(&mut cargo, project_name, &rel);
    } else {
        for file in source_files {
            let stem = file
                .file_stem()
                .map(|s| s.to_string_lossy().to_string())
                .unwrap_or_else(|| "main".to_string());
            let rel = relative_to_horus(file, &horus_dir);
            write_bin_entry(&mut cargo, &stem, &rel);
        }
    }

    // ── Dependencies ─────────────────────────────────────────────────────
    writeln!(cargo, "[dependencies]").unwrap();

    // Add horus core path deps
    if let Ok(horus_source) = crate::commands::run::find_horus_source_dir() {
        write_horus_path_deps(&mut cargo, &horus_source, manifest);
    }

    // Add user deps from horus.toml
    write_deps_section(&mut cargo, &manifest.dependencies, project_dir, &horus_dir)?;

    // ── Dev dependencies ─────────────────────────────────────────────────
    if include_dev && !manifest.dev_dependencies.is_empty() {
        writeln!(cargo).unwrap();
        writeln!(cargo, "[dev-dependencies]").unwrap();
        write_deps_section(&mut cargo, &manifest.dev_dependencies, project_dir, &horus_dir)?;
    }

    // ── Write file ───────────────────────────────────────────────────────
    let cargo_toml_path = horus_dir.join("Cargo.toml");
    fs::write(&cargo_toml_path, &cargo)
        .with_context(|| format!("Failed to write {}", cargo_toml_path.display()))?;

    Ok(cargo_toml_path)
}

/// Write a `[[bin]]` entry.
fn write_bin_entry(cargo: &mut String, name: &str, path: &str) {
    writeln!(cargo, "[[bin]]").unwrap();
    writeln!(cargo, "name = \"{}\"", sanitize_cargo_name(name)).unwrap();
    writeln!(cargo, "path = \"{}\"", path).unwrap();
    writeln!(cargo).unwrap();
}

/// Write horus core/library/macros path dependencies.
fn write_horus_path_deps(cargo: &mut String, horus_source: &Path, manifest: &HorusManifest) {
    // Detect hardware features from manifest
    let hw_features: Vec<&str> = manifest
        .drivers
        .keys()
        .filter_map(|k| match k.as_str() {
            "camera" => Some("camera"),
            "lidar" => Some("lidar"),
            "imu" => Some("imu"),
            "gps" => Some("gps"),
            _ => None,
        })
        .collect();

    for dep_name in &["horus", "horus_core", "horus_library", "horus_macros"] {
        let dep_path = horus_source.join(dep_name);
        if dep_path.exists() && dep_path.join("Cargo.toml").exists() {
            if (*dep_name == "horus" || *dep_name == "horus_library") && !hw_features.is_empty() {
                writeln!(
                    cargo,
                    "{} = {{ path = \"{}\", features = [{}] }}",
                    dep_name,
                    dep_path.display(),
                    hw_features
                        .iter()
                        .map(|f| format!("\"{}\"", f))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
                .unwrap();
            } else {
                writeln!(
                    cargo,
                    "{} = {{ path = \"{}\" }}",
                    dep_name,
                    dep_path.display()
                )
                .unwrap();
            }
        }
    }
}

/// Write dependencies from a BTreeMap to Cargo.toml format.
///
/// Filters for Rust-compatible deps: crates.io, path, git.
/// Registry deps are resolved to path deps pointing to .horus/packages/.
/// PyPI and System deps are skipped (not relevant for Cargo).
fn write_deps_section(
    cargo: &mut String,
    deps: &std::collections::BTreeMap<String, DependencyValue>,
    project_dir: &Path,
    horus_dir: &Path,
) -> Result<()> {
    for (name, dep) in deps {
        match dep.effective_source() {
            DepSource::CratesIo => {
                write_crates_io_dep(cargo, name, dep);
            }
            DepSource::Path => {
                if let DependencyValue::Detailed(d) = dep {
                    if let Some(ref p) = d.path {
                        // Resolve path relative to project dir, then make relative to .horus/
                        let abs_path = project_dir.join(p);
                        let rel = relative_to_horus(&abs_path, horus_dir);
                        writeln!(cargo, "{} = {{ path = \"{}\" }}", name, rel).unwrap();
                    }
                }
            }
            DepSource::Git => {
                if let DependencyValue::Detailed(d) = dep {
                    write_git_dep(cargo, name, d);
                }
            }
            DepSource::Registry => {
                // Registry packages are installed to .horus/packages/<name>/
                // If the package dir exists, add as path dep
                let pkg_dir = horus_dir.join("packages").join(name);
                if pkg_dir.exists() && pkg_dir.join("Cargo.toml").exists() {
                    writeln!(cargo, "{} = {{ path = \"packages/{}\" }}", name, name).unwrap();
                } else {
                    writeln!(cargo, "# {} = \"{}\" (registry, not yet installed)", name,
                        dep.version().unwrap_or("*")).unwrap();
                }
            }
            DepSource::PyPI | DepSource::System => {
                // Not Cargo deps — skip silently
            }
        }
    }
    Ok(())
}

/// Write a crates.io dependency line.
fn write_crates_io_dep(cargo: &mut String, name: &str, dep: &DependencyValue) {
    match dep {
        DependencyValue::Simple(v) => {
            writeln!(cargo, "{} = \"{}\"", name, v).unwrap();
        }
        DependencyValue::Detailed(d) => {
            let version = d.version.as_deref().unwrap_or("*");
            if d.features.is_empty() && !d.optional {
                writeln!(cargo, "{} = \"{}\"", name, version).unwrap();
            } else {
                let mut parts = vec![format!("version = \"{}\"", version)];
                if !d.features.is_empty() {
                    let feats = d
                        .features
                        .iter()
                        .map(|f| format!("\"{}\"", f))
                        .collect::<Vec<_>>()
                        .join(", ");
                    parts.push(format!("features = [{}]", feats));
                }
                if d.optional {
                    parts.push("optional = true".to_string());
                }
                writeln!(cargo, "{} = {{ {} }}", name, parts.join(", ")).unwrap();
            }
        }
    }
}

/// Write a git dependency line.
fn write_git_dep(cargo: &mut String, name: &str, d: &crate::manifest::DetailedDependency) {
    let git_url = d.git.as_deref().unwrap_or("");
    let mut parts = vec![format!("git = \"{}\"", git_url)];
    if let Some(ref branch) = d.branch {
        parts.push(format!("branch = \"{}\"", branch));
    }
    if let Some(ref tag) = d.tag {
        parts.push(format!("tag = \"{}\"", tag));
    }
    if let Some(ref rev) = d.rev {
        parts.push(format!("rev = \"{}\"", rev));
    }
    writeln!(cargo, "{} = {{ {} }}", name, parts.join(", ")).unwrap();
}

/// Compute a relative path from `.horus/` to a file.
///
/// e.g., `/home/user/project/main.rs` from `/home/user/project/.horus/`
/// → `../main.rs`
fn relative_to_horus(file: &Path, horus_dir: &Path) -> String {
    // Try to compute relative path
    if let Ok(rel) = pathdiff(file, horus_dir) {
        rel
    } else {
        // Fallback to absolute
        file.to_string_lossy().to_string()
    }
}

/// Simple relative path computation (from -> to).
fn pathdiff(target: &Path, base: &Path) -> Result<String, ()> {
    // Canonicalize if possible, otherwise use as-is
    let target = target.canonicalize().unwrap_or_else(|_| target.to_path_buf());
    let base = base.canonicalize().unwrap_or_else(|_| base.to_path_buf());

    let mut target_parts: Vec<_> = target.components().collect();
    let mut base_parts: Vec<_> = base.components().collect();

    // Remove common prefix
    while !target_parts.is_empty()
        && !base_parts.is_empty()
        && target_parts[0] == base_parts[0]
    {
        target_parts.remove(0);
        base_parts.remove(0);
    }

    // Go up for remaining base parts, then down for target parts
    let mut result = String::new();
    for _ in &base_parts {
        if !result.is_empty() {
            result.push('/');
        }
        result.push_str("..");
    }
    for part in &target_parts {
        if !result.is_empty() {
            result.push('/');
        }
        result.push_str(&part.as_os_str().to_string_lossy());
    }

    if result.is_empty() {
        result.push('.');
    }

    Ok(result)
}

/// Sanitize a name for use as a Cargo package/bin name.
///
/// Replaces characters that are invalid in Cargo names with underscores.
pub fn sanitize_cargo_name(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' || c == '-' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::*;
    use std::collections::BTreeMap;

    fn test_manifest(deps: BTreeMap<String, DependencyValue>) -> HorusManifest {
        HorusManifest {
            package: PackageInfo {
                name: "test-project".to_string(),
                version: "0.1.0".to_string(),
                description: None,
                authors: vec![],
                license: None,
                edition: "1".to_string(),
                repository: None,
                package_type: None,
                categories: vec![],
            },
            dependencies: deps,
            dev_dependencies: BTreeMap::new(),
            drivers: BTreeMap::new(),
            scripts: BTreeMap::new(),
            ignore: IgnoreConfig::default(),
            enable: vec![],
        }
    }

    #[test]
    fn generate_minimal_cargo_toml() {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(dir.path().join(".horus")).unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), &[], false);
        assert!(result.is_ok());

        let cargo_path = result.unwrap();
        let content = fs::read_to_string(&cargo_path).unwrap();
        assert!(content.contains("name = \"test-project\""));
        assert!(content.contains("edition = \"2021\""));
        assert!(content.contains("[workspace]"));
        assert!(content.contains("[[bin]]"));
        assert!(content.contains("../main.rs"));
    }

    #[test]
    fn generate_with_crates_io_deps() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "serde".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some("1.0".to_string()),
                source: Some(DepSource::CratesIo),
                features: vec!["derive".to_string()],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );
        deps.insert(
            "tokio".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some("1.0".to_string()),
                source: Some(DepSource::CratesIo),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("serde = { version = \"1.0\", features = [\"derive\"] }"));
        assert!(content.contains("tokio = \"1.0\""));
    }

    #[test]
    fn generate_skips_pypi_deps() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "numpy".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some(">=1.24".to_string()),
                source: Some(DepSource::PyPI),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );
        deps.insert(
            "serde".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some("1.0".to_string()),
                source: Some(DepSource::CratesIo),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        // PyPI dep should not appear
        assert!(!content.contains("numpy"));
        // Crates.io dep should appear
        assert!(content.contains("serde = \"1.0\""));
    }

    #[test]
    fn generate_with_git_dep() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "my-fork".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: None,
                source: Some(DepSource::Git),
                features: vec![],
                optional: false,
                path: None,
                git: Some("https://github.com/org/repo".to_string()),
                branch: Some("main".to_string()),
                tag: None,
                rev: None,
            }),
        );

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("my-fork = { git = \"https://github.com/org/repo\", branch = \"main\" }"));
    }

    #[test]
    fn generate_multiple_bin_entries() {
        let dir = tempfile::tempdir().unwrap();
        let f1 = dir.path().join("node1.rs");
        let f2 = dir.path().join("node2.rs");
        fs::write(&f1, "fn main() {}").unwrap();
        fs::write(&f2, "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), &[f1, f2], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("name = \"node1\""));
        assert!(content.contains("name = \"node2\""));
        // Should have two [[bin]] entries
        assert_eq!(content.matches("[[bin]]").count(), 2);
    }

    #[test]
    fn generate_with_dev_deps() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut dev_deps = BTreeMap::new();
        dev_deps.insert(
            "criterion".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some("0.5".to_string()),
                source: Some(DepSource::CratesIo),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );

        let mut manifest = test_manifest(BTreeMap::new());
        manifest.dev_dependencies = dev_deps;

        // Without include_dev
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(&result).unwrap();
        assert!(!content.contains("[dev-dependencies]"));

        // With include_dev
        let result = generate(&manifest, dir.path(), &[], true).unwrap();
        let content = fs::read_to_string(result).unwrap();
        assert!(content.contains("[dev-dependencies]"));
        assert!(content.contains("criterion = \"0.5\""));
    }

    #[test]
    fn sanitize_cargo_name_works() {
        assert_eq!(sanitize_cargo_name("my-robot"), "my-robot");
        assert_eq!(sanitize_cargo_name("my_robot"), "my_robot");
        assert_eq!(sanitize_cargo_name("my@robot/v2"), "my_robot_v2");
    }

    #[test]
    fn relative_path_computation() {
        let horus = PathBuf::from("/home/user/project/.horus");
        let file = PathBuf::from("/home/user/project/main.rs");
        let rel = pathdiff(&file, &horus).unwrap();
        assert_eq!(rel, "../main.rs");
    }

    // ── Battle tests ────────────────────────────────────────────────────────

    /// Helper to build a detailed dep with explicit source.
    fn detailed(
        source: DepSource,
        version: Option<&str>,
        features: &[&str],
        optional: bool,
    ) -> DependencyValue {
        DependencyValue::Detailed(DetailedDependency {
            version: version.map(|v| v.to_string()),
            source: Some(source),
            features: features.iter().map(|s| s.to_string()).collect(),
            optional,
            path: None,
            git: None,
            branch: None,
            tag: None,
            rev: None,
        })
    }

    fn git_dep(url: &str, branch: Option<&str>, tag: Option<&str>, rev: Option<&str>) -> DependencyValue {
        DependencyValue::Detailed(DetailedDependency {
            version: None,
            source: Some(DepSource::Git),
            features: vec![],
            optional: false,
            path: None,
            git: Some(url.to_string()),
            branch: branch.map(|s| s.to_string()),
            tag: tag.map(|s| s.to_string()),
            rev: rev.map(|s| s.to_string()),
        })
    }

    fn path_dep(p: &str) -> DependencyValue {
        DependencyValue::Detailed(DetailedDependency {
            version: None,
            source: Some(DepSource::Path),
            features: vec![],
            optional: false,
            path: Some(p.to_string()),
            git: None,
            branch: None,
            tag: None,
            rev: None,
        })
    }

    #[test]
    fn battle_mixed_deps_filters_correctly() {
        // Mix of crates.io, pypi, git, path, system — only Rust-relevant ones survive
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("serde".into(), detailed(DepSource::CratesIo, Some("1.0"), &[], false));
        deps.insert("numpy".into(), detailed(DepSource::PyPI, Some(">=1.24"), &[], false));
        deps.insert("libz-sys".into(), detailed(DepSource::System, Some("1.0"), &[], false));
        deps.insert("my-fork".into(), git_dep("https://github.com/org/repo", Some("dev"), None, None));

        // Create path dep directory so relative path resolves
        let lib_dir = dir.path().join("libs/mylib");
        fs::create_dir_all(&lib_dir).unwrap();
        deps.insert("mylib".into(), path_dep("libs/mylib"));

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        // crates.io dep present
        assert!(content.contains("serde = \"1.0\""), "crates.io dep missing");
        // git dep present
        assert!(content.contains("my-fork = { git = \"https://github.com/org/repo\", branch = \"dev\" }"),
            "git dep missing");
        // path dep present
        assert!(content.contains("mylib = { path ="), "path dep missing");
        // pypi dep filtered out
        assert!(!content.contains("numpy"), "pypi dep should be filtered");
        // system dep filtered out
        assert!(!content.contains("libz-sys"), "system dep should be filtered");
    }

    #[test]
    fn battle_driver_features_propagation_camera_lidar() {
        // Drivers with camera + lidar should propagate features to horus/horus_library path deps.
        // We can't test the actual write_horus_path_deps without the horus source dir existing,
        // but we can test the hw_features extraction logic directly.
        let mut manifest = test_manifest(BTreeMap::new());
        manifest.drivers.insert("camera".into(), DriverValue::Backend("opencv".into()));
        manifest.drivers.insert("lidar".into(), DriverValue::Backend("rplidar-a2".into()));
        manifest.drivers.insert("custom_sensor".into(), DriverValue::Backend("custom".into()));

        // Extract features using the same logic as write_horus_path_deps
        let hw_features: Vec<&str> = manifest
            .drivers
            .keys()
            .filter_map(|k| match k.as_str() {
                "camera" => Some("camera"),
                "lidar" => Some("lidar"),
                "imu" => Some("imu"),
                "gps" => Some("gps"),
                _ => None,
            })
            .collect();

        assert!(hw_features.contains(&"camera"), "camera feature missing");
        assert!(hw_features.contains(&"lidar"), "lidar feature missing");
        assert_eq!(hw_features.len(), 2, "custom_sensor should not produce a feature");
    }

    #[test]
    fn battle_driver_features_all_four() {
        let mut manifest = test_manifest(BTreeMap::new());
        manifest.drivers.insert("camera".into(), DriverValue::Backend("v4l2".into()));
        manifest.drivers.insert("lidar".into(), DriverValue::Backend("velodyne".into()));
        manifest.drivers.insert("imu".into(), DriverValue::Backend("bno055".into()));
        manifest.drivers.insert("gps".into(), DriverValue::Backend("ublox".into()));

        let hw_features: Vec<&str> = manifest
            .drivers
            .keys()
            .filter_map(|k| match k.as_str() {
                "camera" => Some("camera"),
                "lidar" => Some("lidar"),
                "imu" => Some("imu"),
                "gps" => Some("gps"),
                _ => None,
            })
            .collect();

        assert_eq!(hw_features.len(), 4);
    }

    #[test]
    fn battle_optional_dep_flag() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("serde_json".into(), detailed(DepSource::CratesIo, Some("1.0"), &[], true));

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("optional = true"), "optional flag missing: {}", content);
        assert!(content.contains("serde_json"), "dep name missing");
    }

    #[test]
    fn battle_optional_dep_with_features() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("tokio".into(), detailed(DepSource::CratesIo, Some("1.36"), &["rt", "macros", "net"], true));

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("optional = true"), "optional missing");
        assert!(content.contains("features = [\"rt\", \"macros\", \"net\"]"),
            "features wrong: {}", content);
    }

    #[test]
    fn battle_dev_deps_gated_off() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut dev_deps = BTreeMap::new();
        dev_deps.insert("proptest".into(), detailed(DepSource::CratesIo, Some("1.4"), &[], false));
        dev_deps.insert("insta".into(), detailed(DepSource::CratesIo, Some("1.0"), &["yaml"], false));

        let mut manifest = test_manifest(BTreeMap::new());
        manifest.dev_dependencies = dev_deps;

        // include_dev = false: no [dev-dependencies] section
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();
        assert!(!content.contains("proptest"), "dev dep leaked when include_dev=false");
        assert!(!content.contains("insta"), "dev dep leaked when include_dev=false");
        assert!(!content.contains("[dev-dependencies]"), "section leaked");
    }

    #[test]
    fn battle_dev_deps_gated_on_with_features() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut dev_deps = BTreeMap::new();
        dev_deps.insert("insta".into(), detailed(DepSource::CratesIo, Some("1.0"), &["yaml", "redactions"], false));
        dev_deps.insert("pytest-helper".into(), detailed(DepSource::PyPI, Some(">=3.0"), &[], false));

        let mut manifest = test_manifest(BTreeMap::new());
        manifest.dev_dependencies = dev_deps;

        let result = generate(&manifest, dir.path(), &[], true).unwrap();
        let content = fs::read_to_string(result).unwrap();
        assert!(content.contains("[dev-dependencies]"), "section missing");
        assert!(content.contains("insta = { version = \"1.0\", features = [\"yaml\", \"redactions\"] }"),
            "dev dep wrong: {}", content);
        // PyPI dev dep filtered
        assert!(!content.contains("pytest-helper"), "pypi dev dep should be filtered");
    }

    #[test]
    fn battle_workspace_isolation_present() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("[workspace]"), "workspace section missing for isolation");
        // Verify [workspace] comes after [package]
        let pkg_pos = content.find("[package]").unwrap();
        let ws_pos = content.find("[workspace]").unwrap();
        assert!(ws_pos > pkg_pos, "[workspace] should come after [package]");
    }

    #[test]
    fn battle_registry_dep_not_installed() {
        // Registry deps that haven't been installed yet get a comment
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("horus-nav".into(), DependencyValue::Simple("0.3.0".to_string()));

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        // Simple version defaults to Registry source, package not installed → comment
        assert!(content.contains("# horus-nav = \"0.3.0\" (registry, not yet installed)"),
            "expected commented-out registry dep: {}", content);
    }

    #[test]
    fn battle_registry_dep_installed() {
        // Registry dep that has been installed (package dir exists)
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        // Create the installed package directory
        let pkg_dir = dir.path().join(".horus/packages/horus-nav");
        fs::create_dir_all(&pkg_dir).unwrap();
        fs::write(pkg_dir.join("Cargo.toml"), "[package]\nname = \"horus-nav\"").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("horus-nav".into(), detailed(DepSource::Registry, Some("0.3.0"), &[], false));

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("horus-nav = { path = \"packages/horus-nav\" }"),
            "installed registry dep should be a path dep: {}", content);
    }

    #[test]
    fn battle_multiple_bin_entries_three_files() {
        let dir = tempfile::tempdir().unwrap();
        let f1 = dir.path().join("driver.rs");
        let f2 = dir.path().join("controller.rs");
        let f3 = dir.path().join("planner.rs");
        fs::write(&f1, "fn main() {}").unwrap();
        fs::write(&f2, "fn main() {}").unwrap();
        fs::write(&f3, "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), &[f1, f2, f3], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert_eq!(content.matches("[[bin]]").count(), 3, "expected 3 [[bin]] entries");
        assert!(content.contains("name = \"driver\""));
        assert!(content.contains("name = \"controller\""));
        assert!(content.contains("name = \"planner\""));
    }

    #[test]
    fn battle_single_source_file_uses_project_name() {
        let dir = tempfile::tempdir().unwrap();
        let f1 = dir.path().join("whatever.rs");
        fs::write(&f1, "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), &[f1], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        // Single file uses project name, not file stem
        assert!(content.contains("name = \"test-project\""),
            "single bin should use project name: {}", content);
        assert_eq!(content.matches("[[bin]]").count(), 1);
    }

    #[test]
    fn battle_git_dep_with_tag() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("bevy".into(), git_dep("https://github.com/bevyengine/bevy", None, Some("v0.15.0"), None));

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("bevy = { git = \"https://github.com/bevyengine/bevy\", tag = \"v0.15.0\" }"),
            "git+tag dep wrong: {}", content);
    }

    #[test]
    fn battle_git_dep_with_rev() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("rapier".into(), git_dep("https://github.com/dimforge/rapier", None, None, Some("abc123def")));

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("rapier = { git = \"https://github.com/dimforge/rapier\", rev = \"abc123def\" }"),
            "git+rev dep wrong: {}", content);
    }

    #[test]
    fn battle_sanitize_special_chars() {
        assert_eq!(sanitize_cargo_name("my robot v2"), "my_robot_v2");
        assert_eq!(sanitize_cargo_name("pkg@1.0/beta"), "pkg_1_0_beta");
        assert_eq!(sanitize_cargo_name("valid-name_ok"), "valid-name_ok");
        assert_eq!(sanitize_cargo_name(""), "");
        assert_eq!(sanitize_cargo_name("a!b#c$d%e"), "a_b_c_d_e");
    }

    #[test]
    fn battle_header_always_present() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.starts_with("# Generated by horus from horus.toml"),
            "missing generated header");
    }

    #[test]
    fn battle_path_dep_relativizes_to_horus_dir() {
        // Path dep "../shared" from project root should become "../../shared" from .horus/
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        // Create sibling directory
        let shared_dir = dir.path().join("libs/shared");
        fs::create_dir_all(&shared_dir).unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("shared".into(), path_dep("libs/shared"));

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        // The path should be relative to .horus/, pointing back up
        assert!(content.contains("shared = { path ="), "path dep missing: {}", content);
        // It should contain ".." to go up from .horus/
        assert!(content.contains(".."), "path should be relative: {}", content);
    }

    #[test]
    fn battle_empty_deps_still_has_deps_section() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("[dependencies]"),
            "should always have [dependencies] section");
    }

    #[test]
    fn battle_crates_io_simple_version_string() {
        // Simple version string with explicit crates.io source
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("anyhow".into(), detailed(DepSource::CratesIo, Some("1.0.86"), &[], false));
        deps.insert("thiserror".into(), detailed(DepSource::CratesIo, Some("1.0"), &[], false));

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("anyhow = \"1.0.86\""), "simple version dep wrong: {}", content);
        assert!(content.contains("thiserror = \"1.0\""), "simple version dep wrong: {}", content);
    }

    #[test]
    fn battle_crates_io_wildcard_version() {
        // No version → "*"
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("rand".into(), detailed(DepSource::CratesIo, None, &[], false));

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("rand = \"*\""), "wildcard version wrong: {}", content);
    }

    #[test]
    fn battle_src_main_fallback() {
        // No source files provided but src/main.rs exists
        let dir = tempfile::tempdir().unwrap();
        let src_dir = dir.path().join("src");
        fs::create_dir_all(&src_dir).unwrap();
        fs::write(src_dir.join("main.rs"), "fn main() {}").unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("[[bin]]"), "should have bin entry for src/main.rs");
        assert!(content.contains("src/main.rs") || content.contains("main.rs"),
            "should reference main.rs: {}", content);
    }

    #[test]
    fn battle_no_main_rs_no_bin() {
        // No main.rs files at all — should not have [[bin]] entry
        let dir = tempfile::tempdir().unwrap();

        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), &[], false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(!content.contains("[[bin]]"), "should not have bin entry without main.rs: {}", content);
    }
}
