//! Generate `.horus/pyproject.toml` from `horus.toml` dependencies.
//!
//! This module is the bridge between the unified horus manifest and the Python
//! build system. It reads `[dependencies]` from `horus.toml`, filters for
//! Python-relevant deps (PyPI, git, path), and produces a valid
//! `pyproject.toml` inside `.horus/`.
//!
//! The generated file is always gitignored and treated as a build artifact.

use anyhow::{Context, Result};
use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::{Path, PathBuf};

use crate::manifest::{DepSource, DependencyValue, HorusManifest};

/// The `.horus` build directory name.
const HORUS_DIR: &str = ".horus";

/// Generate `.horus/pyproject.toml` from a `HorusManifest`.
///
/// - Filters PyPI, path, and git deps from `[dependencies]`
/// - Creates a PEP 621 compliant pyproject.toml
/// - Returns the path to the generated `pyproject.toml`
///
/// # Arguments
///
/// * `manifest` - The parsed horus.toml manifest
/// * `project_dir` - The project root directory (where horus.toml lives)
/// * `include_dev` - Whether to include dev-dependencies
pub fn generate(
    manifest: &HorusManifest,
    project_dir: &Path,
    include_dev: bool,
) -> Result<PathBuf> {
    let horus_dir = project_dir.join(HORUS_DIR);
    fs::create_dir_all(&horus_dir).context("Failed to create .horus directory")?;

    let project_name = &manifest.package.name;
    let version = &manifest.package.version;

    let mut pyproject = String::with_capacity(1024);

    // ── Header ───────────────────────────────────────────────────────────
    writeln!(pyproject, "# Generated by horus from horus.toml — do not edit manually").unwrap();
    writeln!(pyproject, "[build-system]").unwrap();
    writeln!(pyproject, "requires = [\"setuptools>=68.0\"]").unwrap();
    writeln!(pyproject, "build-backend = \"setuptools.build_meta\"").unwrap();
    writeln!(pyproject).unwrap();

    // ── Project metadata (PEP 621) ──────────────────────────────────────
    writeln!(pyproject, "[project]").unwrap();
    writeln!(pyproject, "name = \"{}\"", sanitize_pypi_name(project_name)).unwrap();
    writeln!(pyproject, "version = \"{}\"", version).unwrap();
    writeln!(pyproject, "requires-python = \">=3.10\"").unwrap();

    if let Some(ref desc) = manifest.package.description {
        writeln!(pyproject, "description = \"{}\"", desc).unwrap();
    }

    if !manifest.package.authors.is_empty() {
        writeln!(pyproject, "authors = [").unwrap();
        for author in &manifest.package.authors {
            writeln!(pyproject, "  {{ name = \"{}\" }},", author).unwrap();
        }
        writeln!(pyproject, "]").unwrap();
    }

    // ── Dependencies ─────────────────────────────────────────────────────
    let pypi_deps = collect_python_deps(&manifest.dependencies);
    if !pypi_deps.is_empty() {
        writeln!(pyproject, "dependencies = [").unwrap();
        for dep_str in &pypi_deps {
            writeln!(pyproject, "  \"{}\",", dep_str).unwrap();
        }
        writeln!(pyproject, "]").unwrap();
    } else {
        writeln!(pyproject, "dependencies = []").unwrap();
    }
    writeln!(pyproject).unwrap();

    // ── Optional/dev dependencies ────────────────────────────────────────
    if include_dev && !manifest.dev_dependencies.is_empty() {
        let dev_deps = collect_python_deps(&manifest.dev_dependencies);
        if !dev_deps.is_empty() {
            writeln!(pyproject, "[project.optional-dependencies]").unwrap();
            writeln!(pyproject, "dev = [").unwrap();
            for dep_str in &dev_deps {
                writeln!(pyproject, "  \"{}\",", dep_str).unwrap();
            }
            writeln!(pyproject, "]").unwrap();
            writeln!(pyproject).unwrap();
        }
    }

    // ── Tool configs ─────────────────────────────────────────────────────
    writeln!(pyproject, "[tool.setuptools.packages.find]").unwrap();
    writeln!(pyproject, "where = [\"..\"]").unwrap();
    writeln!(pyproject).unwrap();

    // Ruff config
    writeln!(pyproject, "[tool.ruff]").unwrap();
    writeln!(pyproject, "line-length = 100").unwrap();
    writeln!(pyproject, "target-version = \"py310\"").unwrap();

    // ── Write file ───────────────────────────────────────────────────────
    let pyproject_path = horus_dir.join("pyproject.toml");
    fs::write(&pyproject_path, &pyproject)
        .with_context(|| format!("Failed to write {}", pyproject_path.display()))?;

    Ok(pyproject_path)
}

/// Collect Python dependency strings from a manifest dependency map.
///
/// Filters for PyPI deps and formats as PEP 508 requirement strings.
/// Also includes git deps formatted for pip (using `@ git+url` syntax).
fn collect_python_deps(
    deps: &std::collections::BTreeMap<String, DependencyValue>,
) -> Vec<String> {
    let mut result = Vec::new();

    for (name, dep) in deps {
        match dep.effective_source() {
            DepSource::PyPI => {
                let dep_str = format_pypi_dep(name, dep);
                result.push(dep_str);
            }
            DepSource::Git => {
                if let DependencyValue::Detailed(d) = dep {
                    if let Some(ref git_url) = d.git {
                        let mut spec = format!("{} @ git+{}", name, git_url);
                        if let Some(ref tag) = d.tag {
                            spec.push_str(&format!("@{}", tag));
                        } else if let Some(ref rev) = d.rev {
                            spec.push_str(&format!("@{}", rev));
                        } else if let Some(ref branch) = d.branch {
                            spec.push_str(&format!("@{}", branch));
                        }
                        result.push(spec);
                    }
                }
            }
            DepSource::Path => {
                if let DependencyValue::Detailed(d) = dep {
                    if let Some(ref p) = d.path {
                        // pip can install from paths
                        result.push(format!("{} @ file://{}", name, p));
                    }
                }
            }
            DepSource::CratesIo | DepSource::Registry | DepSource::System => {
                // Not Python deps — skip
            }
        }
    }

    result
}

/// Format a PyPI dependency as a PEP 508 requirement string.
fn format_pypi_dep(name: &str, dep: &DependencyValue) -> String {
    match dep {
        DependencyValue::Simple(v) => {
            if v.starts_with(|c: char| c == '>' || c == '<' || c == '=' || c == '!' || c == '~') {
                format!("{}{}", name, v)
            } else {
                format!("{}=={}", name, v)
            }
        }
        DependencyValue::Detailed(d) => {
            let mut spec = name.to_string();
            if let Some(ref version) = d.version {
                if version.starts_with(|c: char| {
                    c == '>' || c == '<' || c == '=' || c == '!' || c == '~'
                }) {
                    spec.push_str(version);
                } else {
                    spec.push_str("==");
                    spec.push_str(version);
                }
            }
            if !d.features.is_empty() {
                spec.push_str(&format!("[{}]", d.features.join(",")));
            }
            spec
        }
    }
}

/// Sanitize a name for use as a Python package name.
///
/// Replaces characters that are invalid in Python package names with hyphens.
fn sanitize_pypi_name(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.' {
                c
            } else {
                '-'
            }
        })
        .collect()
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::*;
    use std::collections::BTreeMap;

    fn test_manifest(deps: BTreeMap<String, DependencyValue>) -> HorusManifest {
        HorusManifest {
            package: PackageInfo {
                name: "test-project".to_string(),
                version: "0.1.0".to_string(),
                description: Some("A test project".to_string()),
                authors: vec!["Test Author".to_string()],
                license: None,
                edition: "1".to_string(),
                repository: None,
                package_type: None,
                categories: vec![],
            },
            dependencies: deps,
            dev_dependencies: BTreeMap::new(),
            drivers: BTreeMap::new(),
            scripts: BTreeMap::new(),
            ignore: IgnoreConfig::default(),
            enable: vec![],
        }
    }

    #[test]
    fn generate_minimal_pyproject() {
        let dir = tempfile::tempdir().unwrap();
        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), false);
        assert!(result.is_ok());

        let content = fs::read_to_string(result.unwrap()).unwrap();
        assert!(content.contains("name = \"test-project\""));
        assert!(content.contains("version = \"0.1.0\""));
        assert!(content.contains("requires-python = \">=3.10\""));
        assert!(content.contains("[build-system]"));
        assert!(content.contains("dependencies = []"));
    }

    #[test]
    fn generate_with_pypi_deps() {
        let dir = tempfile::tempdir().unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "numpy".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some(">=1.24".to_string()),
                source: Some(DepSource::PyPI),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );
        deps.insert(
            "requests".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some("2.31.0".to_string()),
                source: Some(DepSource::PyPI),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("\"numpy>=1.24\""));
        assert!(content.contains("\"requests==2.31.0\""));
    }

    #[test]
    fn generate_skips_crates_io_deps() {
        let dir = tempfile::tempdir().unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "serde".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some("1.0".to_string()),
                source: Some(DepSource::CratesIo),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );
        deps.insert(
            "torch".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some(">=2.0".to_string()),
                source: Some(DepSource::PyPI),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(!content.contains("serde"));
        assert!(content.contains("\"torch>=2.0\""));
    }

    #[test]
    fn generate_with_git_dep() {
        let dir = tempfile::tempdir().unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "my-lib".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: None,
                source: Some(DepSource::Git),
                features: vec![],
                optional: false,
                path: None,
                git: Some("https://github.com/org/my-lib".to_string()),
                branch: Some("main".to_string()),
                tag: None,
                rev: None,
            }),
        );

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("my-lib @ git+https://github.com/org/my-lib@main"));
    }

    #[test]
    fn generate_with_dev_deps() {
        let dir = tempfile::tempdir().unwrap();

        let mut dev_deps = BTreeMap::new();
        dev_deps.insert(
            "pytest".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some(">=7.0".to_string()),
                source: Some(DepSource::PyPI),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );

        let mut manifest = test_manifest(BTreeMap::new());
        manifest.dev_dependencies = dev_deps;

        // Without include_dev
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(&result).unwrap();
        assert!(!content.contains("[project.optional-dependencies]"));

        // With include_dev
        let result = generate(&manifest, dir.path(), true).unwrap();
        let content = fs::read_to_string(result).unwrap();
        assert!(content.contains("[project.optional-dependencies]"));
        assert!(content.contains("\"pytest>=7.0\""));
    }

    #[test]
    fn generate_with_extras() {
        let dir = tempfile::tempdir().unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "uvicorn".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some(">=0.20".to_string()),
                source: Some(DepSource::PyPI),
                features: vec!["standard".to_string()],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("\"uvicorn>=0.20[standard]\""));
    }

    #[test]
    fn sanitize_pypi_name_works() {
        assert_eq!(sanitize_pypi_name("my-robot"), "my-robot");
        assert_eq!(sanitize_pypi_name("my_robot"), "my_robot");
        assert_eq!(sanitize_pypi_name("my@robot/v2"), "my-robot-v2");
    }

    #[test]
    fn format_simple_version() {
        let dep = DependencyValue::Simple("1.0.0".to_string());
        assert_eq!(format_pypi_dep("requests", &dep), "requests==1.0.0");

        let dep = DependencyValue::Simple(">=2.0".to_string());
        assert_eq!(format_pypi_dep("numpy", &dep), "numpy>=2.0");
    }
}
