//! Generate `.horus/pyproject.toml` from `horus.toml` dependencies.
//!
//! This module is the bridge between the unified horus manifest and the Python
//! build system. It reads `[dependencies]` from `horus.toml`, filters for
//! Python-relevant deps (PyPI, git, path), and produces a valid
//! `pyproject.toml` inside `.horus/`.
//!
//! The generated file is always gitignored and treated as a build artifact.

use anyhow::{Context, Result};
use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::{Path, PathBuf};

use crate::manifest::{DepSource, DependencyValue, HorusManifest};

/// The `.horus` build directory name.
const HORUS_DIR: &str = ".horus";

/// Generate `.horus/pyproject.toml` from a `HorusManifest`.
///
/// - Filters PyPI, path, and git deps from `[dependencies]`
/// - Creates a PEP 621 compliant pyproject.toml
/// - Returns the path to the generated `pyproject.toml`
///
/// # Arguments
///
/// * `manifest` - The parsed horus.toml manifest
/// * `project_dir` - The project root directory (where horus.toml lives)
/// * `include_dev` - Whether to include dev-dependencies
pub fn generate(
    manifest: &HorusManifest,
    project_dir: &Path,
    include_dev: bool,
) -> Result<PathBuf> {
    let horus_dir = project_dir.join(HORUS_DIR);
    fs::create_dir_all(&horus_dir).context("Failed to create .horus directory")?;

    let project_name = &manifest.package.name;
    let version = &manifest.package.version;

    let mut pyproject = String::with_capacity(1024);

    // ── Header ───────────────────────────────────────────────────────────
    writeln!(pyproject, "# Generated by horus from horus.toml — do not edit manually").unwrap();
    writeln!(pyproject, "[build-system]").unwrap();
    writeln!(pyproject, "requires = [\"setuptools>=68.0\"]").unwrap();
    writeln!(pyproject, "build-backend = \"setuptools.build_meta\"").unwrap();
    writeln!(pyproject).unwrap();

    // ── Project metadata (PEP 621) ──────────────────────────────────────
    writeln!(pyproject, "[project]").unwrap();
    writeln!(pyproject, "name = \"{}\"", sanitize_pypi_name(project_name)).unwrap();
    writeln!(pyproject, "version = \"{}\"", version).unwrap();
    writeln!(pyproject, "requires-python = \">=3.10\"").unwrap();

    if let Some(ref desc) = manifest.package.description {
        writeln!(pyproject, "description = \"{}\"", desc).unwrap();
    }

    if !manifest.package.authors.is_empty() {
        writeln!(pyproject, "authors = [").unwrap();
        for author in &manifest.package.authors {
            writeln!(pyproject, "  {{ name = \"{}\" }},", author).unwrap();
        }
        writeln!(pyproject, "]").unwrap();
    }

    // ── Dependencies ─────────────────────────────────────────────────────
    let pypi_deps = collect_python_deps(&manifest.dependencies);
    if !pypi_deps.is_empty() {
        writeln!(pyproject, "dependencies = [").unwrap();
        for dep_str in &pypi_deps {
            writeln!(pyproject, "  \"{}\",", dep_str).unwrap();
        }
        writeln!(pyproject, "]").unwrap();
    } else {
        writeln!(pyproject, "dependencies = []").unwrap();
    }
    writeln!(pyproject).unwrap();

    // ── Optional/dev dependencies ────────────────────────────────────────
    if include_dev && !manifest.dev_dependencies.is_empty() {
        let dev_deps = collect_python_deps(&manifest.dev_dependencies);
        if !dev_deps.is_empty() {
            writeln!(pyproject, "[project.optional-dependencies]").unwrap();
            writeln!(pyproject, "dev = [").unwrap();
            for dep_str in &dev_deps {
                writeln!(pyproject, "  \"{}\",", dep_str).unwrap();
            }
            writeln!(pyproject, "]").unwrap();
            writeln!(pyproject).unwrap();
        }
    }

    // ── Tool configs ─────────────────────────────────────────────────────
    writeln!(pyproject, "[tool.setuptools.packages.find]").unwrap();
    writeln!(pyproject, "where = [\"..\"]").unwrap();
    writeln!(pyproject).unwrap();

    // Ruff config
    writeln!(pyproject, "[tool.ruff]").unwrap();
    writeln!(pyproject, "line-length = 100").unwrap();
    writeln!(pyproject, "target-version = \"py310\"").unwrap();

    // ── Write file ───────────────────────────────────────────────────────
    let pyproject_path = horus_dir.join("pyproject.toml");
    fs::write(&pyproject_path, &pyproject)
        .with_context(|| format!("Failed to write {}", pyproject_path.display()))?;

    Ok(pyproject_path)
}

/// Collect Python dependency strings from a manifest dependency map.
///
/// Filters for PyPI deps and formats as PEP 508 requirement strings.
/// Also includes git deps formatted for pip (using `@ git+url` syntax).
///
/// For Simple deps that default to Registry, the smart source resolver is
/// consulted — if the package is a well-known PyPI package, it's included.
fn collect_python_deps(
    deps: &std::collections::BTreeMap<String, DependencyValue>,
) -> Vec<String> {
    use crate::manifest::Language;
    use crate::source_resolver::PackageSourceResolver;
    let resolver = PackageSourceResolver::new(&[Language::Python]);

    let mut result = Vec::new();

    for (name, dep) in deps {
        let source = match dep.effective_source() {
            DepSource::Registry => {
                // Simple deps default to Registry — use smart resolver to check
                // if it's actually a well-known PyPI package.
                // Only upgrade with High confidence to avoid false positives.
                let resolved = resolver.resolve(name);
                if resolved.confidence == crate::source_resolver::Confidence::High {
                    resolved.source
                } else {
                    DepSource::Registry
                }
            }
            other => other,
        };
        match source {
            DepSource::PyPI => {
                let dep_str = format_pypi_dep(name, dep);
                result.push(dep_str);
            }
            DepSource::Git => {
                if let DependencyValue::Detailed(d) = dep {
                    if let Some(ref git_url) = d.git {
                        let mut spec = format!("{} @ git+{}", name, git_url);
                        if let Some(ref tag) = d.tag {
                            spec.push_str(&format!("@{}", tag));
                        } else if let Some(ref rev) = d.rev {
                            spec.push_str(&format!("@{}", rev));
                        } else if let Some(ref branch) = d.branch {
                            spec.push_str(&format!("@{}", branch));
                        }
                        result.push(spec);
                    }
                }
            }
            DepSource::Path => {
                if let DependencyValue::Detailed(d) = dep {
                    if let Some(ref p) = d.path {
                        // pip can install from paths
                        result.push(format!("{} @ file://{}", name, p));
                    }
                }
            }
            DepSource::CratesIo | DepSource::Registry | DepSource::System => {
                // Not Python deps — skip
            }
        }
    }

    result
}

/// Format a PyPI dependency as a PEP 508 requirement string.
fn format_pypi_dep(name: &str, dep: &DependencyValue) -> String {
    match dep {
        DependencyValue::Simple(v) => {
            if v.starts_with(|c: char| c == '>' || c == '<' || c == '=' || c == '!' || c == '~') {
                format!("{}{}", name, v)
            } else {
                format!("{}=={}", name, v)
            }
        }
        DependencyValue::Detailed(d) => {
            let mut spec = name.to_string();
            if let Some(ref version) = d.version {
                if version.starts_with(|c: char| {
                    c == '>' || c == '<' || c == '=' || c == '!' || c == '~'
                }) {
                    spec.push_str(version);
                } else {
                    spec.push_str("==");
                    spec.push_str(version);
                }
            }
            if !d.features.is_empty() {
                spec.push_str(&format!("[{}]", d.features.join(",")));
            }
            spec
        }
    }
}

/// Sanitize a name for use as a Python package name.
///
/// Replaces characters that are invalid in Python package names with hyphens.
fn sanitize_pypi_name(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.' {
                c
            } else {
                '-'
            }
        })
        .collect()
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::*;
    use std::collections::BTreeMap;

    fn test_manifest(deps: BTreeMap<String, DependencyValue>) -> HorusManifest {
        HorusManifest {
            package: PackageInfo {
                name: "test-project".to_string(),
                version: "0.1.0".to_string(),
                description: Some("A test project".to_string()),
                authors: vec!["Test Author".to_string()],
                license: None,
                edition: "1".to_string(),
                repository: None,
                package_type: None,
                categories: vec![],
            },
            dependencies: deps,
            dev_dependencies: BTreeMap::new(),
            drivers: BTreeMap::new(),
            scripts: BTreeMap::new(),
            ignore: IgnoreConfig::default(),
            enable: vec![],
        }
    }

    #[test]
    fn generate_minimal_pyproject() {
        let dir = tempfile::tempdir().unwrap();
        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), false);
        assert!(result.is_ok());

        let content = fs::read_to_string(result.unwrap()).unwrap();
        assert!(content.contains("name = \"test-project\""));
        assert!(content.contains("version = \"0.1.0\""));
        assert!(content.contains("requires-python = \">=3.10\""));
        assert!(content.contains("[build-system]"));
        assert!(content.contains("dependencies = []"));
    }

    #[test]
    fn generate_with_pypi_deps() {
        let dir = tempfile::tempdir().unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "numpy".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some(">=1.24".to_string()),
                source: Some(DepSource::PyPI),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );
        deps.insert(
            "requests".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some("2.31.0".to_string()),
                source: Some(DepSource::PyPI),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("\"numpy>=1.24\""));
        assert!(content.contains("\"requests==2.31.0\""));
    }

    #[test]
    fn generate_skips_crates_io_deps() {
        let dir = tempfile::tempdir().unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "serde".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some("1.0".to_string()),
                source: Some(DepSource::CratesIo),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );
        deps.insert(
            "torch".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some(">=2.0".to_string()),
                source: Some(DepSource::PyPI),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(!content.contains("serde"));
        assert!(content.contains("\"torch>=2.0\""));
    }

    #[test]
    fn generate_with_git_dep() {
        let dir = tempfile::tempdir().unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "my-lib".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: None,
                source: Some(DepSource::Git),
                features: vec![],
                optional: false,
                path: None,
                git: Some("https://github.com/org/my-lib".to_string()),
                branch: Some("main".to_string()),
                tag: None,
                rev: None,
            }),
        );

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("my-lib @ git+https://github.com/org/my-lib@main"));
    }

    #[test]
    fn generate_with_dev_deps() {
        let dir = tempfile::tempdir().unwrap();

        let mut dev_deps = BTreeMap::new();
        dev_deps.insert(
            "pytest".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some(">=7.0".to_string()),
                source: Some(DepSource::PyPI),
                features: vec![],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );

        let mut manifest = test_manifest(BTreeMap::new());
        manifest.dev_dependencies = dev_deps;

        // Without include_dev
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(&result).unwrap();
        assert!(!content.contains("[project.optional-dependencies]"));

        // With include_dev
        let result = generate(&manifest, dir.path(), true).unwrap();
        let content = fs::read_to_string(result).unwrap();
        assert!(content.contains("[project.optional-dependencies]"));
        assert!(content.contains("\"pytest>=7.0\""));
    }

    #[test]
    fn generate_with_extras() {
        let dir = tempfile::tempdir().unwrap();

        let mut deps = BTreeMap::new();
        deps.insert(
            "uvicorn".to_string(),
            DependencyValue::Detailed(DetailedDependency {
                version: Some(">=0.20".to_string()),
                source: Some(DepSource::PyPI),
                features: vec!["standard".to_string()],
                optional: false,
                path: None,
                git: None,
                branch: None,
                tag: None,
                rev: None,
            }),
        );

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("\"uvicorn>=0.20[standard]\""));
    }

    #[test]
    fn sanitize_pypi_name_works() {
        assert_eq!(sanitize_pypi_name("my-robot"), "my-robot");
        assert_eq!(sanitize_pypi_name("my_robot"), "my_robot");
        assert_eq!(sanitize_pypi_name("my@robot/v2"), "my-robot-v2");
    }

    #[test]
    fn format_simple_version() {
        let dep = DependencyValue::Simple("1.0.0".to_string());
        assert_eq!(format_pypi_dep("requests", &dep), "requests==1.0.0");

        let dep = DependencyValue::Simple(">=2.0".to_string());
        assert_eq!(format_pypi_dep("numpy", &dep), "numpy>=2.0");
    }

    // ── Battle tests ────────────────────────────────────────────────────────

    /// Helper: build a detailed dep with explicit source.
    fn pypi_dep(version: Option<&str>, features: &[&str]) -> DependencyValue {
        DependencyValue::Detailed(DetailedDependency {
            version: version.map(|v| v.to_string()),
            source: Some(DepSource::PyPI),
            features: features.iter().map(|s| s.to_string()).collect(),
            optional: false,
            path: None,
            git: None,
            branch: None,
            tag: None,
            rev: None,
        })
    }

    fn crates_dep(version: &str) -> DependencyValue {
        DependencyValue::Detailed(DetailedDependency {
            version: Some(version.to_string()),
            source: Some(DepSource::CratesIo),
            features: vec![],
            optional: false,
            path: None,
            git: None,
            branch: None,
            tag: None,
            rev: None,
        })
    }

    fn py_git_dep(url: &str, branch: Option<&str>, tag: Option<&str>, rev: Option<&str>) -> DependencyValue {
        DependencyValue::Detailed(DetailedDependency {
            version: None,
            source: Some(DepSource::Git),
            features: vec![],
            optional: false,
            path: None,
            git: Some(url.to_string()),
            branch: branch.map(|s| s.to_string()),
            tag: tag.map(|s| s.to_string()),
            rev: rev.map(|s| s.to_string()),
        })
    }

    fn py_path_dep(p: &str) -> DependencyValue {
        DependencyValue::Detailed(DetailedDependency {
            version: None,
            source: Some(DepSource::Path),
            features: vec![],
            optional: false,
            path: Some(p.to_string()),
            git: None,
            branch: None,
            tag: None,
            rev: None,
        })
    }

    #[test]
    fn battle_pep508_git_with_tag() {
        let dir = tempfile::tempdir().unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("my-lib".into(), py_git_dep("https://github.com/org/my-lib", None, Some("v2.0.0"), None));

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("my-lib @ git+https://github.com/org/my-lib@v2.0.0"),
            "git+tag format wrong: {}", content);
    }

    #[test]
    fn battle_pep508_git_with_rev() {
        let dir = tempfile::tempdir().unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("torch-custom".into(), py_git_dep("https://github.com/org/torch-custom", None, None, Some("abc123")));

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("torch-custom @ git+https://github.com/org/torch-custom@abc123"),
            "git+rev format wrong: {}", content);
    }

    #[test]
    fn battle_pep508_path_dep() {
        let dir = tempfile::tempdir().unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("local-utils".into(), py_path_dep("/home/user/libs/local-utils"));

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("local-utils @ file:///home/user/libs/local-utils"),
            "path dep format wrong: {}", content);
    }

    #[test]
    fn battle_version_operators() {
        let dir = tempfile::tempdir().unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("numpy".into(), pypi_dep(Some(">=1.24"), &[]));
        deps.insert("scipy".into(), pypi_dep(Some("<2.0"), &[]));
        deps.insert("pandas".into(), pypi_dep(Some("~=1.5"), &[]));
        deps.insert("pillow".into(), pypi_dep(Some("!=9.0"), &[]));
        deps.insert("requests".into(), pypi_dep(Some("2.31.0"), &[]));

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("\"numpy>=1.24\""), "ge version wrong: {}", content);
        assert!(content.contains("\"scipy<2.0\""), "lt version wrong: {}", content);
        assert!(content.contains("\"pandas~=1.5\""), "compatible version wrong: {}", content);
        assert!(content.contains("\"pillow!=9.0\""), "ne version wrong: {}", content);
        assert!(content.contains("\"requests==2.31.0\""), "exact version wrong: {}", content);
    }

    #[test]
    fn battle_extras_multiple_features() {
        let dir = tempfile::tempdir().unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("fastapi".into(), pypi_dep(Some(">=0.100"), &["all", "jinja"]));

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("\"fastapi>=0.100[all,jinja]\""),
            "multiple extras wrong: {}", content);
    }

    #[test]
    fn battle_mixed_deps_only_python() {
        // crates.io, registry, system deps should be filtered; only pypi, git, path remain
        let dir = tempfile::tempdir().unwrap();

        let mut deps = BTreeMap::new();
        deps.insert("serde".into(), crates_dep("1.0"));
        deps.insert("horus-nav".into(), DependencyValue::Simple("0.3.0".to_string())); // Registry
        deps.insert("libz-sys".into(), DependencyValue::Detailed(DetailedDependency {
            version: Some("1.0".to_string()),
            source: Some(DepSource::System),
            features: vec![],
            optional: false,
            path: None,
            git: None,
            branch: None,
            tag: None,
            rev: None,
        }));
        deps.insert("numpy".into(), pypi_dep(Some(">=1.24"), &[]));
        deps.insert("my-py-lib".into(), py_git_dep("https://github.com/org/my-py-lib", Some("main"), None, None));

        let manifest = test_manifest(deps);
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        // Python deps present
        assert!(content.contains("numpy"), "pypi dep missing");
        assert!(content.contains("my-py-lib"), "git dep missing");
        // Non-Python deps absent
        assert!(!content.contains("serde"), "crates.io dep should be filtered");
        assert!(!content.contains("horus-nav"), "registry dep should be filtered");
        assert!(!content.contains("libz-sys"), "system dep should be filtered");
    }

    #[test]
    fn battle_author_propagation_single() {
        let dir = tempfile::tempdir().unwrap();
        let manifest = test_manifest(BTreeMap::new());
        // Default test_manifest has authors = ["Test Author"]
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("authors = ["), "authors section missing");
        assert!(content.contains("name = \"Test Author\""), "author name missing: {}", content);
    }

    #[test]
    fn battle_author_propagation_multiple() {
        let dir = tempfile::tempdir().unwrap();
        let mut manifest = test_manifest(BTreeMap::new());
        manifest.package.authors = vec![
            "Alice".to_string(),
            "Bob".to_string(),
            "Charlie".to_string(),
        ];

        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("name = \"Alice\""), "Alice missing");
        assert!(content.contains("name = \"Bob\""), "Bob missing");
        assert!(content.contains("name = \"Charlie\""), "Charlie missing");
    }

    #[test]
    fn battle_no_authors_no_section() {
        let dir = tempfile::tempdir().unwrap();
        let mut manifest = test_manifest(BTreeMap::new());
        manifest.package.authors = vec![];

        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(!content.contains("authors = ["), "empty authors should not produce section");
    }

    #[test]
    fn battle_dev_deps_only_python_filtered() {
        let dir = tempfile::tempdir().unwrap();

        let mut dev_deps = BTreeMap::new();
        dev_deps.insert("pytest".into(), pypi_dep(Some(">=7.0"), &[]));
        dev_deps.insert("criterion".into(), crates_dep("0.5")); // Rust dev dep, should be filtered

        let mut manifest = test_manifest(BTreeMap::new());
        manifest.dev_dependencies = dev_deps;

        let result = generate(&manifest, dir.path(), true).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("[project.optional-dependencies]"), "dev section missing");
        assert!(content.contains("\"pytest>=7.0\""), "pytest missing");
        assert!(!content.contains("criterion"), "criterion (crates.io) should be filtered");
    }

    #[test]
    fn battle_dev_deps_all_non_python_no_section() {
        // When all dev deps are crates.io, the optional-dependencies section should not appear
        let dir = tempfile::tempdir().unwrap();

        let mut dev_deps = BTreeMap::new();
        dev_deps.insert("criterion".into(), crates_dep("0.5"));
        dev_deps.insert("proptest".into(), crates_dep("1.4"));

        let mut manifest = test_manifest(BTreeMap::new());
        manifest.dev_dependencies = dev_deps;

        let result = generate(&manifest, dir.path(), true).unwrap();
        let content = fs::read_to_string(result).unwrap();

        // dev_deps is non-empty BUT after filtering, no Python deps → no section
        assert!(!content.contains("[project.optional-dependencies]"),
            "should not have optional-dependencies when all dev deps are Rust: {}", content);
    }

    #[test]
    fn battle_header_always_generated() {
        let dir = tempfile::tempdir().unwrap();
        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.starts_with("# Generated by horus from horus.toml"),
            "missing generated header");
    }

    #[test]
    fn battle_build_system_always_present() {
        let dir = tempfile::tempdir().unwrap();
        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("[build-system]"), "build-system missing");
        assert!(content.contains("setuptools>=68.0"), "setuptools version missing");
        assert!(content.contains("build-backend = \"setuptools.build_meta\""), "build-backend missing");
    }

    #[test]
    fn battle_description_propagation() {
        let dir = tempfile::tempdir().unwrap();
        let manifest = test_manifest(BTreeMap::new());
        // Default test_manifest has description = Some("A test project")
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("description = \"A test project\""),
            "description missing: {}", content);
    }

    #[test]
    fn battle_no_description_omitted() {
        let dir = tempfile::tempdir().unwrap();
        let mut manifest = test_manifest(BTreeMap::new());
        manifest.package.description = None;

        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(!content.contains("description ="), "description should be omitted when None");
    }

    #[test]
    fn battle_sanitize_pypi_name_edge_cases() {
        assert_eq!(sanitize_pypi_name("pkg@1.0/beta"), "pkg-1.0-beta");
        assert_eq!(sanitize_pypi_name("my.robot"), "my.robot");
        assert_eq!(sanitize_pypi_name(""), "");
        assert_eq!(sanitize_pypi_name("a!b#c"), "a-b-c");
        assert_eq!(sanitize_pypi_name("simple"), "simple");
    }

    #[test]
    fn battle_format_detailed_no_version() {
        // Detailed dep with no version at all
        let dep = DependencyValue::Detailed(DetailedDependency {
            version: None,
            source: Some(DepSource::PyPI),
            features: vec![],
            optional: false,
            path: None,
            git: None,
            branch: None,
            tag: None,
            rev: None,
        });
        // Should produce just the name with no version specifier
        assert_eq!(format_pypi_dep("my-pkg", &dep), "my-pkg");
    }

    #[test]
    fn battle_format_detailed_features_before_version_position() {
        // Features (extras) come after version in PEP 508: name>=1.0[extra1,extra2]
        let dep = DependencyValue::Detailed(DetailedDependency {
            version: Some(">=2.0".to_string()),
            source: Some(DepSource::PyPI),
            features: vec!["async".to_string(), "http2".to_string()],
            optional: false,
            path: None,
            git: None,
            branch: None,
            tag: None,
            rev: None,
        });
        let result = format_pypi_dep("httpx", &dep);
        assert_eq!(result, "httpx>=2.0[async,http2]");
    }

    #[test]
    fn battle_tool_configs_always_present() {
        let dir = tempfile::tempdir().unwrap();
        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("[tool.setuptools.packages.find]"), "setuptools packages config missing");
        assert!(content.contains("where = [\"..\"]"), "package find config missing");
        assert!(content.contains("[tool.ruff]"), "ruff config missing");
        assert!(content.contains("line-length = 100"), "ruff line-length missing");
        assert!(content.contains("target-version = \"py310\""), "ruff target missing");
    }

    #[test]
    fn battle_requires_python_always_present() {
        let dir = tempfile::tempdir().unwrap();
        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("requires-python = \">=3.10\""), "requires-python missing");
    }

    #[test]
    fn battle_empty_deps_produces_empty_array() {
        let dir = tempfile::tempdir().unwrap();
        let manifest = test_manifest(BTreeMap::new());
        let result = generate(&manifest, dir.path(), false).unwrap();
        let content = fs::read_to_string(result).unwrap();

        assert!(content.contains("dependencies = []"), "empty deps should produce empty array");
    }
}
