//! Sync lockfile — pins exact versions of all toolchains and deps.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::Path;

/// Sync lockfile format (TOML).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyncLockfile {
    /// Lockfile format version.
    pub version: u32,
    /// Project name.
    pub project: String,
    /// Pinned versions: name → version string.
    pub pinned: BTreeMap<String, String>,
}

impl SyncLockfile {
    /// Read a lockfile from disk.
    pub fn read(path: &Path) -> anyhow::Result<Self> {
        let content = std::fs::read_to_string(path)
            .map_err(|e| anyhow::anyhow!("Failed to read lockfile {}: {}", path.display(), e))?;
        let lockfile: Self = toml::from_str(&content)
            .map_err(|e| anyhow::anyhow!("Failed to parse lockfile: {}", e))?;
        Ok(lockfile)
    }

    /// Write the lockfile to disk.
    pub fn write(&self, path: &Path) -> anyhow::Result<()> {
        let content = toml::to_string_pretty(self)
            .map_err(|e| anyhow::anyhow!("Failed to serialize lockfile: {}", e))?;
        let header = format!(
            "# Generated by `horus sync` — do not edit manually\n\
             # This file pins exact versions of toolchains and system dependencies.\n\n{}",
            content
        );
        std::fs::write(path, header)
            .map_err(|e| anyhow::anyhow!("Failed to write lockfile {}: {}", path.display(), e))?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lockfile_roundtrip() {
        let mut pinned = BTreeMap::new();
        pinned.insert("rust".to_string(), "1.83.0".to_string());
        pinned.insert("python".to_string(), "3.12.3".to_string());

        let lockfile = SyncLockfile {
            version: 1,
            project: "test-project".to_string(),
            pinned,
        };

        let tmp = std::env::temp_dir().join("horus_sys_test_sync_lockfile.toml");
        lockfile.write(&tmp).unwrap();

        let loaded = SyncLockfile::read(&tmp).unwrap();
        assert_eq!(loaded.version, 1);
        assert_eq!(loaded.project, "test-project");
        assert_eq!(loaded.pinned.get("rust").unwrap(), "1.83.0");
        assert_eq!(loaded.pinned.get("python").unwrap(), "3.12.3");

        std::fs::remove_file(&tmp).ok();
    }
}
