"""Type stubs for horus._horus (Rust extension module).

Auto-generated from PyO3 bindings. Covers all 103+ registered Python types.
"""

from typing import Any, Dict, Iterator, List, Optional, Sequence, Tuple, Union

# ── Module-level functions ───────────────────────────────────────────────────

def get_version() -> str: ...
def get_timestamp_ns() -> int: ...
def cuda_is_available() -> bool: ...
def cuda_device_count() -> int: ...

# ── Exceptions ───────────────────────────────────────────────────────────────

class HorusNotFoundError(Exception): ...
class HorusTransformError(Exception): ...
class HorusTimeoutError(Exception): ...

# ── NodeState ────────────────────────────────────────────────────────────────

class NodeState:
    UNINITIALIZED: str
    INITIALIZING: str
    RUNNING: str
    STOPPING: str
    STOPPED: str
    ERROR: str
    CRASHED: str
    name: str
    def __init__(self, name: str) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

# ── NodeInfo ─────────────────────────────────────────────────────────────────

class NodeInfo:
    def __init__(self, name: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def state(self) -> NodeState: ...
    def log_info(self, message: str) -> None: ...
    def log_warning(self, message: str) -> None: ...
    def log_error(self, message: str) -> None: ...
    def log_debug(self, message: str) -> None: ...
    def log_pub(self, topic: str, data_repr: str, ipc_ns: int) -> None: ...
    def log_sub(self, topic: str, data_repr: str, ipc_ns: int) -> None: ...
    def set_custom_data(self, key: str, value: str) -> None: ...
    def get_custom_data(self, key: str) -> Optional[str]: ...
    def tick_count(self) -> int: ...
    def error_count(self) -> int: ...
    def successful_ticks(self) -> int: ...
    def failed_ticks(self) -> int: ...
    def avg_tick_duration_ms(self) -> float: ...
    def get_uptime(self) -> float: ...
    def get_metrics(self) -> Dict[str, float]: ...
    def transition_to_error(self, error_msg: str) -> None: ...
    def request_stop(self) -> None: ...
    def __repr__(self) -> str: ...

# ── Node ─────────────────────────────────────────────────────────────────────

class Node:
    name: str
    def __init__(self, name: str) -> None: ...
    def init(self, info: NodeInfo) -> None: ...
    def tick(self, info: NodeInfo) -> None: ...
    def shutdown(self, info: NodeInfo) -> None: ...
    def set_callback(self, callback: Any) -> None: ...
    def __repr__(self) -> str: ...

# ── Topic ────────────────────────────────────────────────────────────────────

class Topic:
    def __init__(self, msg_type: type, capacity: Optional[int] = None, endpoint: Optional[str] = None) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def is_network_topic(self) -> bool: ...
    @property
    def endpoint(self) -> Optional[str]: ...
    @property
    def backend_type(self) -> str: ...
    def send(self, message: Any, node: Optional[Any] = None) -> bool: ...
    def recv(self, node: Optional[Any] = None) -> Optional[Any]: ...
    def __repr__(self) -> str: ...

# ── Priority ─────────────────────────────────────────────────────────────────

class Priority:
    CRITICAL: int  # 0
    HIGH: int      # 10
    NORMAL: int    # 50
    LOW: int       # 80
    BACKGROUND: int  # 100
    @staticmethod
    def from_string(priority: str) -> int: ...
    @staticmethod
    def to_string(priority: int) -> str: ...

# ── Miss ─────────────────────────────────────────────────────────────────────

class Miss:
    WARN: str
    SKIP: str
    SAFE_MODE: str
    STOP: str

# ── SchedulerConfig ──────────────────────────────────────────────────────────

class SchedulerConfig:
    tick_rate: float
    budget_enforcement: bool
    deadline_monitoring: bool
    watchdog_enabled: bool
    watchdog_timeout_ms: int
    safety_monitor: bool
    max_deadline_misses: int
    memory_locking: bool
    rt_scheduling_class: bool
    cpu_cores: Optional[List[int]]
    profiling: bool
    black_box_enabled: bool
    black_box_size_mb: int
    telemetry_endpoint: Optional[str]
    recording_enabled: bool
    def __init__(self) -> None: ...
    @staticmethod
    def minimal() -> SchedulerConfig: ...
    @staticmethod
    def with_monitoring() -> SchedulerConfig: ...
    def rate(self, hz: float) -> SchedulerConfig: ...
    def watchdog_ms(self, ms: int) -> SchedulerConfig: ...
    def no_watchdog(self) -> SchedulerConfig: ...
    def blackbox_mb(self, mb: int) -> SchedulerConfig: ...
    def cpu_affinity(self, cores: List[int]) -> SchedulerConfig: ...
    def telemetry(self, endpoint: str) -> SchedulerConfig: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# ── NodeBuilder ──────────────────────────────────────────────────────────────

class NodeBuilder:
    def order(self, order: int) -> NodeBuilder: ...
    def rate(self, rate: float) -> NodeBuilder: ...
    def deadline(self, ms: float) -> NodeBuilder: ...
    def budget(self, us: int) -> NodeBuilder: ...
    def on_miss(self, policy: str) -> NodeBuilder: ...
    def failure_policy(
        self, name: str, *,
        max_retries: Optional[int] = None,
        backoff_ms: Optional[int] = None,
        max_failures: Optional[int] = None,
        cooldown_ms: Optional[int] = None,
    ) -> NodeBuilder: ...
    def on(self, topic: str) -> NodeBuilder: ...
    def compute(self) -> NodeBuilder: ...
    def async_io(self) -> NodeBuilder: ...
    def build(self) -> Scheduler: ...

# ── Scheduler ────────────────────────────────────────────────────────────────

class Scheduler:
    def __init__(self, config: Optional[SchedulerConfig] = None) -> None: ...
    def node(self, node: Any) -> NodeBuilder: ...
    def add(
        self, node: Any, order: int = 100, rate: Optional[float] = None,
        rt: bool = False, deadline: Optional[float] = None,
        budget: Optional[int] = None, failure_policy: Optional[str] = None,
        on_miss: Optional[str] = None,
    ) -> None: ...
    def set_node_rate(self, node_name: str, rate: float) -> None: ...
    def run(self) -> None: ...
    def run_for(self, duration_seconds: float) -> None: ...
    def tick(self, node_names: List[str]) -> None: ...
    def tick_for(self, node_names: List[str], duration_seconds: float) -> None: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def get_node_stats(self, node_name: str) -> Dict[str, Any]: ...
    def remove_node(self, name: str) -> bool: ...
    def get_all_nodes(self) -> List[Dict[str, Any]]: ...
    def get_node_count(self) -> int: ...
    def has_node(self, name: str) -> bool: ...
    def get_node_names(self) -> List[str]: ...
    def get_node_info(self, name: str) -> Optional[int]: ...
    def status(self) -> str: ...
    def capabilities(self) -> Optional[Dict[str, Any]]: ...
    def has_full_rt(self) -> bool: ...
    def degradations(self) -> List[Dict[str, Any]]: ...
    def current_tick(self) -> int: ...
    def scheduler_name(self) -> str: ...
    def safety_stats(self) -> Optional[Dict[str, Any]]: ...
    def is_recording(self) -> bool: ...
    def is_replaying(self) -> bool: ...
    def stop_recording(self) -> List[str]: ...
    @staticmethod
    def list_recordings() -> List[str]: ...
    @staticmethod
    def delete_recording(session_name: str) -> None: ...
    def set_tick_budget(self, node_name: str, us: int) -> None: ...
    def add_critical_node(self, node_name: str, timeout_ms: int) -> None: ...
    def __repr__(self) -> str: ...

# ── Transform ────────────────────────────────────────────────────────────────

class Transform:
    def __init__(self, translation: Optional[List[float]] = None, rotation: Optional[List[float]] = None) -> None: ...
    @staticmethod
    def identity() -> Transform: ...
    @staticmethod
    def from_translation(translation: List[float]) -> Transform: ...
    @staticmethod
    def from_euler(translation: List[float], rpy: List[float]) -> Transform: ...
    @staticmethod
    def from_matrix(matrix: List[List[float]]) -> Transform: ...
    @property
    def translation(self) -> List[float]: ...
    @translation.setter
    def translation(self, value: List[float]) -> None: ...
    @property
    def rotation(self) -> List[float]: ...
    @rotation.setter
    def rotation(self, value: List[float]) -> None: ...
    def to_euler(self) -> List[float]: ...
    def compose(self, other: Transform) -> Transform: ...
    def inverse(self) -> Transform: ...
    def transform_point(self, point: List[float]) -> List[float]: ...
    def transform_vector(self, vector: List[float]) -> List[float]: ...
    def interpolate(self, other: Transform, t: float) -> Transform: ...
    def translation_magnitude(self) -> float: ...
    def rotation_angle(self) -> float: ...
    def to_matrix(self) -> List[List[float]]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# ── TransformFrameConfig ─────────────────────────────────────────────────────

class TransformFrameConfig:
    def __init__(self, max_frames: int = 256, history_len: int = 32) -> None: ...
    @staticmethod
    def small() -> TransformFrameConfig: ...
    @staticmethod
    def medium() -> TransformFrameConfig: ...
    @staticmethod
    def large() -> TransformFrameConfig: ...
    @staticmethod
    def massive() -> TransformFrameConfig: ...
    @property
    def max_frames(self) -> int: ...
    @property
    def history_len(self) -> int: ...
    def memory_estimate(self) -> str: ...
    def __repr__(self) -> str: ...

# ── TransformFrame ───────────────────────────────────────────────────────────

class TransformFrame:
    def __init__(self, config: Optional[TransformFrameConfig] = None) -> None: ...
    @staticmethod
    def small() -> TransformFrame: ...
    @staticmethod
    def medium() -> TransformFrame: ...
    @staticmethod
    def large() -> TransformFrame: ...
    @staticmethod
    def massive() -> TransformFrame: ...
    # Frame management
    def register_frame(self, name: str, parent: Optional[str] = None) -> int: ...
    def register_static_frame(self, name: str, transform: Transform, parent: Optional[str] = None) -> int: ...
    def unregister_frame(self, name: str) -> None: ...
    def frame_id(self, name: str) -> Optional[int]: ...
    def frame_name(self, id: int) -> Optional[str]: ...
    def has_frame(self, name: str) -> bool: ...
    def all_frames(self) -> List[str]: ...
    def frame_count(self) -> int: ...
    # Transform updates
    def update_transform(self, name: str, transform: Transform, timestamp_ns: Optional[int] = None) -> None: ...
    def update_transform_by_id(self, frame_id: int, transform: Transform, timestamp_ns: Optional[int] = None) -> None: ...
    def set_static_transform(self, name: str, transform: Transform) -> None: ...
    # Transform lookups
    def tf(self, src: str, dst: str) -> Transform: ...
    def tf_at(self, src: str, dst: str, timestamp_ns: int) -> Transform: ...
    def tf_by_id(self, src: int, dst: int) -> Optional[Transform]: ...
    def tf_at_with_tolerance(self, src: str, dst: str, timestamp_ns: int, tolerance_ns: int = 100_000_000) -> Transform: ...
    def tf_at_strict(self, src: str, dst: str, timestamp_ns: int) -> Transform: ...
    # Availability checks
    def can_transform(self, src: str, dst: str) -> bool: ...
    def can_transform_at(self, src: str, dst: str, timestamp_ns: int) -> bool: ...
    def can_transform_at_with_tolerance(self, src: str, dst: str, timestamp_ns: int, tolerance_ns: int) -> bool: ...
    # Point/vector transforms
    def transform_point(self, src: str, dst: str, point: List[float]) -> List[float]: ...
    def transform_vector(self, src: str, dst: str, vector: List[float]) -> List[float]: ...
    # Tree navigation
    def parent(self, name: str) -> Optional[str]: ...
    def children(self, name: str) -> List[str]: ...
    def frame_chain(self, src: str, dst: str) -> List[str]: ...
    # Waits & staleness
    def wait_for_transform(self, src: str, dst: str, timeout_sec: float = 5.0) -> Transform: ...
    def wait_for_transform_async(self, src: str, dst: str, timeout_sec: float = 5.0) -> Transform: ...
    def is_stale(self, name: str, max_age_sec: float = 1.0) -> bool: ...
    def time_since_last_update(self, name: str) -> Optional[float]: ...
    # Diagnostics
    def stats(self) -> Dict[str, Any]: ...
    def validate(self) -> None: ...
    def frame_info(self, name: str) -> Optional[Dict[str, Any]]: ...
    def frame_info_all(self) -> List[Dict[str, Any]]: ...
    def frames_as_dot(self) -> str: ...
    def frames_as_yaml(self) -> str: ...
    def format_tree(self) -> str: ...
    def __repr__(self) -> str: ...

# ── Domain Types ─────────────────────────────────────────────────────────────

class Image:
    def __init__(self, height: int, width: int, encoding: str = "rgb8") -> None: ...
    @staticmethod
    def from_numpy(array: Any, encoding: Optional[str] = None) -> Image: ...
    @staticmethod
    def from_torch(tensor: Any, encoding: Optional[str] = None) -> Image: ...
    @staticmethod
    def from_bytes(data: bytes, height: int, width: int, encoding: str = "rgb8") -> Image: ...
    @property
    def height(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def channels(self) -> int: ...
    @property
    def encoding(self) -> str: ...
    @property
    def dtype(self) -> str: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def step(self) -> int: ...
    @property
    def frame_id(self) -> str: ...
    @property
    def timestamp_ns(self) -> int: ...
    @property
    def __array_interface__(self) -> Dict[str, Any]: ...
    def to_numpy(self) -> Any: ...
    def to_torch(self) -> Any: ...
    def to_jax(self) -> Any: ...
    def __dlpack__(self, stream: Optional[int] = None) -> Any: ...
    def __dlpack_device__(self) -> Tuple[int, int]: ...
    def pixel(self, x: int, y: int) -> List[int]: ...
    def set_pixel(self, x: int, y: int, value: List[int]) -> None: ...
    def fill(self, value: List[int]) -> None: ...
    def copy_from(self, data: bytes) -> None: ...
    def roi(self, x: int, y: int, w: int, h: int) -> List[int]: ...
    def set_frame_id(self, id: str) -> None: ...
    def set_timestamp_ns(self, ts: int) -> None: ...
    def is_cpu(self) -> bool: ...
    def is_cuda(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PointCloud:
    def __init__(self, num_points: int, fields: int = 3, dtype: str = "float32") -> None: ...
    @staticmethod
    def from_numpy(array: Any) -> PointCloud: ...
    @staticmethod
    def from_torch(tensor: Any) -> PointCloud: ...
    @property
    def point_count(self) -> int: ...
    @property
    def fields_per_point(self) -> int: ...
    @property
    def dtype(self) -> str: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def frame_id(self) -> str: ...
    @property
    def timestamp_ns(self) -> int: ...
    @property
    def __array_interface__(self) -> Dict[str, Any]: ...
    def to_numpy(self) -> Any: ...
    def to_torch(self) -> Any: ...
    def to_jax(self) -> Any: ...
    def __dlpack__(self, stream: Optional[int] = None) -> Any: ...
    def __dlpack_device__(self) -> Tuple[int, int]: ...
    def point_at(self, idx: int) -> List[float]: ...
    def set_frame_id(self, id: str) -> None: ...
    def set_timestamp_ns(self, ts: int) -> None: ...
    def is_xyz(self) -> bool: ...
    def has_intensity(self) -> bool: ...
    def has_color(self) -> bool: ...
    def is_cpu(self) -> bool: ...
    def is_cuda(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class DepthImage:
    def __init__(self, height: int, width: int, dtype: str = "float32") -> None: ...
    @staticmethod
    def from_numpy(array: Any) -> DepthImage: ...
    @staticmethod
    def from_torch(tensor: Any) -> DepthImage: ...
    @property
    def height(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def dtype(self) -> str: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def frame_id(self) -> str: ...
    @property
    def timestamp_ns(self) -> int: ...
    @property
    def depth_scale(self) -> float: ...
    @property
    def __array_interface__(self) -> Dict[str, Any]: ...
    def to_numpy(self) -> Any: ...
    def to_torch(self) -> Any: ...
    def to_jax(self) -> Any: ...
    def __dlpack__(self, stream: Optional[int] = None) -> Any: ...
    def __dlpack_device__(self) -> Tuple[int, int]: ...
    def get_depth(self, x: int, y: int) -> float: ...
    def set_depth(self, x: int, y: int, value: float) -> None: ...
    def depth_statistics(self) -> Optional[Tuple[float, float, float]]: ...
    def set_frame_id(self, id: str) -> None: ...
    def set_timestamp_ns(self, ts: int) -> None: ...
    def is_meters(self) -> bool: ...
    def is_millimeters(self) -> bool: ...
    def is_cpu(self) -> bool: ...
    def is_cuda(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# ── GPU / Tensor Types ───────────────────────────────────────────────────────

class TensorPool:
    def __init__(self, pool_id: int = 1, size_mb: int = 1024, max_slots: int = 1024) -> None: ...
    @property
    def pool_id(self) -> int: ...
    def alloc(self, shape: List[int], dtype: str = "float32", device: str = "cpu") -> TensorHandle: ...
    def stats(self) -> Dict[str, Any]: ...

class TensorHandle:
    @staticmethod
    def from_descriptor(pool_id: int, descriptor_bytes: bytes) -> TensorHandle: ...
    @staticmethod
    def from_dlpack(obj: Any) -> TensorHandle: ...
    @property
    def shape(self) -> List[int]: ...
    @property
    def dtype(self) -> str: ...
    @property
    def device(self) -> str: ...
    @property
    def numel(self) -> int: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def refcount(self) -> int: ...
    @property
    def __array_interface__(self) -> Dict[str, Any]: ...
    @property
    def __cuda_array_interface__(self) -> Dict[str, Any]: ...
    def to_descriptor(self) -> bytes: ...
    def is_cpu(self) -> bool: ...
    def is_cuda(self) -> bool: ...
    def is_contiguous(self) -> bool: ...
    def numpy(self) -> Any: ...
    def torch(self) -> Any: ...
    def slice(self, start: int, end: int) -> TensorHandle: ...
    def view(self, new_shape: List[int]) -> TensorHandle: ...
    def cpu(self) -> TensorHandle: ...
    def cuda(self, device: str = "cuda:0") -> TensorHandle: ...
    def release(self) -> None: ...
    def __dlpack__(self, stream: Optional[int] = None) -> Any: ...
    def __dlpack_device__(self) -> Tuple[int, int]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# ── Message Types ────────────────────────────────────────────────────────────
# All message classes support: __init__ with kwargs, __repr__, __eq__,
# and have a __topic_name__ class attribute for default topic routing.

class CmdVel:
    __topic_name__: str
    linear: float
    angular: float
    timestamp_ns: int
    def __init__(self, linear: float = 0.0, angular: float = 0.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class Pose2D:
    __topic_name__: str
    x: float
    y: float
    theta: float
    timestamp_ns: int
    def __init__(self, x: float = 0.0, y: float = 0.0, theta: float = 0.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class Imu:
    __topic_name__: str
    accel_x: float
    accel_y: float
    accel_z: float
    gyro_x: float
    gyro_y: float
    gyro_z: float
    timestamp_ns: int
    def __init__(self, accel_x: float = 0.0, accel_y: float = 0.0, accel_z: float = 0.0, gyro_x: float = 0.0, gyro_y: float = 0.0, gyro_z: float = 0.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class Odometry:
    __topic_name__: str
    x: float
    y: float
    theta: float
    linear_velocity: float
    angular_velocity: float
    timestamp_ns: int
    def __init__(self, x: float = 0.0, y: float = 0.0, theta: float = 0.0, linear_velocity: float = 0.0, angular_velocity: float = 0.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class LaserScan:
    __topic_name__: str
    angle_min: float
    angle_max: float
    angle_increment: float
    range_min: float
    range_max: float
    ranges: List[float]
    timestamp_ns: int
    def __init__(self, angle_min: float = 0.0, angle_max: float = 0.0, angle_increment: float = 0.0, range_min: float = 0.0, range_max: float = 0.0, ranges: Optional[List[float]] = None, timestamp_ns: int = 0) -> None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class Twist:
    __topic_name__: str
    linear_x: float
    linear_y: float
    linear_z: float
    angular_x: float
    angular_y: float
    angular_z: float
    timestamp_ns: int
    def __init__(self, linear_x: float = 0.0, linear_y: float = 0.0, linear_z: float = 0.0, angular_x: float = 0.0, angular_y: float = 0.0, angular_z: float = 0.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class Pose3D:
    __topic_name__: str
    x: float
    y: float
    z: float
    qx: float
    qy: float
    qz: float
    qw: float
    timestamp_ns: int
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, qx: float = 0.0, qy: float = 0.0, qz: float = 0.0, qw: float = 1.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class Vector3:
    x: float
    y: float
    z: float
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...
    def __repr__(self) -> str: ...

class Point3:
    x: float
    y: float
    z: float
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...
    def __repr__(self) -> str: ...

class Quaternion:
    x: float
    y: float
    z: float
    w: float
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, w: float = 1.0) -> None: ...
    def __repr__(self) -> str: ...

class JointState:
    __topic_name__: str
    names: List[str]
    positions: List[float]
    velocities: List[float]
    efforts: List[float]
    timestamp_ns: int
    def __init__(self, names: Optional[List[str]] = None, positions: Optional[List[float]] = None, velocities: Optional[List[float]] = None, efforts: Optional[List[float]] = None, timestamp_ns: int = 0) -> None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class Clock:
    __topic_name__: str
    clock_ns: int
    realtime_ns: int
    sim_speed: float
    paused: bool
    source: int
    timestamp_ns: int
    def __init__(self, clock_ns: int = 0, realtime_ns: int = 0, sim_speed: float = 1.0, paused: bool = False, source: int = 0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class TransformStamped:
    tx: float
    ty: float
    tz: float
    rx: float
    ry: float
    rz: float
    rw: float
    timestamp_ns: int
    def __init__(self, tx: float = 0.0, ty: float = 0.0, tz: float = 0.0, rx: float = 0.0, ry: float = 0.0, rz: float = 0.0, rw: float = 1.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class PoseStamped:
    x: float
    y: float
    z: float
    qx: float
    qy: float
    qz: float
    qw: float
    frame_id: str
    timestamp_ns: int
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, qx: float = 0.0, qy: float = 0.0, qz: float = 0.0, qw: float = 1.0, frame_id: str = "", timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class PoseWithCovariance:
    x: float
    y: float
    z: float
    qx: float
    qy: float
    qz: float
    qw: float
    frame_id: str
    timestamp_ns: int
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, qx: float = 0.0, qy: float = 0.0, qz: float = 0.0, qw: float = 1.0, frame_id: str = "", timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class TwistWithCovariance:
    linear_x: float
    linear_y: float
    linear_z: float
    angular_x: float
    angular_y: float
    angular_z: float
    frame_id: str
    timestamp_ns: int
    def __init__(self, linear_x: float = 0.0, linear_y: float = 0.0, linear_z: float = 0.0, angular_x: float = 0.0, angular_y: float = 0.0, angular_z: float = 0.0, frame_id: str = "", timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class Accel:
    linear_x: float
    linear_y: float
    linear_z: float
    angular_x: float
    angular_y: float
    angular_z: float
    timestamp_ns: int
    def __init__(self, linear_x: float = 0.0, linear_y: float = 0.0, linear_z: float = 0.0, angular_x: float = 0.0, angular_y: float = 0.0, angular_z: float = 0.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class AccelStamped:
    linear_x: float
    linear_y: float
    linear_z: float
    angular_x: float
    angular_y: float
    angular_z: float
    frame_id: str
    timestamp_ns: int
    def __init__(self, linear_x: float = 0.0, linear_y: float = 0.0, linear_z: float = 0.0, angular_x: float = 0.0, angular_y: float = 0.0, angular_z: float = 0.0, frame_id: str = "", timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

# Control messages

class MotorCommand:
    __topic_name__: str
    motor_id: int
    mode: int
    target: float
    max_velocity: float
    max_acceleration: float
    feed_forward: float
    enable: bool
    timestamp_ns: int
    def __init__(self, motor_id: int = 0, mode: int = 0, target: float = 0.0, max_velocity: float = ..., max_acceleration: float = ..., feed_forward: float = 0.0, enable: bool = True, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class ServoCommand:
    __topic_name__: str
    servo_id: int
    position: float
    speed: float
    enable: bool
    timestamp_ns: int
    def __init__(self, servo_id: int = 0, position: float = 0.0, speed: float = 0.5, enable: bool = True, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class DifferentialDriveCommand:
    __topic_name__: str
    left_velocity: float
    right_velocity: float
    max_acceleration: float
    enable: bool
    timestamp_ns: int
    def __init__(self, left_velocity: float = 0.0, right_velocity: float = 0.0, max_acceleration: float = ..., enable: bool = True, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class PidConfig:
    __topic_name__: str
    kp: float
    ki: float
    kd: float
    controller_id: int
    integral_limit: float
    output_limit: float
    anti_windup: bool
    timestamp_ns: int
    def __init__(self, kp: float = 1.0, ki: float = 0.0, kd: float = 0.0, controller_id: int = 0, integral_limit: float = ..., output_limit: float = ..., anti_windup: bool = True, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class TrajectoryPoint:
    position: List[float]
    velocity: List[float]
    acceleration: List[float]
    orientation: List[float]
    angular_velocity: List[float]
    time_from_start: float
    def __init__(self, position: Optional[List[float]] = None, velocity: Optional[List[float]] = None, acceleration: Optional[List[float]] = None, orientation: Optional[List[float]] = None, angular_velocity: Optional[List[float]] = None, time_from_start: float = 0.0) -> None: ...
    def __repr__(self) -> str: ...

class JointCommand:
    __topic_name__: str
    names: List[str]
    positions: List[float]
    velocities: List[float]
    efforts: List[float]
    modes: List[int]
    timestamp_ns: int
    def __init__(self, names: Optional[List[str]] = None, positions: Optional[List[float]] = None, velocities: Optional[List[float]] = None, efforts: Optional[List[float]] = None, modes: Optional[List[int]] = None, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

# Sensor messages

class RangeSensor:
    __topic_name__: str
    range: float
    sensor_type: int
    field_of_view: float
    min_range: float
    max_range: float
    timestamp_ns: int
    def __init__(self, range: float = 0.0, sensor_type: int = 0, field_of_view: float = 0.1, min_range: float = 0.02, max_range: float = 4.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class BatteryState:
    __topic_name__: str
    voltage: float
    percentage: float
    current: float
    temperature: float
    power_supply_status: int
    timestamp_ns: int
    def __init__(self, voltage: float = 0.0, percentage: float = 0.0, current: float = 0.0, temperature: float = 25.0, power_supply_status: int = 0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class NavSatFix:
    __topic_name__: str
    latitude: float
    longitude: float
    altitude: float
    timestamp_ns: int
    def __init__(self, latitude: float = 0.0, longitude: float = 0.0, altitude: float = 0.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class MagneticField:
    __topic_name__: str
    x: float
    y: float
    z: float
    timestamp_ns: int
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class Temperature:
    __topic_name__: str
    temperature: float
    variance: float
    timestamp_ns: int
    def __init__(self, temperature: float = 0.0, variance: float = 0.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class FluidPressure:
    __topic_name__: str
    pressure: float
    variance: float
    timestamp_ns: int
    def __init__(self, pressure: float = 0.0, variance: float = 0.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class Illuminance:
    __topic_name__: str
    illuminance: float
    variance: float
    timestamp_ns: int
    def __init__(self, illuminance: float = 0.0, variance: float = 0.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class TimeReference:
    __topic_name__: str
    time_ref_ns: int
    source: str
    offset_ns: int
    timestamp_ns: int
    def __init__(self, time_ref_ns: int = 0, source: str = "", offset_ns: int = 0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

# Diagnostics messages

class Heartbeat:
    __topic_name__: str
    node_name: str
    node_id: int
    timestamp_ns: int
    def __init__(self, node_name: str = "", node_id: int = 0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class DiagnosticStatus:
    __topic_name__: str
    level: int
    code: int
    message: str
    component: str
    timestamp_ns: int
    def __init__(self, level: int = 0, code: int = 0, message: str = "", component: str = "", timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class EmergencyStop:
    __topic_name__: str
    engaged: bool
    reason: str
    timestamp_ns: int
    def __init__(self, engaged: bool = True, reason: str = "", timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class ResourceUsage:
    __topic_name__: str
    cpu_percent: float
    memory_bytes: int
    memory_percent: float
    timestamp_ns: int
    def __init__(self, cpu_percent: float = 0.0, memory_bytes: int = 0, memory_percent: float = 0.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

# Navigation messages

class NavGoal:
    __topic_name__: str
    x: float
    y: float
    theta: float
    position_tolerance: float
    angle_tolerance: float
    timeout: float
    timestamp_ns: int
    def __init__(self, x: float = 0.0, y: float = 0.0, theta: float = 0.0, position_tolerance: float = 0.1, angle_tolerance: float = 0.1, timeout: float = 30.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class GoalResult:
    __topic_name__: str
    goal_id: int
    status: int
    progress: float
    timestamp_ns: int
    def __init__(self, goal_id: int = 0, status: int = 0, progress: float = 0.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class Waypoint:
    x: float
    y: float
    theta: float
    def __init__(self, x: float = 0.0, y: float = 0.0, theta: float = 0.0) -> None: ...
    def __repr__(self) -> str: ...

class PathPlan:
    __topic_name__: str
    goal_x: float
    goal_y: float
    goal_theta: float
    timestamp_ns: int
    def __init__(self, goal_x: float = 0.0, goal_y: float = 0.0, goal_theta: float = 0.0, timestamp_ns: int = 0) -> None: ...
    @staticmethod
    def from_waypoints(waypoints: List[Any], goal_x: float = 0.0, goal_y: float = 0.0, goal_theta: float = 0.0) -> PathPlan: ...
    def __repr__(self) -> str: ...

class OccupancyGrid:
    __topic_name__: str
    width: int
    height: int
    resolution: float
    def __init__(self, width: int = 0, height: int = 0, resolution: float = 0.05) -> None: ...
    def __repr__(self) -> str: ...

# Force/haptics messages

class WrenchStamped:
    __topic_name__: str
    fx: float
    fy: float
    fz: float
    tx: float
    ty: float
    tz: float
    timestamp_ns: int
    def __init__(self, fx: float = 0.0, fy: float = 0.0, fz: float = 0.0, tx: float = 0.0, ty: float = 0.0, tz: float = 0.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class ForceCommand:
    __topic_name__: str
    fx: float
    fy: float
    fz: float
    tx: float
    ty: float
    tz: float
    timeout: float
    timestamp_ns: int
    def __init__(self, fx: float = 0.0, fy: float = 0.0, fz: float = 0.0, tx: float = 0.0, ty: float = 0.0, tz: float = 0.0, timeout: float = 0.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class ContactInfo:
    __topic_name__: str
    state: int
    contact_force: float
    confidence: float
    timestamp_ns: int
    def __init__(self, state: int = 0, contact_force: float = 0.0, confidence: float = 0.0, timestamp_ns: int = 0) -> None: ...
    def __repr__(self) -> str: ...

# Input messages

class JoystickInput:
    __topic_name__: str
    joystick_id: int
    element_id: int
    value: float
    pressed: bool
    def __init__(self, joystick_id: int = 0, element_id: int = 0, value: float = 0.0, pressed: bool = False) -> None: ...
    def __repr__(self) -> str: ...

class KeyboardInput:
    __topic_name__: str
    key_name: str
    code: int
    pressed: bool
    modifiers: int
    def __init__(self, key_name: str = "", code: int = 0, pressed: bool = True, modifiers: int = 0) -> None: ...
    def __repr__(self) -> str: ...

# Vision messages

class CompressedImage:
    __topic_name__: str
    format: str
    data: List[int]
    width: int
    height: int
    def __init__(self, format: str = "jpeg", data: Optional[List[int]] = None, width: int = 0, height: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class CameraInfo:
    __topic_name__: str
    width: int
    height: int
    fx: float
    fy: float
    cx: float
    cy: float
    def __init__(self, width: int = 0, height: int = 0, fx: float = 0.0, fy: float = 0.0, cx: float = 0.0, cy: float = 0.0) -> None: ...
    def __repr__(self) -> str: ...

class RegionOfInterest:
    x: int
    y: int
    width: int
    height: int
    do_rectify: bool
    def __init__(self, x: int = 0, y: int = 0, width: int = 0, height: int = 0, do_rectify: bool = False) -> None: ...
    def __repr__(self) -> str: ...

# Detection messages (message-level, distinct from perception submodule)

class BoundingBox3D:
    cx: float
    cy: float
    cz: float
    length: float
    width: float
    height: float
    yaw: float
    def __init__(self, cx: float = 0.0, cy: float = 0.0, cz: float = 0.0, length: float = 0.0, width: float = 0.0, height: float = 0.0, yaw: float = 0.0) -> None: ...
    @staticmethod
    def from_euler(cx: float, cy: float, cz: float, length: float, width: float, height: float, roll: float, pitch: float, yaw: float) -> BoundingBox3D: ...
    def __repr__(self) -> str: ...

class Detection3D:
    class_name: str
    confidence: float
    cx: float
    cy: float
    cz: float
    length: float
    width: float
    height: float
    yaw: float
    def __init__(self, class_name: str = "", confidence: float = 0.0, cx: float = 0.0, cy: float = 0.0, cz: float = 0.0, length: float = 0.0, width: float = 0.0, height: float = 0.0, yaw: float = 0.0) -> None: ...
    def __repr__(self) -> str: ...

class SegmentationMask:
    width: int
    height: int
    mask_type: int
    num_classes: int
    def __init__(self, width: int = 0, height: int = 0, mask_type: int = 0, num_classes: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class Landmark3D:
    x: float
    y: float
    z: float
    visibility: float
    index: int
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, visibility: float = 1.0, index: int = 0) -> None: ...
    def __repr__(self) -> str: ...

class PointField:
    name: str
    offset: int
    datatype: int
    count: int
    def __init__(self, name: str = "", offset: int = 0, datatype: int = 0, count: int = 1) -> None: ...
    def __repr__(self) -> str: ...

# ── Perception Submodule ─────────────────────────────────────────────────────

class perception:
    class BoundingBox2D:
        def __init__(self, x: float = 0.0, y: float = 0.0, width: float = 0.0, height: float = 0.0) -> None: ...
        @staticmethod
        def from_center(cx: float, cy: float, width: float, height: float) -> perception.BoundingBox2D: ...
        @property
        def x(self) -> float: ...
        @property
        def y(self) -> float: ...
        @property
        def width(self) -> float: ...
        @property
        def height(self) -> float: ...
        @property
        def center_x(self) -> float: ...
        @property
        def center_y(self) -> float: ...
        @property
        def area(self) -> float: ...
        def iou(self, other: perception.BoundingBox2D) -> float: ...
        def as_tuple(self) -> Tuple[float, float, float, float]: ...
        def as_xyxy(self) -> Tuple[float, float, float, float]: ...
        def __repr__(self) -> str: ...

    class Detection:
        def __init__(self, class_name: str, confidence: float, x: float, y: float, width: float, height: float, class_id: int = 0, instance_id: int = 0) -> None: ...
        @staticmethod
        def from_bbox(bbox: perception.BoundingBox2D, class_name: str, confidence: float, class_id: int = 0, instance_id: int = 0) -> perception.Detection: ...
        @staticmethod
        def from_bytes(data: bytes) -> perception.Detection: ...
        @property
        def bbox(self) -> perception.BoundingBox2D: ...
        @property
        def confidence(self) -> float: ...
        @property
        def class_id(self) -> int: ...
        @property
        def class_name(self) -> str: ...
        @property
        def instance_id(self) -> int: ...
        def is_confident(self, threshold: float) -> bool: ...
        def to_bytes(self) -> bytes: ...
        def __repr__(self) -> str: ...

    class DetectionList:
        def __init__(self) -> None: ...
        @staticmethod
        def from_list(detections: List[perception.Detection]) -> perception.DetectionList: ...
        @staticmethod
        def from_bytes(data: bytes) -> perception.DetectionList: ...
        def append(self, detection: perception.Detection) -> None: ...
        def filter_confidence(self, threshold: float) -> perception.DetectionList: ...
        def filter_class(self, class_name: str) -> perception.DetectionList: ...
        def to_bytes(self) -> bytes: ...
        def to_dicts(self) -> List[Dict[str, Any]]: ...
        def __len__(self) -> int: ...
        def __getitem__(self, index: int) -> perception.Detection: ...
        def __iter__(self) -> Iterator[perception.Detection]: ...
        def __repr__(self) -> str: ...

    class PointXYZ:
        def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...
        @property
        def x(self) -> float: ...
        @property
        def y(self) -> float: ...
        @property
        def z(self) -> float: ...
        def distance(self) -> float: ...
        def distance_to(self, other: perception.PointXYZ) -> float: ...
        def as_tuple(self) -> Tuple[float, float, float]: ...
        def to_numpy(self) -> Any: ...
        def __repr__(self) -> str: ...

    class PointXYZRGB:
        def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, r: int = 255, g: int = 255, b: int = 255) -> None: ...
        @property
        def x(self) -> float: ...
        @property
        def y(self) -> float: ...
        @property
        def z(self) -> float: ...
        @property
        def r(self) -> int: ...
        @property
        def g(self) -> int: ...
        @property
        def b(self) -> int: ...
        def rgb(self) -> Tuple[int, int, int]: ...
        def xyz(self) -> perception.PointXYZ: ...
        def __repr__(self) -> str: ...

    class Landmark:
        def __init__(self, x: float, y: float, visibility: float = 1.0, index: int = 0) -> None: ...
        @property
        def x(self) -> float: ...
        @property
        def y(self) -> float: ...
        @property
        def visibility(self) -> float: ...
        @property
        def index(self) -> int: ...
        def is_visible(self, threshold: float) -> bool: ...
        def distance_to(self, other: perception.Landmark) -> float: ...
        def __repr__(self) -> str: ...

    class TrackedObject:
        def __init__(self, track_id: int, bbox: perception.BoundingBox2D, class_name: str, confidence: float, class_id: int = 0) -> None: ...
        @property
        def bbox(self) -> perception.BoundingBox2D: ...
        @property
        def track_id(self) -> int: ...
        @property
        def confidence(self) -> float: ...
        @property
        def class_id(self) -> int: ...
        @property
        def class_name(self) -> str: ...
        @property
        def velocity(self) -> Tuple[float, float]: ...
        @property
        def age(self) -> int: ...
        @property
        def hits(self) -> int: ...
        def speed(self) -> float: ...
        def is_tentative(self) -> bool: ...
        def is_confirmed(self) -> bool: ...
        def is_deleted(self) -> bool: ...
        def update(self, bbox: perception.BoundingBox2D, confidence: float) -> None: ...
        def mark_missed(self) -> None: ...
        def confirm(self) -> None: ...
        def delete(self) -> None: ...
        def __repr__(self) -> str: ...

    class PointCloudBuffer:
        def __init__(self, capacity: int = 0, frame_id: str = "") -> None: ...
        @staticmethod
        def from_numpy(array: Any, frame_id: str = "") -> perception.PointCloudBuffer: ...
        @property
        def frame_id(self) -> str: ...
        def add_point(self, x: float, y: float, z: float) -> None: ...
        def to_numpy(self) -> Any: ...
        def to_bytes(self) -> bytes: ...
        def __len__(self) -> int: ...
        def __getitem__(self, index: int) -> perception.PointXYZ: ...
        def __repr__(self) -> str: ...

    class COCOPose:
        NOSE: int
        LEFT_EYE: int
        RIGHT_EYE: int
        LEFT_EAR: int
        RIGHT_EAR: int
        LEFT_SHOULDER: int
        RIGHT_SHOULDER: int
        LEFT_ELBOW: int
        RIGHT_ELBOW: int
        LEFT_WRIST: int
        RIGHT_WRIST: int
        LEFT_HIP: int
        RIGHT_HIP: int
        LEFT_KNEE: int
        RIGHT_KNEE: int
        LEFT_ANKLE: int
        RIGHT_ANKLE: int
        NUM_KEYPOINTS: int
